### ISSUE TITLE
some Nav links are not working , Not Responsive UI , also some of the nav links do not have Engaging UI (menu , services) .

### ISSUE THREAD

**Issue by Mohit5Upadhyay** [khushi-joshi-05/Food-ordering-website#1]
I want to contribute under GSSoC'24 . Please Assign this to me , as currently website is not responsive and also home , cart , contact us link are not linked also services and menu link are not arranged in proper manner (UI Not Good ) . please assign it to me .

**Comment by kashyapsaksham012** [comment]
With expertise in frontend development and UI/UX design, I'll enhance the user experience by resolving issues like non-functional links, unresponsive UI, and unengaging navigation elements.

**Comment by nandu-99** [comment]
Please assign this to me, i can work on this, and i have made all the local setup ready

**Comment by khushi-joshi-05** [comment]
@Mohit5Upadhyay the issue is being assigned to you. Do improve the UI and link the pages.
All the best!

**Comment by kanikaa-3018** [comment]
please assign this project to me for GSSoc'24 ( nav bar non-responsive, buttons are unclickable, hover effect missing , links are missing in footer section, no backend for "ORDER NOW")

**Comment by khushi-joshi-05** [comment]
@kanikaa-3018 i have assigned you the issue. It will be great if you will work on "ORDER NOW" and its backend as mentioned.

**Comment by hussain123sahil** [comment]
please assign me this issue.

**Comment by Pujan-sarkar** [comment]
Is this issue solved , I want to contribute in this issue under GSSOC'24 . Will it be possible to assign this issue to me please @khushi-joshi-05

**Comment by Mohit5Upadhyay** [comment]
@khushi-joshi-05  i have solved the required issues related with responsiveness and hovering effect , please do accept the PR.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by sahithinandikula** [comment]
@khushi-joshi-05 I would love to contribute for GSSOC'24 by working on this issue .I hope my request is considered
