### ISSUE TITLE
 File Structure Optimization in Codebase

### ISSUE THREAD

**Issue by nandu-99** [khushi-joshi-05/Food-ordering-website#10]
The current file structure in our open-source organization's codebase lacks organization, hindering code readability and maintenance. To enhance efficiency, we propose structuring files into distinct folders: one for HTML files, one for CSS files (excluding index.css), one for JavaScript files (excluding index.js), and a folder for images. This approach streamlines navigation and upkeep, fostering better code management. Please assign this issue to me, i want to work on this issue, and resolve this as soon as possible.

**Comment by khushi-joshi-05** [comment]
@nandu-99 I have assigned you the issue. Will be glad to have done the file optimization.

**Comment by nandu-99** [comment]
Thank you so much
