### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by Ramsey99** [khushi-joshi-05/Food-ordering-website#100]
There is no favicon on this website. I want to add a favicon. If you want anything specific for this website. I will try my best.

**Comment by Mujtabaa07** [comment]
Please assign me this issue @khushi-joshi-05

**Comment by ShrestyTyagi** [comment]
Describe:
I would like to add favicon in this beautiful website. Favicon enhances the overall experience of this website.

I will complete this as soon as possible.
I request you to kindly assign this issue to me.  @khushi-joshi-05 
Request you to label this issue as well.

**Comment by HimangshuRanjan** [comment]
i would like to fix this issue

**Comment by Ramsey99** [comment]
I would like to add favicon on this website.
