### ISSUE TITLE
Bug: linkdin button not hovering 

### ISSUE THREAD

**Issue by puneet426** [khushi-joshi-05/Food-ordering-website#1014]
linkdin button in footer is not hovering while all others are hovering

https://github.com/khushi-joshi-05/Food-ordering-website/assets/168094736/caddcf0c-cd0a-42d4-9d79-48d516937e45

@khushi-joshi-05 please assign this issue to me and add level like GSSoC and also add level of project like leven1 or 2

**Comment by puneet426** [comment]
@sunny0625 please assign this issue to me

**Comment by savvymonk05** [comment]
@khushi-joshi-05 please assign this issue to me

**Comment by Aditi-Gopinath** [comment]
Can you please assign this issue under Gssoc'24 @khushi-joshi-05

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
