### ISSUE TITLE
adding a donate button 

### ISSUE THREAD

**Issue by sahithinandikula** [khushi-joshi-05/Food-ordering-website#1020]
Problem:

The web page can have a donate option to provide the user the chance to donate money which will be further used for the enhancing the lifestyle of the needy such as rural and empowerment.It also depicts that the website cares about human values and food .It have higher chances of improving customer interaction .

Solution:
creating a button to donate and add the amount mentioned by the user.

screenshot:

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/138794574/70403f54-2346-4178-a3f5-96a84d78db39)

**Comment by Pragya1601** [comment]
please assign this issue to me

**Comment by Charmie1234** [comment]
Please assign this issue to me
