### ISSUE TITLE
Add the Feedback section

### ISSUE THREAD

**Issue by Riddhi162** [khushi-joshi-05/Food-ordering-website#103]
The website do not have a feedback section so we can add it and maybe create a form that takes
1. Name
2. email
3. phone number 
4. also we can provide options like sections like food quality, service, order accuracy, staff behaviour and have radio buttons for it

**Comment by Riddhi162** [comment]
@khushi-joshi-05 i have previously worked with html,css,javascript can you please assign this issue

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by Gauri-Dabhade** [comment]
i would like to work on feedback section ,by adding rating system.

**Comment by Aishikap** [comment]
i would like to work on this issue. please assign me
