### ISSUE TITLE
Bug in Footer of services page.

### ISSUE THREAD

**Issue by vaishali-sharma-20** [khushi-joshi-05/Food-ordering-website#1032]
Hello @khushi-joshi-05, I am a GSSOC'24 Contributor and I would like to contribute to this project. I have noticed an issue in the footer of the Services page. that the footer is not aligned and does not cover the proper width of the page.
I request you assign this task to me so, that can make relevant changes and updates.

![Screenshot 2024-06-08 211053](https://github.com/khushi-joshi-05/Food-ordering-website/assets/89777420/db930212-6dae-4f7c-8393-9a3beac17dc5)

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
