### ISSUE TITLE
Fix the broken Navbar and issue with resizeable message box 

### ISSUE THREAD

**Issue by Pratik2401** [khushi-joshi-05/Food-ordering-website#104]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/105542579/c65f9fd9-4952-422d-aedc-81c81fa6b698)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/105542579/a255695f-b322-439c-998f-20a42d0398da)
The navbar links are broken and the resize option of textbox should be only in y-axis or it deattract the site

**Comment by DevNandini02** [comment]
Please label the issue.

**Comment by ShatakshiPalli** [comment]
Please assign me this issue. I would like to work on this.

**Comment by Pratik2401** [comment]
> Please assign me this issue. I would like to work on this.

Hey can you please find your own issues it takes time to find one
