### ISSUE TITLE
[Bug]: Show and Hide Button is not working

### ISSUE THREAD

**Issue by SrinivasDevolper** [khushi-joshi-05/Food-ordering-website#1043]
The Show and Hide Button is not working in the password of the Login and Sign-up pages

**I am GSSOC24 contributor
Please assign me, I would like to work on it**

https://github.com/khushi-joshi-05/Food-ordering-website/assets/121508628/dd9db640-d27e-4539-bda9-f5e9cc3c37d0

**Comment by Unknnown-Mayank** [comment]
Hello Ma'am

Just saw an issue in your "Food-ordering-website"
that during login , when we click on eye icon 
It should show the password but the icon is not working
I can fix the issue by making it to work
So, Kindly allow it to me
Thanks
