### ISSUE TITLE
Static Cards 

### ISSUE THREAD

**Issue by Saloni-0465** [khushi-joshi-05/Food-ordering-website#105]
The cards on the later sections of website are static. I want to make the website's static cards dynamic, like expanding on hover or implementing a more interactive style.
Kindly assign me the issue please.

**Comment by singhpratibha98** [comment]
Having thoroughly examined the platform, I believe that enhancing the static card can significantly improve the user experience and contribute to the overall success of the platform. My experience in HTML , CSS , Javascript , React js equips me with the necessary expertise to tackle this task effectively.

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
