### ISSUE TITLE
Navbar ui enhancement 

### ISSUE THREAD

**Issue by parikhitritgithub** [khushi-joshi-05/Food-ordering-website#1065]
i want to work on the  broken navbar ui  .. please assign this to me  under GSSOC 2024 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/124444610/157c961e-0b12-41a7-9a80-6fd930e400db)

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05 please assign this to me i am GSSOC'24 contributor and have 2+year of experience in development

**Comment by priti200** [comment]
Hey @parikhitritgithub ,

I would like to work upon this issue which is to enhance the navbar. I've hands on experience in creating a navbar for my personal projects. So i can assure you that i can work upon this smoothly.

Thankyou!!!
