### ISSUE TITLE
hamburger not working in offer page

### ISSUE THREAD

**Issue by DevGajjar28** [khushi-joshi-05/Food-ordering-website#1068]
In offer page hamburger not working in small devices 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/145287513/cc74d7cf-82bf-4dd0-8cd0-972fa9e09726)
here is image can check this out .

**Comment by priti200** [comment]
Hey @DevGajjar28,

I would like to work upon this issue.  I can make the hamburger button functional if you assign me with this issue. 

Also, please label this issue.

thankyou!!!

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
