### ISSUE TITLE
Cards in CUSTOMER OPTION section are very near to each other

### ISSUE THREAD

**Issue by SumithThota** [khushi-joshi-05/Food-ordering-website#1071]
Cards in CUSTOMER OPTION section are very near to each other a better spacing required in between them let me fixt it
![Screenshot 2024-06-11 092245](https://github.com/khushi-joshi-05/Food-ordering-website/assets/108344062/40b88aac-756a-4a01-b0e0-44eb09b3d6a6)

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05 please assign this to me i am GSSOC'24 contributor and has 2+ years of experience in development

**Comment by SumithThota** [comment]
Hello @sunny0625 please add appropriate levels label
