### ISSUE TITLE
Adding Navbar and footer to sign up page.

### ISSUE THREAD

**Issue by Its-your-rj** [khushi-joshi-05/Food-ordering-website#1073]
Please assign me a Task to add Navbar and footer to sign up page Under GSSOC' and along with the label of level 3
<img width="949" alt="Screenshot 2024-06-11 120243" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/131703345/3571a961-1dd0-4f77-8a11-72d965eb3f23">

I would love to work on this issue please assign me this.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05 please assign this to me i am GSSOC'24 contirbutor and has 2+year of experience in development

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by Its-your-rj** [comment]
@sunny0625 please add label of level3 along with gssoc

**Comment by dakshika-chaudhary** [comment]
I would like to work on it . I will add the header and footer to it by adding the functionalities to the header like making it fixed and making is navigatable.

**Comment by dakshika-chaudhary** [comment]
Please @khushi-joshi-05  @sunny0625  assign it to me
