### ISSUE TITLE
The dark mode button is not functional

### ISSUE THREAD

**Issue by samarsajad** [khushi-joshi-05/Food-ordering-website#1088]
The dark mode button fails to serve its purpose. When the button is clicked it should apply a dark theme to the website.

**Comment by samarsajad** [comment]
Please assign this issue to me @sunny0625 @khushi-joshi-05

**Comment by guneetdewangan9** [comment]
Dark mode button is not functioning. I would like to work on this issue. Please assign me this issue under GSSoC' 24 to contribute to this project and make website functional with more attractive features.

**Comment by priti200** [comment]
I would like to makt the dark mode button functional by fixing the bug. So @admin could you please assign me this issue.

**Comment by samarsajad** [comment]
Please assign this issue to me @sunny0625 @khushi-joshi-05
