### ISSUE TITLE
addition of favicons to services,menu,contact us page

### ISSUE THREAD

**Issue by CoderGirl2844** [khushi-joshi-05/Food-ordering-website#1091]
addition of favicons would enhance the look of the website...Please Assign this issue to me

**Comment by priti200** [comment]
Hey @CoderGirl2844,

Please label this issue & assign me to work on this issue, I can add favicons to services,menu , contact us page to make it more attractive. 

thankyou!!!

**Comment by CoderGirl2844** [comment]
favicons are already added
