### ISSUE TITLE
App LOGO is not visible on the signup page

### ISSUE THREAD

**Issue by ayushrskiaa** [khushi-joshi-05/Food-ordering-website#1098]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/130389607/55b85c85-09d0-4575-9384-17f0c82e23ba)

The logo on the left upper corner of the sign up page is not visible.

kindly assign it to me I will fix it
Thank you

**Comment by ayushrskiaa** [comment]
@khushi-joshi-05 please assign it to me
Thank you

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
