### ISSUE TITLE
The login link down the REGISTER button is not functional

### ISSUE THREAD

**Issue by ayushrskiaa** [khushi-joshi-05/Food-ordering-website#1099]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/130389607/1e710ed9-08ed-4f09-acc3-5f6f19ae07ca)

The login link does not refer to the login page.

**Comment by ayushrskiaa** [comment]
@khushi-joshi-05  please assign it to me I would like to work on this issue.
Thank you

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
