### ISSUE TITLE
marque

### ISSUE THREAD

**Issue by shuhaki** [khushi-joshi-05/Food-ordering-website#11]
fixing marque

**Comment by suraj-9849** [comment]
I would like to work on this issue under @GSSOC'24 can you please assign me this issue!

**Comment by khushi-joshi-05** [comment]
@shuhaki @suraj-9849 can u please elaborate the issue with marque.

**Comment by shuhaki** [comment]
@khushi-joshi-05 i want working on it. please assign me

**Comment by suraj-9849** [comment]
Yeah let me tell u sir as the marque is coming but its very slow and I will make it look more better by adding the best stylings to it and also we can see there is only one content which is moving which is Get 30% off I can replicate it and keep it on the same marque and make it more better @khushi-joshi-05

**Comment by khushi-joshi-05** [comment]
@suraj-9849 I have assigned you the issue, do the required changes.

**Comment by suraj-9849** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/146669517/f8424b2f-65fb-4946-884b-9db4cc556b4f

is this ok sir before the PR I would like to confirm from you @khushi-joshi-05 sir

**Comment by khushi-joshi-05** [comment]
@suraj-9849 I think if its width will be lesser and smaller font then it will look better .

And just to correct you I am not sir.

**Comment by suraj-9849** [comment]
Hello @khushi-joshi-05  I made the PR Please check it out

**Comment by MUKUL-RAJPUT2004** [comment]
Hello
For more customer attraction this marquee tag must on on the top not at the bottom . 
Please assign it to me in Gssoc 24 . I will solve the issue a my earliest.
Thank you
