### ISSUE TITLE
The Width of the Sign up page is not according to the screen.

### ISSUE THREAD

**Issue by ayushrskiaa** [khushi-joshi-05/Food-ordering-website#1100]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/130389607/60c8b78d-b3b2-45d9-ba02-59854ed22243)

The horizontal scroll bar is coming on the signup page.

**Comment by ayushrskiaa** [comment]
Assign this task to me, @khushi-joshi-05. I want to work on it. Thank you.

**Comment by laxmi09-walker** [comment]
please assigned me this issue!
Thanks.
