### ISSUE TITLE
Their is no logo in the signup page

### ISSUE THREAD

**Issue by shivathmikavemula** [khushi-joshi-05/Food-ordering-website#1109]
Their is no logo in the signup page
### Screenshot:
![Screenshot (28)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/133566953/3848e0ec-5260-4fde-b7ae-f1477acc440d)

**Comment by shivathmikavemula** [comment]
Please assign this issue to me @khushi-joshi-05

**Comment by shivathmikavemula** [comment]
And please add the gssoc labels to it @khushi-joshi-05

**Comment by shivathmikavemula** [comment]
yeah I finished the work @sunny0625

**Comment by shivathmikavemula** [comment]
and you assigned this issue to me @sunny0625

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
