### ISSUE TITLE
Add the restaurants, Improve the design and home page

### ISSUE THREAD

**Issue by somrima-09** [khushi-joshi-05/Food-ordering-website#111]
1. More user friendly 
2. Adding the new features 
3. Making it working.
4. Enable the Order now button.

**Comment by Jyoti9014** [comment]
1. I want to add indian pahadi traditional food .. like Aloo K Gutke, Bhatt ki dal ,Dadim chutney etc...
2. Adding more features like order now page..
3. Our menu page .
4.  Enable add to cart button.

**Comment by aasthakourav20** [comment]
Hey khushi-joshi-05 ,  please assign this issue to me , want to make the website responsive

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
