### ISSUE TITLE
enhance navbar

### ISSUE THREAD

**Issue by sanayamahajan-23** [khushi-joshi-05/Food-ordering-website#1113]
the navbar looks really basic . planning to enhance it and make it stylish

**Comment by anshikatiwari20** [comment]
**Description:**
The current navbar can be enhanced to improve its functionality and user experience.

**Screenshot:**
![Screenshot 2024-06-18 233739](https://github.com/khushi-joshi-05/Food-ordering-website/assets/143124119/b4ad67fb-4e4a-4eff-adfb-07cad5380bb8)

@khushi-joshi-05 I am a GSSoC contributor and would like to work on enhancing the navbar as described in issue #1113. Could you please assign this issue to me and add the GSSoC label? Thank you!

**Comment by RohanDable** [comment]
Yes , Navbar seems very basic lot can be improve in it . Can i work on it ? where is the mentor ? are you guys not serious , why are you taking this much time to reply to contributors ? . Project Admin should look into this matter asap.

**Comment by sanayamahajan-23** [comment]
I dont know why aren't they answering

**Comment by RohanDable** [comment]
Actually i am working on other  stuff , so thought to go  through this repo but it seems all are dead here lol.  sanaya do you know any cool projects to contribute in this year gssoc . if so please do let me know.
