### ISSUE TITLE
footer and nav bar of "Book table " page is not proper

### ISSUE THREAD

**Issue by suhanigupta23** [khushi-joshi-05/Food-ordering-website#1116]
footer and nav bar of "Book table " page is not proper.
<img width="1437" alt="Screenshot 2024-06-18 at 7 53 14 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/d2089bab-29a6-4bce-abcb-ff29d2a9d195">

<img width="1437" alt="Screenshot 2024-06-18 at 7 53 21 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/f305ab8d-d111-4677-961c-11194fa2e4de">

I want to work on this issue under Gssoc'24.

**Comment by suhanigupta23** [comment]
please assign this to me @khushi-joshi-05

**Comment by sunny0625** [comment]
Improve Text in Book Table
