### ISSUE TITLE
Buttons of service page division are not visible.

### ISSUE THREAD

**Issue by suhanigupta23** [khushi-joshi-05/Food-ordering-website#1117]
Buttons of service page division are not visible. The buttons are not visible unless hovered on the division.
<img width="1437" alt="Screenshot 2024-06-18 at 7 58 30 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/ff46c4ed-9ce5-4531-a4b5-fd422e576619">
We can make the divisions a little bigger and images some what smaller also align the images to the centre properly. 

Please assign me this issue under GSSOC'24.

**Comment by suhanigupta23** [comment]
please assign this to me @khushi-joshi-05

**Comment by suhanigupta23** [comment]
please assign this to me @khushi-joshi-05

**Comment by sunny0625** [comment]
This is an effect, not an issue.
