### ISSUE TITLE
UI NOT RESPONSIVE

### ISSUE THREAD

**Issue by milansamuel609** [khushi-joshi-05/Food-ordering-website#113]
I have checked the UI responsiveness. When viewed in mobile device the screen is not full covering and half area of the screen is shown as black. See the image for the reference.
I can easily fix this issue.

![Screenshot 2024-05-11 122855](https://github.com/khushi-joshi-05/Food-ordering-website/assets/75712741/fbc82610-884f-42e5-9dd8-237e727069ae)

**Comment by Mujtabaa07** [comment]
Please Assign Me This Issue , I'll Improve This Site Responsiveness @khushi-joshi-05

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
