### ISSUE TITLE
BUG: NavBar in cart.html

### ISSUE THREAD

**Issue by kdanjana** [khushi-joshi-05/Food-ordering-website#1134]
Cant see the navbar in the cart.html.
<img width="959" alt="fow" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/103878831/95bce7b7-1c15-407a-9acc-dae987f5da61">
please assign this to me.
@sunny0625 @khushi-joshi-05

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
