### ISSUE TITLE
[Bug] : Navbar Not Fully Visible Due to Overlapping Red Background

### ISSUE THREAD

**Issue by HarshadaGirase** [khushi-joshi-05/Food-ordering-website#1142]
###Description :-
The navigation bar (navbar) is not fully visible because the newly implemented red background color overlaps with it. This issue affects the visibility and usability of the navbar, making it difficult for users to navigate the site effectively.

###Steps to Reproduce :-
Open the web browser and navigate to the homepage of the website.
Observe the navbar at the top of the page.
Note that the red background color is overlapping with the navbar, making parts of it obscured.

###Expected Behavior :-
The navbar should be fully visible without any parts being obscured by the background color. The text and elements within the navbar should be clear and easily accessible.

###Actual Behavior:
The navbar is partially covered by the red background color, which makes it difficult to see the text and interact with the navigation elements
![cartpage](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128895955/b8208864-bce0-4966-baf4-5615cce7c07f)

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
