### ISSUE TITLE
there are javascript code snippets that are visible in the footer section in addition to a toggle button which has no function

### ISSUE THREAD

**Issue by samarsajad** [khushi-joshi-05/Food-ordering-website#1148]
there are javascript code snippets that are visible in the footer section in addition to a toggle button which has no function
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/142666229/fe28a301-a187-41f6-a35a-83eeb601708e)

**Comment by samarsajad** [comment]
Please assign this to me @sunny0625 @khushi-joshi-05

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
