### ISSUE TITLE
Unwanted JavaScript Code Rendering in Footer Section of Login Page

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#1157]
There is an unwanted block of JavaScript code appearing in the footer section of the login page. This code is being rendered as text instead of being executed as a script. This issue affects the visual presentation and functionality of the login page.

![Screenshot 2024-06-22 171429](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/d7d20f84-eabc-4071-938f-e47bbafecd21)

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/dfaf0324-7915-4b7a-ba90-6d9ea7f38db3)

@sunny0625 @khushi-joshi-05 please assign this issue to me, under GSSoC'24.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
