### ISSUE TITLE
Header and Footer Sections of Book-Table Page Are Not Properly Styled

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#1158]
The header and footer sections of the book-table page are not properly styled, which affects the overall user experience and visual consistency of the page. This issue needs to be addressed to ensure a professional and cohesive look for the website.

The header section appears misaligned and does not blend well with the overall page layout.
The footer section is not properly styled and is not aligned correctly at the bottom of the page.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/da4f0c65-dec6-4fda-b458-2def67f4b8c2

@khushi-joshi-05 @sunny0625 Please assign this issue to me under GSSoC,24.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
