### ISSUE TITLE
Correcting the Position of Marquee tag for attracting the user on site

### ISSUE THREAD

**Issue by MUKUL-RAJPUT2004** [khushi-joshi-05/Food-ordering-website#116]
![Screenshot (4)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/118878628/5db5c236-f8ff-4ed1-8c66-bcf5c7ba434e)
The marquee tag of "Get 30% OFF on your first order!" should be present on the top as it will attract the users and also they will be more likely to place order .
I can correct this issue , so please assign me this issue.
Looking for a positive response from your side.
Thank you

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
