### ISSUE TITLE
Header and Footer Sections of Cart Page Are Not Properly Styled

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#1161]
The header and footer sections of the Cart page are not properly styled, which affects the overall user experience and visual consistency of the page. This issue needs to be addressed to ensure a professional and cohesive look for the website.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/6b6f2e9a-862d-4815-a97d-89b1639a0915

@khushi-joshi-05 @sunny0625 Please assign this issue to me under  GSSoC'24.

**Comment by sunny0625** [comment]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/a3d97e29-b7c7-4d57-a7a9-753f5f131d86)

@TBorundia 
Work on Footer..!

**Comment by TBorundia** [comment]
> ![image](https://private-user-images.githubusercontent.com/76521579/345769442-a3d97e29-b7c7-4d57-a7a9-753f5f131d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ1NTIsIm5iZiI6MTcyMDA4NDI1MiwicGF0aCI6Ii83NjUyMTU3OS8zNDU3Njk0NDItYTNkOTdlMjktYjdjNy00ZDU3LWE3YTktNzUzZjVmMTMxZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZmZhZjg3Nzg1OWQ3NjZhZGUwZjJmZTQ2MzI3YjJkNWNkZjQ1OWJmZjgyNGRhNDI3NmEwN2YzODVhZTIwMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-43EBuhhk8JmTX9Ra7fH-4JzLk7tuPiaU3FZoICLFTM)
> 
> @TBorundia Work on Footer..!

Ok Sir!
