### ISSUE TITLE
Unnecessary Large Picture of happy Client

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#1162]
A large picture is displayed prominently on the happy Client page, which is not required. 

https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/ffbd4a85-2aac-4c6b-9e19-a9bdd3bdab77

@khushi-joshi-05 @sunny0625 Please assign this issue to me under  GSSoC'24.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
