### ISSUE TITLE
Feature🌟: Add a Dedicated "Feedback Form" Page

### ISSUE THREAD

**Issue by aslams2020** [khushi-joshi-05/Food-ordering-website#1164]
hey @khushi-joshi-05, @sunny0625 

To further enhance user interaction and engagement on the Foodie website, I propose **adding a dedicated feedback form page**. 
This page will provide users with an easy and accessible way to share their thoughts, suggestions, and issues, thereby helping us improve the overall user experience.

### What is the need -

The current website offers a variety of features such as online ordering, table booking, and a comprehensive menu. However, there is no centralized location for users to provide feedback.

I believe this feature will significantly benefit the Foodie website by providing a dedicated channel for user feedback, leading to continuous improvements and enhanced user satisfaction. 

I would like to take up this task. @khushi-joshi-05 / @sunny0625  Could you please assign this issue to me? 
Thank you!

**Comment by Meghana-n10** [comment]
Hey can you please assign this to me under ggsoc level 1

**Comment by aslams2020** [comment]
@sunny0625 Could you please assign me with this issue?
