### ISSUE TITLE
Footer can be improved

### ISSUE THREAD

**Issue by Anshika040** [khushi-joshi-05/Food-ordering-website#117]
Footer can be improved , can be more interactive

**Comment by royalrajputayush** [comment]
I want to work on this issue, please assign me this under gssoc level 2.

**Comment by 1404honey** [comment]
I want to work on this issue Please assign it to me I will surely make the best changes in it

**Comment by abhirup0199** [comment]
Sir, I want to work on this issue. Please assign this issue to me. And please add the tags and labels.

**Comment by Harshit279096** [comment]
we can increase the size of the text and add hover on the social media page.
kindly assign this task to me.
