### ISSUE TITLE
View all menu is not working

### ISSUE THREAD

**Issue by Anshika040** [khushi-joshi-05/Food-ordering-website#118]
Menu list should be shown on clicking view all menu

**Comment by Aishikap** [comment]
i want to work on this issue.

**Comment by singhpratibha98** [comment]
![Screenshot (50)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/129493126/ab768135-b44e-4c70-8d17-21e862f44d09)
  

This is the issue which is coming when user click on menu button . I can fix this issue . Please assign this task to me.

**Comment by singhpratibha98** [comment]
![Screenshot (50)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/129493126/32126bf0-a2db-4557-a356-d6779024d6ee)

This is the issue which is coming when user click on menu button . I can fix this issue . Please assign this task to me.
