### ISSUE TITLE
Adding hover effects and pointer cursor on the footer and the social media links, also adding icons to the play store and app store logos

### ISSUE THREAD

**Issue by kushagrakiyawat** [khushi-joshi-05/Food-ordering-website#12]
Hello PA
Issues I would like to report:
1. add hover effects and cursor pointer on the the footer links and the social media links. Also add the pointer cursor on the buttons. 
2. Adding logos of play store and app store would also give a better UI.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/143614783/483938c8-c2c5-4bb4-a141-d835f76c4960)

**Comment by kushagrakiyawat** [comment]
Kindly assign this issue to me, I know how to do these things. And would like to start contributing to GSSOC'24 with this issue

**Comment by khushi-joshi-05** [comment]
@kushagrakiyawat you have been assigned the issue. All the best!

**Comment by kushagrakiyawat** [comment]
Thank you so much!

**Comment by PayalKumari10** [comment]
@khushi-joshi-05  i want to work on this issues,  can you assign me ?

**Comment by Khushinkm15** [comment]
pls assign me on this issue

**Comment by Harish-2003** [comment]
can you please add the level labels so that we can able to get points in gssoc

**Comment by SalehaTabassum** [comment]
Hi @kushagrakiyawat please assign this issue to me

**Comment by sahithinandikula** [comment]
@khushi-joshi-05 I am willing to work on this task and contribute under GSSOC'24 . I hope my request is considered

**Comment by oddnumbercringe** [comment]
Hey @khushi-joshi-05 , I would like to work on this issue

**Comment by Ketan787898** [comment]
I have a **genuine interest** in this project pls assign this issue to me , I think my work will help your project to be more attractive and responsive !!

**Comment by anupa-rb** [comment]
Hi there, I've been learning UI/UX and I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.
