### ISSUE TITLE
Login menu is needed

### ISSUE THREAD

**Issue by Aishikap** [khushi-joshi-05/Food-ordering-website#120]

**Comment by shraddhalute** [comment]
I am well-prepared to address the need for a login menu feature by taking on the task. I kindly request to be assigned to this issue for its implementation.

**Comment by Monika3002** [comment]
Hello ,

I hope you are doing well. I am eager to contribute to the project and would appreciate it if you could assign me a task or let me know how I can get started. I am looking forward to collaborating with all of you!

Best regards,
Monika

**Comment by Ansh101112** [comment]
@khushi-joshi-05 please assign this issue to me.
