### ISSUE TITLE
[Feature] : `service` page can't work `Dark & Light` mode

### ISSUE THREAD

**Issue by sivaprasath2004** [khushi-joshi-05/Food-ordering-website#1202]
- In this project `Services` page cannot work the `Dark & Light` mode.
### Expected Behaviour

![Screenshot from 2024-06-26 09-03-45](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121082414/cc533b4e-2943-4232-8e27-24eaf20ff169)

### Actual work
 
![Screenshot from 2024-06-26 09-07-34](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121082414/c5d1663f-386a-4ab8-8a52-8afb706691f1)

- please assign me.

**Comment by khushi-joshi-05** [comment]
@sivaprasath2004 u can work on it

**Comment by sivaprasath2004** [comment]
Yes
