### ISSUE TITLE
[FEAT 💡]: Need for a sticky Floating Navbar

### ISSUE THREAD

**Issue by warmachine028** [khushi-joshi-05/Food-ordering-website#121]
- The navigation bar can be made to float which will always stick to the top of the page.
- A floating navbar enables users to navigate while scrolling down the page.
- This feature eliminates the need for users to scroll back up to access the navbar every time they need it.

**Comment by anshig135** [comment]
i want to add this feature to the website, kindly assign me this issue under GSSOC'24

**Comment by warmachine028** [comment]
> i want to add this feature to the website, kindly assign me this issue under GSSOC'24

@anshig135  I have created this issue to work on it. Could you please find other issues to contribute to this project
