### ISSUE TITLE
Email validation in the 'Contact Us' form

### ISSUE THREAD

**Issue by Ajita369** [khushi-joshi-05/Food-ordering-website#1210]
I entered the wrong format email in the email box and it got submitted . It should provide message to user to input valid address .
Screenshots: 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/162597493/e397b4b9-b3cf-403a-89ee-52ac7f88895c)
this is what I entered .
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/162597493/5875ebc1-277e-4e11-bd5d-d916f2324c66)
this is message I received .
I would like to work on this issue please assign me this  under GSSOC'24 .

**Comment by khushi-joshi-05** [comment]
@Ajita369  i have assigned u this issue

**Comment by Ajita369** [comment]
Please add the labels of gssoc and level .
