### ISSUE TITLE
Dark Mode Toggle Button  for better UI

### ISSUE THREAD

**Issue by maverickcodex18** [khushi-joshi-05/Food-ordering-website#122]
mentors @sanjay-kv @khushi-joshi-05 

**Is your feature request related to a problem? Please describe.**
Continous work in light mode is frustrating and increases fatigueness in eyes , adding a feature of dark mode might increase user interaction and satisfaction

**Describe the solution you'd like**
A toggle button for switching between light and dark modes .
Kindly assign me this project under **GSSoC'24**

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/79051168/5ca70386-3c61-4147-a194-fe55fb17120c)

**Comment by safael-alami** [comment]
I'd like to handle the implementation of the dark Mode for this project, given its current high demand. Could you please assign it to me?

**Comment by sunny0625** [comment]
@maverickcodex18 Can you add multiple-color theme feature?

**Comment by maverickcodex18** [comment]
> @maverickcodex18 Can you add multiple-color theme feature?

Can you elaborate, like user can choose a theme and website color changes accordingly?

**Comment by sunny0625** [comment]
> > @maverickcodex18 Can you add multiple-color theme feature?
> 
> Can you elaborate, like user can choose a theme and website color changes accordingly?

Users can get the limited colour option in which the component's colour will change accordingly.
