### ISSUE TITLE
 Enhance User Interface for Better Usability

### ISSUE THREAD

**Issue by Mujtabaa07** [khushi-joshi-05/Food-ordering-website#124]
Transitions ,
Hover Effects ,

These enhancements will make the user interface more engaging and intuitive, leading to a better overall user experience.to 
I Request You To Kindly Assign This Issue To Me, @khushi-joshi-05 , 
Request You To Label This Issue As Well .

**Comment by shrutisachan08** [comment]
I can be working on making the website more efficient by:
simplifying the complex tasks by breaking them down that is minimizing the cognitive load.
A feature of continuous iteration could also be added to it that updates the interface based on user's feedback and data.
Hence , @khushi-joshi-05 I would request u to please assign this issue to me.
