### ISSUE TITLE
Overlapping Navbar in Offers Page

### ISSUE THREAD

**Issue by saurabh-dhakite** [khushi-joshi-05/Food-ordering-website#1243]
The navbar overlaps with the page content in the offers page. 
![Screenshot 2024-07-01 170911](https://github.com/khushi-joshi-05/Food-ordering-website/assets/113512874/84b50723-2f56-46ed-9e36-650b95563365)

**Comment by saurabh-dhakite** [comment]
@sunny0625 Please assign this issue to me under GSSOC '24.

**Comment by khushi-joshi-05** [comment]
@saurabh-dhakite u can work on it.

**Comment by saurabh-dhakite** [comment]
Recent commits to the repo already solve this issue so closing this.
