### ISSUE TITLE
"Order Online " and "Take order" isn't working

### ISSUE THREAD

**Issue by khushi-joshi-05** [khushi-joshi-05/Food-ordering-website#1246]
"Order Online " and "Take order"  icon on home page in the bringing happiness to you section aren't working.
Anyone up to resolve this issue?

**Comment by Ishitva744** [comment]
I can try to resolve the issue. Please assign it to me under GSSoC'24.

**Comment by Pratiksha1661** [comment]
Kindly,Assign me this issue under GSSOC"24

**Comment by khushi-joshi-05** [comment]
@Ishitva744 i have assigned u this issue. go ahead

**Comment by Ishitva744** [comment]
> @Ishitva744 i have assigned u this issue. go ahead

@khushi-joshi-05 I was thinking to add a new webpage for "Order Online" button which will ask users for the address and for "Take order" button redirecting them to the payment page. Is this ok?

**Comment by Ishitva744** [comment]
> @Ishitva744 i have assigned u this issue. go ahead

@khushi-joshi-05 I have created a pull request for this issue #1329
