### ISSUE TITLE
Add Sliding Animations to Images

### ISSUE THREAD

**Issue by MastanSayyad** [khushi-joshi-05/Food-ordering-website#126]
Hi @khushi-joshi-05 
Adding sliding animations can make the website more engaging and visually appealing, especially for sections like menus and customer opinions, services, etc. 

**All Menus**

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/101971980/8f9365a5-a8c6-441b-b817-37764ce2fdb2)

**CUSTOMER OPINION**

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/101971980/92b25d15-463c-4700-97c7-8bd6994a80d0)

I Can Implement sliding animations using CSS and JavaScript for images in sections such as menus, customer opinions, etc.
Could you please assign this project to me under GSSOC 24?

**Comment by Mitali-Pandey** [comment]
I am Mitali Pandey. Under GSSOC'24, @khushi-joshi-05 I would like to work on this issue. Please assign this to me.

**Comment by abhirup0199** [comment]
I am Abhirup, Under GSSOC'24, @khushi-joshi-05 please assign this issue to me. I want to work on this issue.

**Comment by vaishnavip27** [comment]
I would love to work on this issue as I have build a lot of sliding carousels. Please assign me this issue. Looking forward for the approval

**Comment by khushi-joshi-05** [comment]
@MastanSayyad I have assigaed you the issue. Go ahead . All the best.

**Comment by MastanSayyad** [comment]
Thank you for assigning it to me @khushi-joshi-05 . Will start working on it immediately.

**Comment by dakshika-chaudhary** [comment]
I am dakshika-chaudhary. I was seeking for the similar issue, @khushi-joshi-05 please assign it to me.

**Comment by abhirup0199** [comment]
@khushi-joshi-05 I also want to work on this issue. So please assign me to work on this issue too.

**Comment by rashmitha155** [comment]
Hello! @khushi-joshi-05, That’s a great idea! Sliding animations can indeed make a website more engaging and visually appealing.
To create a sliding animation, we can use CSS animations or Bootstrap Carousel-which builts with CSS 3D transforms and a bit of javascript.
I already developed these kinds of animations on my projects.

i request you to assign me to work on this issue under GSSoc'24.

**Comment by sunny0625** [comment]
Is anyone still up for this issue?

**Comment by n14rishitha** [comment]
> Is anyone still up for this issue?

Yes , I would like to work on this issue .  I can solve this issue . so could you please assign this task to me .
