### ISSUE TITLE
Text and images are flowing out of cards in services page in mobile view.

### ISSUE THREAD

**Issue by meetarora10** [khushi-joshi-05/Food-ordering-website#1263]
The text and images are flowing out of the box in the services page for mobile view.
Assign this task to me under GSSOC'24 and I will fix this issue.
![Screenshot (603)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/143121854/a2080fdb-18d3-404c-99f9-0e3b601f82de)

**Comment by meetarora10** [comment]
@sunny0625 please assign me this issue.

**Comment by khushi-joshi-05** [comment]
@meetarora10 i have assigned u this issue.

**Comment by meetarora10** [comment]
@khushi-joshi-05 thanku I will work on it.

**Comment by meetarora10** [comment]
@khushi-joshi-05 fixed this issue please review.
