### ISSUE TITLE
Adding an option for Veg and Non-veg in the initial 

### ISSUE THREAD

**Issue by debiprasannadash** [khushi-joshi-05/Food-ordering-website#128]
Adding an option for the veg and non-veg items would be good for the website. So that the users can explore the range in the domains.

**Comment by kvdevlopment** [comment]
"Hello Team!
 I've come across the request to add an option for Veg and Non-veg in the initial setup (#128). This addition will provide users with greater clarity and convenience right from the start, ensuring a smoother experience while navigating the website. I'd be happy to work on implementing this feature and ensuring its seamless integration into the initial setup process. Could you please assign this task to me? I'm eager to contribute and enhance the user experience. Thank you!"

**Comment by ankiiitagupta** [comment]
Can you assign this issue to me under GSSOC'24 please? I would love to use my skills to provide you with desired and enhanced result.
