### ISSUE TITLE
"order now" button and "apply now" button not working

### ISSUE THREAD

**Issue by nandani-goyal** [khushi-joshi-05/Food-ordering-website#1288]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/152094228/2617f392-2d01-4d38-838b-bc08fdbd08df)
in the cart page the "order now" and "apply" button are not working. Please assign me this issue under gssoc'24

**Comment by khushi-joshi-05** [comment]
@nandani-goyal i have assigned u this issue. go ahead
