### ISSUE TITLE
Cursor doesn't change when hovering over View All Menu

### ISSUE THREAD

**Issue by iDhruv03** [khushi-joshi-05/Food-ordering-website#129]
When the user hovers over it, the cursor should transform into a hand, indicating that it's clickable like a button. This helps users recognize its interactive nature and encourages them to click on it.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/146013529/0b25b007-3356-4466-b24b-6c87851e8cfd

**Comment by iDhruv03** [comment]
Please assign this issue to me under GSSoC
I can work on this

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue under GSSOC'24 so that I can provide my insights and solutions.

**Comment by Harshit279096** [comment]
we can change an one finger icon while hovering also increases the size of "view all menu" text while hovering.
kindly assign this task to me.
