### ISSUE TITLE
Bug : The faq link in services section is not redirecting to the faq section.

### ISSUE THREAD

**Issue by shraddhha** [khushi-joshi-05/Food-ordering-website#1293]
![faqlink](https://github.com/khushi-joshi-05/Food-ordering-website/assets/125660723/d81c1468-f3c3-4fd2-97db-87fa96b57cf8)
The FAQ link in the services section of the website is currently not redirecting users to the FAQ section. This issue can significantly impact user experience and accessibility, as visitors may find it challenging to locate essential information quickly.

**Reasons to Solve this Bug:**

-  Enhanced User Experience:

Users expect links to work correctly and take them to the specified section of the website. A non-functioning link can lead to frustration and a poor user experience.

-  Accessibility:

Ensuring that links work correctly is a critical aspect of web accessibility. Users, especially those who may rely on assistive technologies, need functional navigation to access all parts of the website.

- Trust and Credibility:

A website with broken links can appear unprofessional and may diminish users' trust in the site’s reliability and credibility.

**Comment by shraddhha** [comment]
Hello @khushi-joshi-05 and @sunny0625 
Please assign me this issue under GSSOC'24.
Thank You!

**Comment by khushi-joshi-05** [comment]
@shraddhha i have assigned u this issue.
