### ISSUE TITLE
Adding Hover effects to buttons, fixing menu button and improving navigation bar

### ISSUE THREAD

**Issue by pulkitgarg04** [khushi-joshi-05/Food-ordering-website#13]
Adding the Google Play Store logo and Apple App Store logo instead of buttons, making a cursor pointer hover effect on nav links, and adding website's name in the navigation bar. 
I would like to work on this issue under GSSOC'24 can you please assign me this issue!

**Comment by suraj-9849** [comment]
I would like to work on this issue under @GSSOC'24 can you please assign me this issue!

**Comment by kamalesh-og** [comment]
Hi,
I'm one of the contributors for the GSOCC'24, I would love to take up this issue and work on this UI.
I have experience in Web Design and I can assure you that I make this UI more attractive and good-looking with proper formatting fonts and design of the page.
Can you please assign this issue to me
Thank you!

**Comment by khushi-joshi-05** [comment]
@pulkitgarg04 I have assigned you the issue. Kindly make the suggested improvements for google play store and app store.

**Comment by asinha828** [comment]
hello, i am a contributor in gssoc'24, i would like to work on my first contribution to this issues.

**Comment by 1911aditi** [comment]
hii, i m a contributor in gssoc' 24 .I would definitely like to work on my first contribution on this issue.
we can solve this issue by using hover function in CSS it will provide hover effects to the button. Also i have knowledge about design so i will try to work on the beautification of nav bar

**Comment by sunny0625** [comment]
Do create only one issue for only one change of the website. Others also get the opportunity to Contribute.
