### ISSUE TITLE
Improving the website

### ISSUE THREAD

**Issue by chaanakyaaM** [khushi-joshi-05/Food-ordering-website#130]
Things I would like to fix:

- [X] Improve the font of the header , including hover effect
- [X] Improve footer including the hover effect
- [X] Change the name of the website as per your requirements
- [X] Make home page more user friendly and responsive
- [X] Make landing page symmetric

would you assign me to this issue under GSSOC'24 ??

**Comment by Prachiii8287** [comment]
I would like add illustrations in this website which will make this more user friendly.Please assign me this work
