### ISSUE TITLE
Changing button and input to a better design and color pattern styling the food cards with animation and hover

### ISSUE THREAD

**Issue by cxde-Sujal** [khushi-joshi-05/Food-ordering-website#131]
Will make the buttons more user intuitive through patterns and different in its active state and use of hover.
Change the cards animation on hover it will rotate and card will show the food items under that card
Will also change Contact page and make it more better 
@khushi-joshi-05 @sanjay-kv

**Comment by cxde-Sujal** [comment]
Please assign it to me for GSSoc'24 will surely complete and make it a successful completion

**Comment by SahilThakur02** [comment]
@cxde-Sujal , I would also like to work on this issue with you please. 
Please /assign the issue.
