### ISSUE TITLE
[BUG]: Adjust Background Image to Fill Entire Screen on Landing Page

### ISSUE THREAD

**Issue by anurag-jaiswal-aj** [khushi-joshi-05/Food-ordering-website#132]
Currently, the landing page of the foodie website displays a background image that does not cover the entire screen, resulting in a visual inconsistency. This issue aims to improve the aesthetics and user experience by adjusting the background image to fill the complete screen. By ensuring the background image covers the entire viewport, we aim to create a more visually appealing and cohesive landing page.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144160916/8874c182-83b0-4b1e-91b7-6f848beecb27)

Kindly assign this task to me, and I'll proceed with implementing the necessary changes. Thank you for the opportunity to contribute!

**Comment by anurag-jaiswal-aj** [comment]
Kindly assign this task to me, and I'll proceed with implementing the necessary changes. Thank you for the opportunity to contribute!

**Comment by Harshit279096** [comment]
i can add a background image and we can do one thing also , to add image inside a  text that will give an attractive look. 
kindly assign this task to me.

**Comment by khushi-joshi-05** [comment]
@anurag-jaiswal-aj I have assigned you the issue. Go ahead . All the best.

**Comment by anurag-jaiswal-aj** [comment]
I wanted to provide an update regarding the issue reported in this thread. The necessary changes have been implemented in pull request #223 to address the issue.  
Could you please review and merge at your earliest convenience?
