### ISSUE TITLE
[FEAT]: Implement Hover Effect for Text in Footer Section

### ISSUE THREAD

**Issue by anurag-jaiswal-aj** [khushi-joshi-05/Food-ordering-website#133]
The footer section of the foodie website lacks a hover effect on its text elements, diminishing user interactivity and visual feedback. This issue aims to enhance user experience by implementing a hover effect on the text within the footer section. By adding hover effects, such as color changes or underlines, we can improve the user's perception of interactivity and engagement. 

https://github.com/khushi-joshi-05/Food-ordering-website/assets/144160916/07d4163f-1610-4c36-8758-6ec8548ae508

Kindly assign this task to me, and I'll work on implementing the necessary hover effects for the footer text. Thank you for considering my contribution!

**Comment by anurag-jaiswal-aj** [comment]
Kindly assign this task to me, and I'll work on implementing the necessary hover effects for the footer text. Thank you for considering my contribution!

**Comment by Harshit279096** [comment]
i can add  hover effect and some attractive style also if you assign this task to me.

**Comment by ankiiitagupta** [comment]
@khushi-joshi-05 Can you assign this issue to me under GSSOC'24 please? I would love to use my skills to provide you with desired and enhanced result.

**Comment by Prachiii8287** [comment]
@khushi-joshi-05 Could you assign this work to me. I have already solve these types of issues.So,I can solve this easily.
