### ISSUE TITLE
Navbar links not working

### ISSUE THREAD

**Issue by SatyajeetGhosh** [khushi-joshi-05/Food-ordering-website#134]
The links in the navbar are broken. They don't route to the intended page. I have provided the screenshot of what happens when someone tries to click these links. 

I can fix this issue. Please assign me this issue to me @khushi-joshi-05 under GSSoC'24

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/103898124/2479e616-981d-4169-adf3-3c285ec9424c)

**Comment by shrutibharat-05** [comment]
I can fix

**Comment by SardulR** [comment]
Hey! @khushi-joshi-05 I would like to work on this issue kindly assign me under gssoc 2024.

**Comment by khushi-joshi-05** [comment]
@SatyajeetGhosh i have assigned this issue to you. Can u also link the menu and other files under html-files to the content.css file in css-files. All the best.

**Comment by SatyajeetGhosh** [comment]
@khushi-joshi-05 I have fixed the issue and also linked the other files under html-files to the content.css file in css-files as you asked. I have raised a pull-request (#171) which doesn't have any merge conflicts, please review and merge it. 

Thank you for giving me the opportunity to contribute to this project.
