### ISSUE TITLE
[Style] Improving the overall UI of the website 

### ISSUE THREAD

**Issue by AnandK-pm** [khushi-joshi-05/Food-ordering-website#135]
We need to improve the overall UI as currently , the website seems to be using the primitive CSS styling.
I intend to improve the overall UI of the website so that it becomes a little more tidy and exquisite ensuring a customer friendly experience.
Please assign me this issue as i have experience building websites with HTML and CSS . I'am confident that i can resolve this issue.
( Requesting as a part of GSSoC '24 )

**Comment by vaishnavip27** [comment]
I would love top contribute to this as a designer and developer. Please assign me this issue. Looking forward for the approval
