### ISSUE TITLE
Feature: Improve services section

### ISSUE THREAD

**Issue by sau-mili** [khushi-joshi-05/Food-ordering-website#1357]
![image](https://github.com/user-attachments/assets/a8dd6f4e-84d4-4a0c-aca4-e00530df4cef)
This section can be improved with icons, effects and better UI

please assign me under GSSOC'24

**Comment by sau-mili** [comment]
@sunny0625 please assign me this

**Comment by Rishabh5002** [comment]
@sau-mili 
I want to work on this issue.

**Comment by Rishabh5002** [comment]
please assign me to this issue.
