### ISSUE TITLE
FIX : To update the twitter logo in the footer.

### ISSUE THREAD

**Issue by Akkash20** [khushi-joshi-05/Food-ordering-website#136]
To **change** the twitter logo from the existing **twitter bird** logo to the new **X logo.**

![Screenshot_20240511_193129](https://github.com/khushi-joshi-05/Food-ordering-website/assets/111886713/0342a097-db0d-418a-891d-860edc969308)

**Comment by Akkash20** [comment]
Hey! @khushi-joshi-05 I would like to work on this issue kindly assign me.

**Comment by SardulR** [comment]
Hey! @khushi-joshi-05  I would like to work on this issue kindly assign me under gssoc 2024.

**Comment by kvdevlopment** [comment]
"Hi team! I've noticed the issue regarding updating the Twitter logo in the footer (#136). It's important to keep branding consistent and up-to-date, so I'm happy to take on this fix. I'll ensure the new logo is integrated seamlessly into the footer, maintaining the aesthetic appeal of the website. Could you please assign this task to me? I'm ready to make the necessary updates and ensure a polished look for our platform. Thanks!"

**Comment by Harshit279096** [comment]
"Hi I've noticed the issue regarding updating the Twitter logo in the footer .  I'll ensure the new logo is integrated seamlessly into the footer, maintaining the aesthetic appeal of the website. Could you please assign this task to me? I'm ready to make the necessary updates and ensure a polished look for our platform. Thanks!"

**Comment by sunny0625** [comment]
@Akkash20 are you still up for the issue..!
