### ISSUE TITLE
Font and color is not according to principles of UI/UX.

### ISSUE THREAD

**Issue by shnwz-solves** [khushi-joshi-05/Food-ordering-website#137]
The font of the website is not modern and according to 2024, also the color selection is not appropriate.
Please assign this to me, I would like to contribute to it. Thankyou!
![Uploading Screenshot 2024-05-11 202637.png…]()

**Comment by ankiiitagupta** [comment]
@khushi-joshi-05 Can you assign this issue to me under GSSOC'24 please? I would love to use my skills to provide you with desired and enhanced result.
