### ISSUE TITLE
`View All Menu Button` is not working in the home page !

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [khushi-joshi-05/Food-ordering-website#138]
Hello PA,
There is a wrong entered in the `View all menu button`

### Screenshot -
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121503426/0733e0b8-e34d-4a1f-afb1-639e35bd55ed)

Can you please assign me this issue, I want to fix this.

**Comment by SardulR** [comment]
Hi @khushi-joshi-05 can u pls assign me this issue.
