### ISSUE TITLE
Navbar Links are not correct

### ISSUE THREAD

**Issue by shnwz-solves** [khushi-joshi-05/Food-ordering-website#139]
The links in the navbar menu is not correct and it is redirecting to 404 page.
Please assign this to me I would like to contribute to it under GSSOC 2024. Thankyou.
![Screenshot 2024-05-11 202855](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126380641/a5d9cc7a-0cb4-45f9-8e22-cb67080dab93)

**Comment by harikasayani** [comment]
Hi, 
I am GSSOC'24 Contributor. Could you please assign this issue to me. I have good knowledge in HTML, CSS and JavaScript. I think I can handle it.

**Comment by shrashti2004** [comment]
I am GSSOC'24 Contributor. Could you please assign this issue to me. I have good knowledge in HTML, CSS and JavaScript. I think I can handle

**Comment by ksy2912** [comment]
Hi,
I am GSSOC'24 Contributor. Could you please assign this issue to me. I have good knowledge in HTML, CSS and JavaScript. I think I can handle it.
