### ISSUE TITLE
Improving the visual appeal of "Contact us " form, add carousel effect to menu items and add responsiveness.

### ISSUE THREAD

**Issue by Devaki01** [khushi-joshi-05/Food-ordering-website#14]
hello, 
This is Devaki. I am GGSoC'24 contributor. 
I would like to contribute by making the following changes:
1. Improving contact us form by validations and making is visually appealing to users/clients .
2. Add carousel effect to the menu items listed.
3. Add card hover effect to menu items to make it more user-friendly.
4. Add responsiveness to make it fit for all screen sizes.

Please assign me the issue.

**Comment by Damini2004** [comment]
I can resolve this issue.Please assign me this issue.

**Comment by khushi-joshi-05** [comment]
@Devaki01 I have assigned you the issue.  Would really like u to work on contact section.

**Comment by khushi-joshi-05** [comment]
@Damini2004 I have assigned you the issue. Would really like u to work on point 3,5 and 6 as per your suggested changes.

**Comment by Damini2004** [comment]
> @Damini2004 I have assigned you the issue. Would really like u to work on point 3,5 and 6 as per your suggested changes.

Sure i will contribute my all efforts try to match the enlisted advancement

**Comment by Devaki01** [comment]
> @Devaki01 I have assigned you the issue. Would really like u to work on contact section.

Thank you for the opportunity. Will try my best to complete assigned enhancements.

**Comment by Damini2004** [comment]
@khushi-joshi-05 Can we add Bootstrap it will help in faster execution of listed point of contact section in less amount of time.

**Comment by Devaki01** [comment]
> @khushi-joshi-05 Can we add or use Bootstrap concept it will help in faster execution of listed point of contact section in less amount of time.

Yes..that is actually a good idea. Can we go ahead with it ?

**Comment by asinha828** [comment]
hello maam, can you assign me this work. Also in the website the adjustment has to be made as there is little change. 
![Screenshot 2024-05-11 115608](https://github.com/khushi-joshi-05/Food-ordering-website/assets/38392413/d7bfd6ab-a053-456a-95f8-f68be75cc8eb)
as the image is coming out of the box.
