### ISSUE TITLE
Implementing Add to Cart functionality

### ISSUE THREAD

**Issue by A-b-i-r-a-m-i-G-S** [khushi-joshi-05/Food-ordering-website#142]
@khushi-joshi-05 I would like to work on the following tasks as part of GSSOC'24.
- Implement cart.html (which is currently empty) to display menu items that are added to the cart
- Ensure that when the "Order Now" button is pressed on the menu item card, the item gets added to the cart.
- Include remove from cart option in the cart page
- Display bill total
- Place order button

**Comment by khushi-joshi-05** [comment]
@A-b-i-r-a-m-i-G-S I have assigned you the issue. Go ahead . All the best.
