### ISSUE TITLE
Add  a scrolling marqee animation effect for this section 

### ISSUE THREAD

**Issue by GayathriPCh** [khushi-joshi-05/Food-ordering-website#144]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/132088009/bdd53d23-96b6-455a-bd6e-2a8c784ea084)
images could rather scroll on their own horizontally, like in netflix website. 
I would like to add such type of animation for this section, so could you please assign this task to me? Also could you assign a level under GSSOC'24? 
Thank you for considering!

**Comment by kvdevlopment** [comment]
"Hello team! I've noticed the request to add a scrolling marquee animation effect for this section (#144). This enhancement will add a dynamic and eye-catching element to the section, enhancing its visual appeal and user engagement. I'd love to work on implementing this feature to elevate the overall design of the website. Could you please assign this task to me? I'm excited to contribute and bring this creative idea to life. Thank you!"
