### ISSUE TITLE
Hover effects for the site

### ISSUE THREAD

**Issue by kairveeehh** [khushi-joshi-05/Food-ordering-website#15]
the site lacks hover effects and the effects on card which can show more features to it , I would like to contribute to this issue and improve the overall visual appeal of the site , **please assign me this issue .**
I have proficiency in css and creating useful and creative effects.

**Comment by kamalesh-og** [comment]
Thank you @khushi-joshi-05

**Comment by kairveeehh** [comment]
you are welcome :)

**Comment by sahithinandikula** [comment]
Hello @khushi-joshi-05 I had after the issue that has been mentioned and I can add hover effects to the web page .I hope my request would be considered

**Comment by shrutibharat-05** [comment]
Helllo I beleive I have good enough knowledge of UI in html css. Please do assign me this issue. I am contributor in 2024 GSSOC.

**Comment by SuhainaFathimaM** [comment]
@khushi-joshi-05 Please assign me this task and please label all the issues

**Comment by vaishnavip27** [comment]
Hey as a designer and developer, I would like to work on this issue. Please assign me this issue. Looking forward for the approval

**Comment by Jatinchouhan** [comment]
i would like to work on this issue please assign it to me .

**Comment by Nih1tGupta** [comment]
i would like to work on this issue ,Please assign me too @khushi-joshi-05
