### ISSUE TITLE
Create "Contact Us" Page #GSSOC24

### ISSUE THREAD

**Issue by SamarupBhattacharya** [khushi-joshi-05/Food-ordering-website#150]
Hi,
I noticed that the file for the **Contact Page** is blank. **I would like to add a Contact Us page to your website**. I would like it a lot if you add the labels of **"gssoc"** and **"level2"** to this issue. Also, **pls assign this to me for GSSOC 24**.

Eagerly awaiting your response

**Comment by iim-amit** [comment]
hello,
I am GSSOC'24 Contributor. Could you please assign this task to me. I will add an attractive Contact Us page to your website.
![contact_us](https://github.com/khushi-joshi-05/Food-ordering-website/assets/153279290/f060044e-22f5-44f0-869c-5426f1db02c9)

**Comment by khushi-joshi-05** [comment]
@SamarupBhattacharya I have assigned u the issue. It will be great if u will use similar colour combinations as of other pages. All the best.

**Comment by SamarupBhattacharya** [comment]
Yes, definitely. I will get to it right away. Thank you so much for assigning this issue to me🙏🙏
