### ISSUE TITLE
Creating new pages of login and signup for your webpage

### ISSUE THREAD

**Issue by NamanJain795** [khushi-joshi-05/Food-ordering-website#152]
Hey, I am Naman Jain 
Contributor at Gssoc 24 
i think that your web page should contain a login and signup page so that information of the customer should be there so that order tracking should take place precisely. 
so i would request you to assign me this task for making login and signup page for your web page
Also please tag this issue with gssoc level 2 
waiting for your response
Thank U

**Comment by HimangshuRanjan** [comment]
i would like to fix this issue

**Comment by iim-amit** [comment]
hi, I am Amit kumar
GSSOC'24 Contributor.
 Could you please assign this task to me. 
i would like to create a responsive and attractive log-in and sign-up page for your webpage.

**Comment by vaishnavip27** [comment]
Hey @NamanJain795 I would love to build a login and sign-up page for your website as a designer and developer. Please assign me this issue. Looking forward for the approval

**Comment by khushi-joshi-05** [comment]
@NamanJain795 I have assigned u the task. Can you also add google authentication to it?

**Comment by NamanJain795** [comment]
thank u so much @khushi-joshi-05 and i have never added google authentication but i will try my best to do it

**Comment by NamanJain795** [comment]
@vaishnavip27 i am not the project admin. you have to ask to the admin for assigning the task to u.

**Comment by vandana79039** [comment]
I would like to work on this issue. Please assign this task to me.

**Comment by vandana79039** [comment]
hi, I am vandana kumari GSSOC'24 Contributor.
Could you please assign this task to me.
i would like to create a responsive and attractive log-in and sign-up page for your webpage.

**Comment by vaishnavip27** [comment]
Hey @khushi-joshi-05 I would love to work on the login and signup page for this website. And I can add google authentication also. Let me know. Looking forward for the approval
