### ISSUE TITLE
Please add level labels

### ISSUE THREAD

**Issue by Anjaliavv51** [khushi-joshi-05/Food-ordering-website#1538]
@sunny0625

Please add Level label to below PR'S

#1489

#1486

And also Please review the below PR'S tooo

#1487

#1488

**Comment by Anjaliavv51** [comment]
@sunny0625

Please add Level label to below PR'S

#1489

#1486

And also Please review the below PR'S tooo

#1487

#1488

**Comment by sunny0625** [comment]
Stop Spamming, You will be disqualified from this program.
@Anjaliavv51

**Comment by Anjaliavv51** [comment]
@sunny0625 please ask @khushi-joshi-05 u check mails , PR is merged but level label is not attached, i am mentioning u PPL every day and updating the comment daily , as u r not responding , I have created an issue like this

**Comment by Anjaliavv51** [comment]
![Screenshot_20240802_144258_Gmail.jpg](https://github.com/user-attachments/assets/76558d15-688e-4a4d-affc-5437f8c7125a)

**Comment by Anjaliavv51** [comment]
![Screenshot_20240802_145824_GitHub.jpg](https://github.com/user-attachments/assets/12c3cc0b-e3b4-46d2-955b-45e4ffa4e69b)

![Screenshot_20240802_145831_GitHub.jpg](https://github.com/user-attachments/assets/1cbb5036-c0ee-4760-872e-4d4c48d906bd)

These are my two PR'S yesterday @khushi-joshi-05 added the level label , PR'S are merged some days before.

**Comment by Anjaliavv51** [comment]
@sunny0625
