### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by meetarora10** [khushi-joshi-05/Food-ordering-website#154]
I can work on this website to make it responsive and more attractive by adding more css and animations.Please this issue to me.

**Comment by meetarora10** [comment]
I will work on it. Thank you

**Comment by Ayushhurkat22** [comment]
I can also make the website responsive for various screen sizes. Please assign it to me. I am a contributor in GSSOC 24.

**Comment by harshitpnd12** [comment]
Please assign me this task
