### ISSUE TITLE
View Menu Button not working

### ISSUE THREAD

**Issue by bhumika-1127** [khushi-joshi-05/Food-ordering-website#159]
The View Menu button on your index.html has some bug which is hindering its functionality on your website.
@khushi-joshi-05 I would like to help under GSSOC'24. Kindly add labels.
![Screenshot 2024-05-12 033316](https://github.com/khushi-joshi-05/Food-ordering-website/assets/137604220/33b53670-406f-460b-bac7-243300b4d110)

**Comment by SardulR** [comment]
HI @khushi-joshi-05 can u pls assign me this task under gssoc 2024
