### ISSUE TITLE
Create the menu page for  the site 

### ISSUE THREAD

**Issue by kairveeehh** [khushi-joshi-05/Food-ordering-website#16]
as of now the menu directs to a 404 page , I would like to create an appealing menu page for the site  using my techstack of html css and javascript according to the project.

please assign me this issue.

**Comment by kairveeehh** [comment]
@khushi-joshi-05 I have created the PR but they are counting after 7 only 
## please ensure to merge after 7 
Thankyou

**Comment by jinalraghwani18** [comment]
I would like to work on this issue and using my knowledge in UI/UX, HTML,CSS, I can create a good menu page .

please assign this to me.

**Comment by kairveeehh** [comment]
> I would like to work on this issue and using my knowledge in UI/UX, HTML,CSS, I can create a good menu page .
> 
> please assign this to me.

@jinalraghwani18  if you read the above comments it was already assigned to me  :) would suggest you to comment over unassigned issues

**Comment by Divya-1612-reddy** [comment]
please assign me this issue

**Comment by kairveeehh** [comment]
> please assign me this issue
It's already assigned and a PR is also created to be merged so I would suggest you to raise smt else needed
