### ISSUE TITLE
To deploy the app on vercel for easy viewing and increased reach

### ISSUE THREAD

**Issue by Debarunn1806** [khushi-joshi-05/Food-ordering-website#161]
Live link to the website would ensure increased reach and throught vercel it can be insured that any changes made to the code on github will be reflected on the live wesite also.

**Comment by Debarunn1806** [comment]
Hello @khushi-joshi-05 I am Debarun Chakrabortty and would like to contribute in this project under GSSOC'24 Kindly assign it to me.

**Comment by Aksshay88** [comment]
@khushi-joshi-05 I have a live link to this website which I have been deployed it in vercel , I will share the website link to this one ,
[Food-ordereding-website](https://food-ordering-website-lemon.vercel.app/)


You could add this one in the github

**Comment by Yashc885** [comment]
i would like to resolve this issue
