### ISSUE TITLE
home page cards and contact inputs 

### ISSUE THREAD

**Issue by NitinChakrawarti** [khushi-joshi-05/Food-ordering-website#162]
In home page of website cards are not visible completely, and also input fields in footer are not looking good and in footer section is not responsive 

@sunny0625  please assign this issue to me under GSSoC'24 

![Screenshot 2024-05-12 091901](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149225785/368983a6-20c9-49d8-ac76-d0a5f382f50f)
![Screenshot 2024-05-12 091913](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149225785/6bc95d1e-cff3-4d81-868d-944c68f6e9e6)
![Screenshot 2024-05-12 091926](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149225785/fd9aee7b-4667-40c1-809d-7fdc5b7aef71)

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
