### ISSUE TITLE
Improve Navbar UI 

### ISSUE THREAD

**Issue by lokeshazad10** [khushi-joshi-05/Food-ordering-website#1628]
**Navbar UI Improvment 🔥**

Foodie website's navbar UI is not very well

**Video :-**

https://github.com/user-attachments/assets/be9c254e-8b49-4ee7-b237-182af4ebf48f

As you can see in this video, the navbar links are not adjusted properly, the theme toggle images are also not adjusted properly, its size is quite large which is affecting the UI.
**And I want to fix it and I can fix it**

so please @sunny0625 assign me this issue, so i can start.

**Comment by khushi-joshi-05** [comment]
@lokeshazad10 u can start working on it
