### ISSUE TITLE
Enhance the menu section of the website.

### ISSUE THREAD

**Issue by sinhaudita** [khushi-joshi-05/Food-ordering-website#165]
The menu section of the website that displays some of the food items type can be enhanced with a better UI design. I can make the UI better using some unique designs. So kindly assign this task to me under GSSoC'24.

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by sunny0625** [comment]
@sinhaudita Describe how would you like to contribute.

**Comment by sinhaudita** [comment]
> @sinhaudita Describe how would you like to contribute.

Implementing sliding card view  can enhance the UI of menu section. I would like to work on this.
