### ISSUE TITLE
Updating Navbar 

### ISSUE THREAD

**Issue by shailifadadu** [khushi-joshi-05/Food-ordering-website#17]
Navbar needs to be responsive. @khushi-joshi-05 can u plz assign this issue to me!!

**Comment by nish1502** [comment]
@khushi-joshi-05 can you pls assign this issue to me

**Comment by Harsh-Vardhan-Yadav-03** [comment]
Please assign this issue to me . I can handle this issue.

**Comment by khushi-joshi-05** [comment]
@shailifadadu you have been assigned the issue.

**Comment by atharvakej** [comment]
@khushi-joshi-05  I've updated and raised PR in clone URL in readme. please review the change if you find useful.

**Comment by shailifadadu** [comment]
> @shailifadadu you have been assigned the issue.

Okay!! Working on it..

**Comment by litesh1123** [comment]
can u please assign me this issue .  i have couple of ideas regarding beautifying navbar

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by tomartanu** [comment]
I would like to work on this issue, Please assign this issue to me.

**Comment by sahithinandikula** [comment]
@shailifadadu I can handle the issue and interested in working on it. I Hope my request will be considered

**Comment by Divya-1612-reddy** [comment]
please assign me this issue

**Comment by anshikatiwari20** [comment]
Could you please assign this issue to me? I will try to resolve it as soon as possible.

**Comment by sunny0625** [comment]
Is any one still up for this issue?
