### ISSUE TITLE
nav bar problem

### ISSUE THREAD

**Issue by souravupreti005** [khushi-joshi-05/Food-ordering-website#170]
Subject: Request for Technical Support: Fixing Navigation Behavior on Website

Dear khushi-joshi-05,

I hope this message finds you well. I am reaching out regarding an issue that has been identified on our website's navigation system. Currently, when users access the "Menu" tab or the "Service" tab, it opens in a new tab, which disrupts the seamless browsing experience. Our objective is to ensure that these tabs open within the same browser window to maintain continuity for our visitors.

Upon selecting an item from the menu or service list, users are then redirected to the home page, instead of opening a new tab. This behavior is not aligned with our desired user experience and warrants immediate attention.

Could you kindly assign this task to the appropriate team or individual for resolution? We aim to provide a professional and user-friendly browsing experience on our website, and resolving this issue promptly is essential to achieving that goal.

Thank you for your attention to this matter. Should you require any further clarification or information, please do not hesitate to reach out.

Best Regards,
sourav upreti

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by khushi-joshi-05** [comment]
@souravupreti005 I have assigned u the issue. Go ahead. All the best!
Looking for best reults.

**Comment by Yashc885** [comment]
please assign me too
