### ISSUE TITLE
copyright_BUG

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#174]
Bug in copyright , Currently the copyright is static it is displaying website created year , Not the current year which will be done by using javascript @khushi-joshi-05 mam assign this issue to me I will fix this bug . Thankyou

**Comment by Meetjain1** [comment]
i am working under gssoc24

**Comment by sunny0625** [comment]
@Meetjain1 want to Contribute to GSSoC'24?

**Comment by Meetjain1** [comment]
> @Meetjain1 want to Contribute to GSSoC'24?

@sunny0625 yes , I am working under gssoc24

**Comment by sunny0625** [comment]
@Meetjain1 go ahead and make a valuable contribution toward GSSoC.

**Comment by Meetjain1** [comment]
> @Meetjain1 go ahead and make a valuable contribution toward GSSoC.

Sure @sunny0625
