### ISSUE TITLE
Missing social media links

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#175]
Social media links are not there in current website also hover effect is missing @khushi-joshi-05 mam Please assign this issue to me I will fix it . Thankyou

**Comment by Meetjain1** [comment]
i am working under gssoc24

**Comment by Srujitha-Raghava** [comment]
Hover and links are missing.assign me this so that i can work on and fix it @khushi-joshi-05 also please add gssoc label
