### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#177]
Favicon is missing in current website , @khushi-joshi-05 please assign this issue to me I will add it . Thankyou , i am working under gssoc24

**Comment by Khushinkm15** [comment]
i would like to wrok on this issue pl assign it to me

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
