### ISSUE TITLE
Image boxes

### ISSUE THREAD

**Issue by tokosaniya09** [khushi-joshi-05/Food-ordering-website#179]
![box](https://github.com/khushi-joshi-05/Food-ordering-website/assets/142909744/002e9748-93ca-4095-a736-56e20f70d622)
![Screenshot 2024-05-12 114621](https://github.com/khushi-joshi-05/Food-ordering-website/assets/142909744/d71c6e10-82fb-467c-a804-76bad1f87f32)
I found some issues in the boxes shown in the picture
1 . The background colour where boxes are placed can be something more eye-catching.
2 . The middle box has different size than the others.
3 . The third box has different font alignment than others

I'd like to enhance the design of these boxes. We can achieve this by adding hover effects and some visual improvements.
So assign me this task.

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
