### ISSUE TITLE
Navbarfixing_BUG

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#180]
Navbar is not fixed in the current website which is not good for our website , @khushi-joshi-05 assign this issue to me I will fix this bug , i.e I will fix the navbar 
I am working under GSSOC24

**Comment by Satwik-Kar** [comment]
This issue caught my eye, and I'm curious to dig in. Let's team up and crack this one together! Excited to work on it with you!
@khushi-joshi-05  . Kindly assign me this issue under GSSOC'24
