### ISSUE TITLE
Missing Profile dropdown in the Navbar

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#181]
currently there is no Profile , signin, Myorders dropdown in the navbar . @khushi-joshi-05 mam assign this issue to me I will add this in the navbar . Thankyou

**Comment by Prachiii8287** [comment]
I would like to contribute in this work. Please assign me this work

**Comment by Meetjain1** [comment]
I am working under GSSOC24
