### ISSUE TITLE
Missing Signin , Signup page 

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#182]
Currently The signin, signup page is not present in the website @khushi-joshi-05 mam assign this issue to me I will add signin, signup page in the website .
I am working under GSSOC24
Thankyou

**Comment by Aksshay88** [comment]
@khushi-joshi-05 I am a GSSOC Contributor 24 and I would like to work on this issue 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/119944779/18277df1-d79f-4988-8cf8-7b164a28398c)

I could add this code and you could able to sign in and as well as sign up 
I would like to work on this issue

**Comment by MahadevprasadDL** [comment]
Hi,
I am contributing under GSSOC'24. I am having good knowledge in web development projects. I think I can handle it. Could you please assign me this issue.

**Comment by sunny0625** [comment]
This issue is already solved try different issues!
