### ISSUE TITLE
Missing Animations 

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#187]
Website looks good , But If there were some few animations in it , Then it will look awesome @khushi-joshi-05 mam assign this to me I will add some animations to it to make website more fascinating .
I am working under GSSOC24
Thankyou

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by Abdul-momin24** [comment]
Dear mam I would like to solve this issue @khushi-joshi-05
