### ISSUE TITLE
Navbar enhancing

### ISSUE THREAD

**Issue by jollyhub8278** [khushi-joshi-05/Food-ordering-website#188]
Navbar is looking so dull and simple. I have a nicer idea to make it more beautiful and eye-catchy. Kindle please assign me this task @khushi-joshi-05 . Here's my LinkedIn profile : https://www.linkedin.com/in/bharti-jangir-9a719a264/
![Screenshot 2024-05-12 124441](https://github.com/khushi-joshi-05/Food-ordering-website/assets/142597742/874d6cfd-56b7-4b7b-8e0c-6d4d680ea608)

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by jayanththalla** [comment]
Navbar is not sticky. It is not simple and responsiness. I have good idea to make attractive contact and cart make to left @khushi-joshi-05 . So,Kindly please assign to me.
