### ISSUE TITLE
Adding Search Bar for better User experience

### ISSUE THREAD

**Issue by pankajgawade** [khushi-joshi-05/Food-ordering-website#189]
Why : 
Adding Search bar in website helps enhancing User experience by enabling quick content discovery, Improving website usability, and reducing manual navigation 

What:
Currently there is no any search bar in the entire website for searching recipes and menus  so adding Search bar to website

This is the sample png of search bar 
![SearchBar](https://github.com/khushi-joshi-05/Food-ordering-website/assets/135791801/5afb3f58-fdcc-4edd-8b2e-b30d6d8aed61)

@khushi-joshi-05  Please assign this task to me under GSSoC,2024, I will add the search bar option in this website, Thank You.

**Comment by sunny0625** [comment]
@Riyasharma28 you can work on this issue!

**Comment by kesava23** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by sunny0625** [comment]
@kesava23 work on this issue
@Riyasharma28 is inactive for this issue!
