### ISSUE TITLE
syntax error in the index.html file

### ISSUE THREAD

**Issue by abhishekdumaniya** [khushi-joshi-05/Food-ordering-website#190]
`<button class="butt" onclick="window.open('Html-files/menu.html" target="_blank')">View Menu</button>`
Typo -->  `<button class="butt" onclick="window.open('Html-files/menu.html', '_blank')">View Menu</button>`
@khushi-joshi-05 can you please assign me

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by MahadevprasadDL** [comment]
please assign this issue for me . i am good in web development.

**Comment by FadikarSurangan** [comment]
@khushi-joshi-05 can you please assign this to me .
Thanks in advance.

**Comment by Deathnote45** [comment]
hi, I want to work on this issue can you please assign me?
my profile: https://www.linkedin.com/in/shuvangi-de-369071236/
