### ISSUE TITLE
No dedicated Error 404 Page 

### ISSUE THREAD

**Issue by r7projects-shayan** [khushi-joshi-05/Food-ordering-website#194]
## Problem

There must be a dedicated error 404 page for the users to land on and be alerted whenever they click on any wrong link or visit the wrong url

## Steps to reproduce 

A separate error 404 page following the color schemes of the website, which will have a button to redirect the users back to the website

## Additional Context

These are some of the inspirations 

![Screenshot 2024-05-12 130110](https://github.com/khushi-joshi-05/Food-ordering-website/assets/167475552/6fe6b1c2-0ba5-4ca4-a57e-a747d73c5155)
![Screenshot 2024-05-12 130901](https://github.com/khushi-joshi-05/Food-ordering-website/assets/167475552/4e344f3d-cea6-4e7f-a3d8-41eab3f6f116)
![Screenshot 2024-05-12 130950](https://github.com/khushi-joshi-05/Food-ordering-website/assets/167475552/509e9ea1-0d4e-49b2-953b-4f298883c25c)

## Program

Gssoc 24 

## Labels
- Level 2
- Gssoc 24

**Comment by r7projects-shayan** [comment]
@khushi-joshi-05 Kindly assign me this issue, so that I can work on it

**Comment by sunny0625** [comment]
@r7projects-shayan are you still up for issue?

**Comment by r7projects-shayan** [comment]
@sunny0625 Yeah, I can do it

**Comment by sunny0625** [comment]
Can you explain how it works?

**Comment by r7projects-shayan** [comment]
@sunny0625 Yes so, if an user tries to navigate around the website, and by mistake they navigate to some different url, or click on any wrong link, then they wont be able to find the homepage back, if there isn't a dedicated error page

**Comment by sunny0625** [comment]
@r7projects-shayan I guess by default they get the page not errors and the links are working.

**Comment by sunny0625** [comment]
You have given enough time!
