### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [khushi-joshi-05/Food-ordering-website#195]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by n14rishitha** [comment]
In The repository I can add a CONTRIBUTING.md file which will be helpful for all the contributor who visited this project
I would like to work on this issue . so please assign this task to me and Can u please label the issue as GSSoC'24

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
