### ISSUE TITLE
Footer link not working 

### ISSUE THREAD

**Issue by Rupalpy** [khushi-joshi-05/Food-ordering-website#196]
The navigation tab's links when clicked get opened in new tab which is not required ,more time to go to other tab and then back to the original tab . Also order now, take out order and book table links when clicked they don't smoothly navigate to order now part , it's all sudden .
![Screenshot_20240512_140133](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121295967/c22a9f47-05cb-4bda-966f-0d89e51ff394)

Also right above footer , our pages section must be responsive if i click on any of them it should take me to that section of page ,or that particular page

**Comment by Rupalpy** [comment]
@khushi-joshi-05 Kindly assign me this issue, so that I can work on it

**Comment by sunny0625** [comment]
The footer Link not working change the title and work on this issue!

**Comment by Rupalpy** [comment]
@sunny0625 Can you please specify a lil more which link in the footer is not working?

**Comment by sunny0625** [comment]
@Rupalpy are you still up for issue..!?

**Comment by Rupalpy** [comment]
#689 most of the things were good, added few changes on the files and created the pull request. @sunny0625
