### ISSUE TITLE
issue in Readme.md file 

### ISSUE THREAD

**Issue by Meetjain1** [khushi-joshi-05/Food-ordering-website#199]
Curently readme.md file is good , But it can be more fascinating If we add contributors section at the bottom of the file , and code of conduct section in the file . Thankyou @khushi-joshi-05 assign this issue to me I will add it , 
I am working under GSSOC24. Thankyou

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.

**Comment by shraddhha** [comment]
I'm eager to solve this issue, ensuring that the readme file accurately represents the project's progress and serves a comprehensive guide for contributors. It will enhance project's transparency and accessibility.
I am working under GSSOC24.
@khushi-joshi-05 @sunny0625 please assign this issue to me as I feel that Iwill be able to solve this issue more precisely and accurately. Thank you.
