### ISSUE TITLE
Adding Hover Effects to various buttons ,  Menu Card and social media links.

### ISSUE THREAD

**Issue by Mohit5Upadhyay** [khushi-joshi-05/Food-ordering-website#2]
I want to contribute under GSSoC'24 . Please assign it to me . I will surely add the hover effect to all card  , buttons as well as to all social media links. please assign it to me.

**Comment by kashyapsaksham012** [comment]
I can handle this task because I have previous experience working on similar projects.

**Comment by shuhaki** [comment]
Hello! Could you please assign this issue to me? I can help you work on this.

**Comment by AkshitGarg24** [comment]
I want to work on this issue. Can you please assign me this task?

**Comment by CharanAdithya6505** [comment]
i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

**Comment by TechSenseiX** [comment]
Hi, I hope you are doing well! I have experience with front end .
Could you please assign this issue to me?
I believe I can solve it effectively.
 I am eager to get started and make meaningful contribution to this project.

**Comment by BhargavTammana** [comment]
Hi, I have pretty good ideas about the hover effects which I have been working recently can assign this task to me I want learn and contribute under GSSoC'24

**Comment by kanishk-2** [comment]
Hi @khushi-joshi-05 , I'm a Gssoc'24 contributor.
I can improve hover effects for this project . Can you please assign it to me
so that I can start making meaningful contributions  to this project

**Comment by AditiJeena** [comment]
Can you assign this issue to me?

**Comment by Harsh-KumarJha** [comment]
Can I get this issue as I have similar experience that is require and want to contribute towards this as my first GSSoC contribution . I have good ideas for the hover animations for all kinds and it would be smooth.

**Comment by litesh1123** [comment]
objective - add hover effects to buttons, menu card , social media link.

solution- this can be done by using hover function , also have couple of ideas

please assign me this issue

**Comment by paridhi1509** [comment]
I have previous experience working on a task similar to this
please assign it to me 
thank you

**Comment by im-ysh** [comment]
hi @khushi-joshi-05 . I have done similar tasks while creating amazon clone website  myself . I  would love to make a better hover effects to various buttons , Menu Card and social media links.
I'm a gssoc contributor. Please assign the issue to me.Thank you.

**Comment by yashika0432** [comment]
I have been developing my own websites it is not completely developed assign this task to me I have done this work on my website too

**Comment by anglerfishlyy** [comment]
I have worked with frontend stacks . I am suitable for resolving this.
Can you assign me under GSSOC'24?

**Comment by Caliber-Ruchi** [comment]
I would like to contribute in this issue . Kindly assign it .

**Comment by maniranjan2023** [comment]
I want to contribute under GSSoC'24 . Please assign it to me . I will surely add the hover effect to all card , buttons as well as to all social media links. please assign it to me.

**Comment by Riddhi162** [comment]
i am a contributer of Gssoc 24 and have an hands on experience in ui have previously worked with adding wonderful hover animation to social media links and buttons can you please assign it to me

**Comment by PallaviGudupallavi** [comment]
@khushi-joshi-05 I would like to work  on this under GSSoC'24. can you please assign me this!

**Comment by asinha828** [comment]
hello, I would like to work on this issue. can i please ?

**Comment by sahithinandikula** [comment]
Hello @khushi-joshi-05 I am interested in working and contributing for this .I hope I will be considered for this issue and  add hover effects on the mentioned components and make it visually appealing .

**Comment by oddnumbercringe** [comment]
Hey , I know how to work with the hover function and can handle this task . Can you please assign this issue to me

**Comment by Caliber-Ruchi** [comment]
Hey @khushi-joshi-05 , I would like to work on this issue.Kindly assign it.

**Comment by pahuja-sahil** [comment]
hello @khushi-joshi-05 , I would like to work on this issue under  GSSoC'24. I have already built a blogging website using reactjs and uploaded it on my github.
Link - https://github.com/pahuja-sahil/Online-Blogging-System.
I can add the hover effects on various button easily and efficiently . So I kindly request you to please assign this issue to me under GSSoc'24 level 1.
Thank you.

**Comment by shivani3267** [comment]
Hey, I would like to work on it. Can you please assign it to me?

**Comment by bhuvangoel04** [comment]
Hi @khushi-joshi-05, Please assign me this issue. I have prior experience in animation, transitions, and effect like these.

**Comment by ayushiigarg** [comment]
Hi @khushi-joshi-05 please assign me this issue..i can solve it

**Comment by jency1** [comment]
I'm a Gssoc'24 contributor and I'm interested in working on the task of adding hover effects to the buttons, menu cards, and social media links. Please assign it to me, and I'll get started right away.

**Comment by vaishnavip27** [comment]
Hey, I would love to work on this issue, as previously I have worked on this before. Please assign me with this issue. Looking forward for the approval

**Comment by khushi-joshi-05** [comment]
@pahuja-sahil I have assigned you the issue. Go ahead . All the best.

**Comment by khushi-joshi-05** [comment]
@kanishk-2 I have assigned you the issue. Go ahead . All the best.

**Comment by anupa-rb** [comment]
Hi there, I've been learning UI/UX and I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by pahuja-sahil** [comment]
@khushi-joshi-05 I have created a pull request for the changes that are made by me but it seems there is a conflict .kindly see to it when you have time and reply if possible.
Thank you.

**Comment by kanishk-2** [comment]
@khushi-joshi-05 I have created pull request for the changes for hover effect on menu cards, social media icons.
Do check and reply . Thank you

**Comment by pahuja-sahil** [comment]
@sunny0625 and @khushi-joshi-05  kindly please see my pull request created today only with zero branch conflicts. Please respond with a text if possible .
