### ISSUE TITLE
adding foods in menu section 

### ISSUE THREAD

**Issue by somaakash** [khushi-joshi-05/Food-ordering-website#206]
i will create a good food menu page and will  mention cost,quantity and details by using html,css,bootstrap.
pls assign this issue to me

**Comment by n14rishitha** [comment]
I would like to work on this issue . so please assign this task to me and Can u please label the issue as GSSoC'24
I will add special menu and add rating (i.e stars) , cost.

**Comment by Srujitha-Raghava** [comment]
Hopefully, i am good at css,html and javascript. @khushi-joshi-05 please label this as gssoc and asssign this to me
