### ISSUE TITLE
Non-Responsive 'Book Table' Button Issue

### ISSUE THREAD

**Issue by bristiHalder** [khushi-joshi-05/Food-ordering-website#207]
@khushi-joshi-05 
The 'Book Table' button is currently non-responsive. It should redirect users to a booking page, which is not happening.

I would like to contribute to this project (gssoc'24 contributor)

**Comment by khushi-joshi-05** [comment]
@bristiHalder you can start working on it, itstead of a complete new page, if it show a pop up page with say location it will be great.

**Comment by Sanketmehta1724** [comment]
@khushi-joshi-05
i would like to solve this button responsivity issue.(GSSoC`24 Contributer)
