### ISSUE TITLE
Feat:Adding links to the titles(Footer section).

### ISSUE THREAD

**Issue by Brinda-07** [khushi-joshi-05/Food-ordering-website#208]
In the footer section, I can add links to the home services cart contacts titles.
It would help the user to easily navigate through the services by just clicking on it in the footer section.
Please assign this issue to me.

![Screenshot 2024-05-12 170757](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154052901/9f500c26-c8fa-4fde-9628-787c110e41fa)

**Comment by vallinayakichidambaram** [comment]
@khushi-joshi-05  Can you please assign the issue to me?

I am a GSSoC Contributor. Let me solve this as my first issue.

Thanks
