### ISSUE TITLE
[Enhancement] Enhance User Experience and Visual Appeal Across Website Elements

### ISSUE THREAD

**Issue by moroii69** [khushi-joshi-05/Food-ordering-website#209]
## Navbar:
- Center align the navbar and implement button-like effects for better differentiation.
- Introduce smooth scroll animation for seamless navigation through sections.

## Savor the Flavors Section:
- Apply hover animations to all elements within the boxes/cards to enhance interactivity.

## Download the App Buttons:
- Incorporate icons (Google Play Store and App Store) with modern effects for visual appeal.

## Footer:
- Customize email and message input fields in the 'Contact Us' section to match the website theme.
- Increase the size of the 'Your Message' input field.
- Update the copyright year to 2024.
- Make 'Home,' 'Menu,' 'Services,' 'Contact,' and 'Cart' clickable in the 'Our Pages' subsection.

## Menu Page:
- Enhance hover effects for buttons under dish names.
- Update dish prices to rupees and categorize food items under relevant headers.
- Change 'Order Now' buttons to 'Add to Cart' for consistency and functionality.

## Services Page:
- Implement pop-up elements for 'Gift Card and Voucher Redemption' and 'Exclusive Offers and Promotions' buttons.
- Adjust customer opinion picture dimensions to avoid stretching.
- Replace lorem ipsum text with authentic reviews and vary star ratings.

## Contact Us Page:
- Modernize the form theme to align with the website's aesthetic.
- Refine input questions for clarity.
- Add padding to the 'Send Message' button for centered text.
- Align footer text using container and alignment properties.

## Cart Page:
- Customize cart table theme to match the overall website theme.
- Include images of items added to the cart for visual reference.

### PS: Could you please assign this issue to me under GSSOC 24?

**Comment by vverma022** [comment]
I'd like to contribute to the project. Could you assign this issue to me

**Comment by Ufraan** [comment]
> I'd like to contribute to the project. Could you assign this issue to me

the issue can only be assigned by the repository owner/admins. so, we might have to wait a few hours or days for them to review all issues and assign them accordingly.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
