### ISSUE TITLE
[Enhancement] improving the ux

### ISSUE THREAD

**Issue by Vikashchou-dhary** [khushi-joshi-05/Food-ordering-website#214]
![food store](https://github.com/khushi-joshi-05/Food-ordering-website/assets/158028747/8725a033-8726-494a-a4ae-24969120a3c4)
@khushi-joshi-05 the right side look empty we can shift free delivery on right side and add photo of it for eye catching 
I can solve this issue. please assign it to me

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
