### ISSUE TITLE
New Feature : Food Showcase Section

### ISSUE THREAD

**Issue by mohitrajjha111** [khushi-joshi-05/Food-ordering-website#216]
Hi, I want to add a new Section related to food show.
Something like this.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/125960660/6a09e3e0-c834-4f43-a02b-f984a0f8acd8

If i have your permission, Can I please try?
if yes, please assign it to me under GSSoC'24

**Comment by mohitrajjha111** [comment]
I worked on it before generating the issue. So that i can be sure of able to implement this feature 
Here's a PR for the same.

https://github.com/khushi-joshi-05/Food-ordering-website/pull/219

Please consider merging PR

**Comment by mohitrajjha111** [comment]
@khushi-joshi-05 Please Assign under label GSSoC'24. I dont know if the points will be counted without it so to be safe.

**Comment by khushi-joshi-05** [comment]
@mohitrajjha111 that issue is already merged and i have also labeled it under gssoc and level1.

**Comment by mohitrajjha111** [comment]
@sunny0625 Please assign this to me and add appropiate labels. Its PR has been closed but it was still not assigned and labelled. Please do same. Thank you
