### ISSUE TITLE
Styling the part above the footer

### ISSUE THREAD

**Issue by ayush-848** [khushi-joshi-05/Food-ordering-website#217]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126975547/3aefe240-8a07-4689-b786-7009599e113b)

This part of the website looks unattractive.
The 'Your email' and 'Your Message' box does not have a proper boundary.

**Comment by ayush-848** [comment]
@khushi-joshi-05 Please assign this issue to me. I will give some ***hover effects*** and ***required styling*** to make it look more attractive.
I am participating as a contributor in GSSoC'24

**Comment by niteshbca** [comment]
Please assign to me task
