### ISSUE TITLE
Year is not updated on website 

### ISSUE THREAD

**Issue by kanishk-2** [khushi-joshi-05/Food-ordering-website#218]
<img width="586" alt="yr issue" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/157130879/ed9bd471-01c8-4936-a4cc-1d987cd5de1a">

yr is not updated on website its of last yr . Add level-1, gssoc'24 label and assign it to me will fix this issue

**Comment by DhruvJohri** [comment]
please assign this issue i can fix this issue

**Comment by vverma022** [comment]
I'd like to work on the issue and fix it

**Comment by khushi-joshi-05** [comment]
@kanishk-2 Do change the year from all the pages.

**Comment by kanishk-2** [comment]
@khushi-joshi-05 changed yr in all pages plz check

**Comment by nikita011203** [comment]
I'd like to work on the issue and fix it. Add level-1, gssoc'24 label and assign it to me will fix this issue
