### ISSUE TITLE
Creative Footers and Contact Section and Good UI for Bottom Section

### ISSUE THREAD

**Issue by kamalesh-og** [khushi-joshi-05/Food-ordering-website#22]
Description: The social media icons in the Footer section of the webpage are currently not linked to their respective social media handles and are also more creative and have good UI for the footer and contact section.

**Steps to Tackle:**
- Navigation to the respective pages.
- Locating the social media icons (Given, Facebook, Twitter, Instagram).
- Onclick Behavior: Clicking on a social media icon should redirect users to the respective social media handle.
- More Creative and impactful UI for the webpage

Actual Behavior:
Clicking on any social media icon does not redirect users to the handles and minimal usage of CSS.

Can you please assign me this issue,  I would love to work on the bottom section of the page.
Labels: bug, enhancement.

**Comment by kanikaa-3018** [comment]
along with clickability of the handles, it can also be given hover effects and ui can be improved along with addition of icons. please assign me this issue for GSSoc'24

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
