### ISSUE TITLE
Creating a separate Dessert Page.

### ISSUE THREAD

**Issue by Ishaparte** [khushi-joshi-05/Food-ordering-website#220]
I will Create a Separate Dessert page for users to order different types of desserts.
@khushi-joshi-05 Plz assign me this issue under gssoc 24.
thank you!
![dessert page](https://github.com/khushi-joshi-05/Food-ordering-website/assets/113294672/e6170a94-d188-4678-8b3d-81757ef2403d)

**Comment by jainaman78** [comment]
please add gssoc and levels tags
