### ISSUE TITLE
Update Navbar to make it more Appealing

### ISSUE THREAD

**Issue by harini-1597** [khushi-joshi-05/Food-ordering-website#222]
![Screen Shot 2024-05-12 at 7 52 01 PM](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128628820/fdd7662d-2573-4166-9cf3-4b68ad74a63f)

Currently the Navbar is very simple. I'd like to make it more appealing by improving CSS, something cleaner looking like this:

![0_2opgK6RrvU_nn_KJ](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128628820/f5d63dda-66f2-4e57-97f3-a749f141bcbd)

**Could you assign this issue to me under GSSoC? Thanks.**

**Comment by niteshbca** [comment]
Please assign to me task

**Comment by theeayushkumar** [comment]
I would add hover and animation effects too on the navbar. 
Assign this to me

**Comment by hritika2409** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/117531823/0d92e07d-0d75-45c5-a146-abe3d421ad03

can i help u with this as i have already addressed this problem in my previous project. and please do assign the labels
