### ISSUE TITLE
Add Hover Effects on Menu, Services, Cart, and Contact Us Pages

### ISSUE THREAD

**Issue by ishap11** [khushi-joshi-05/Food-ordering-website#225]
Hello, This is Isha Prajapati , I've observed a lack of hover effects on buttons, menu cards, and social media links across various pages of our website except home page. Implementing hover effects enhances user interaction and improves visual feedback.
I propose to add hover effects to these elements, engaging user experience throughout the website. Could you please assign me this task under gssoc'24.
Thank you!

**Comment by Harshit279096** [comment]
i can do this. I have expertise in this field please assign this task to me.

**Comment by pahuja-sahil** [comment]
@ishap11 i kindly request you to please first search the issue you are trying to impose as this issue is already created but not solved . please refer issue #2 
Thank you.
