### ISSUE TITLE
Bug: Bill amount is missing still it is showing an alert that the order is placed in the cart section

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [khushi-joshi-05/Food-ordering-website#227]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/138589633/ce1ba3ca-8bdb-4e08-9ff3-35c4f0927bf5

In the CART section, the bill amount appears to be missing, yet the system indicates that the order has been successfully placed

**Comment by khushi-joshi-05** [comment]
@Ishitamukherjee2004 Can u solve this bug?

**Comment by Ishitamukherjee2004** [comment]
@khushi-joshi-05 Yes, definitely I can solve Please assign me this issue.

**Comment by Ishitamukherjee2004** [comment]
@khushi-joshi-05 I have solved the bug. Can you please check it!
