### ISSUE TITLE
Sample menu list is not responsive

### ISSUE THREAD

**Issue by pankaj-bind** [khushi-joshi-05/Food-ordering-website#23]
![tg](https://github.com/khushi-joshi-05/Food-ordering-website/assets/73558583/11a0f66d-1f51-4917-ab90-bd7bfd7a8ce1)

Proposed Changes:
Sample menu shown are not responsive.
Please assign me this work, I can make it responsive.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
