### ISSUE TITLE
 update offer/discount  option should be on top 

### ISSUE THREAD

**Issue by Reshma-2301** [khushi-joshi-05/Food-ordering-website#231]
as the discount option is diplayed in the bottom of the site . according to my concern it should be on the top so that it can catch customer eyes . 

![Screenshot ](https://github.com/khushi-joshi-05/Food-ordering-website/assets/162494882/ba0e8660-7828-4d58-82c2-f338e4580916)

**Comment by khushi-joshi-05** [comment]
@Reshma-2301 I have assigned u the task. Do adjust it in best way and after completion do attach a screenshot.
