### ISSUE TITLE
Styling navigation bar and contact page 

### ISSUE THREAD

**Issue by Pragni24** [khushi-joshi-05/Food-ordering-website#235]
Hey, @khushi-joshi-05. I've noticed a few issues with the website that I'd like to work on:

**Navigation Bar Enhancement:**The navigation bar could be made more attractive. I propose to redesign it to improve its visual appeal and user experience.

**Background Image Issue:** There is a white space at the bottom of the homepage due to the background image. I can modify the image or adjust the layout to eliminate this space.

** The styling of the navigation page looks a bit dry. I can enhance it to make it more engaging and visually appealing.

Here are the screenshots for reference:
1. Home Page and navigation bar
![ss1](https://github.com/khushi-joshi-05/Food-ordering-website/assets/129032980/8aff473f-3cec-4f15-a78e-7224800fbb73)

2.  Contact page:
![ss2](https://github.com/khushi-joshi-05/Food-ordering-website/assets/129032980/f9807737-cca8-4d2d-84ce-6cd29dd5f902)

Could you please assign me this issue under GSSoC'24?

**Comment by Pragni24** [comment]
@khushi-joshi-05 , Please assign me this issue under GSSoC'24.

**Comment by Manaswini123456** [comment]
@khushi-joshi-05 kindly assign me with this issue

**Comment by khushi-joshi-05** [comment]
@Pragni24 I have assigned you the issue. Can u modify the UI of contact page and its footer and make it similar to other pages with an image in background.

**Comment by Pragni24** [comment]
Yes,sure

**Comment by Anshu3301** [comment]
Hello, I've updated the UI of the  contact page, please have a look...
If you like it, please assign this to me too, under GSSOC'24.

![Screenshot (162)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/134282893/d45a6f0e-7c7e-419b-9828-d1c44ff8b027)
 
![Screenshot (163)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/134282893/fd2fbf23-16c4-41b7-bbc6-aa1529c47eb6)
