### ISSUE TITLE
index.html file need to update

### ISSUE THREAD

**Issue by pankaj-bind** [khushi-joshi-05/Food-ordering-website#24]
Proposed changes:
1) The name in title tag is wrong.
2) Link of home button is not working, it should open the same home page.

Please assign me this work.

**Comment by Vaibhav-Kumar10** [comment]
Please assign this task to me. I am interested in this problem

**Comment by atharvakej** [comment]
@khushi-joshi-05 @pankaj-bind  Please review my PR resolving this issue.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!
