### ISSUE TITLE
BUG - In navigation bar

### ISSUE THREAD

**Issue by Harleen-786** [khushi-joshi-05/Food-ordering-website#240]
Describing the bug
When navigating from the navigation bars on index.html page to the menu.html or services.html or cart.html or contact.html the user is not directed to the particular section as expected.

Expected behavior
Clicking on the navigation bars on the index.html page should take the user back to the particular section to the other menu.html , contact.html , cart.html.

Screenshots :

<img width="964" alt="Screenshot 2024-05-12 at 11 48 13 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/d2b7bd20-0887-4518-9d8d-655ad9a43762">
<img width="1440" alt="Screenshot 2024-05-12 at 11 48 27 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/93764071-0f00-4b39-9447-cad99260bc65">
<img width="865" alt="Screenshot 2024-05-12 at 11 48 31 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/2f23e1ef-7f8a-4f3a-9af2-e8583444fcb3">
<img width="734" alt="Screenshot 2024-05-12 at 11 48 41 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/f05fb09a-c7a3-4f89-9acb-9aa02d2b3cac">

I am contributing from open source GSSOC24.
Please assign me the issue.

**Comment by NAVJOT-786** [comment]
please i too want to work on this issue please assign issue to me as well i m contributing from GSSOC24.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by AnanyaChauhan17** [comment]
HI hope this message finds you well. I'm currently working on a web development project and as an GSSoC contributor I am writing to express my interest in assisting with the resolution of the project issue you mentioned. After reviewing the details you provided regarding the navigation links bug on the website, I am eager to contribute my skills to help address this challenge. As someone with experience in web development and a passion for problem-solving, I'm confident I can help diagnose and fix the issue effectively.

**Comment by Harleen-786** [comment]
@khushi-joshi-05  please assign the issue
