### ISSUE TITLE
Link opening in new Tab

### ISSUE THREAD

**Issue by im-alok** [khushi-joshi-05/Food-ordering-website#248]
when you click a link in your navbar, it opens the linked page in a new tab every time. This behavior can lead to multiple tabs being opened if the link is clicked repeatedly. To address this, you can modify the links to open in the same tab.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
