### ISSUE TITLE
Add Restaurant Page

### ISSUE THREAD

**Issue by Nitin8426** [khushi-joshi-05/Food-ordering-website#249]
**Description of Page** 
 The "Add Restaurant" feature allows users to contribute new restaurants to our website's Restaurant directory.  This empowers user to choose A large variety of food item from various Restaurants available . help partnership with large restaurants outlet and deliver food to various users.

**Features:-**
Scroll down Animation with responsive web page options.
![Screenshot 2024-05-13 020341](https://github.com/khushi-joshi-05/Food-ordering-website/assets/164453064/7a7f2bd5-3294-464a-a7f2-9cf68acdc341)

Please Assign me this Issue. will take care of background just tis is demo to pitch the idea

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
