### ISSUE TITLE
Add LinkedIn of KHUSHI JOSHI

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#255]
Click on Kushi Joshi will direct you to her LinkedIn page.
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/50f896e3-97e6-420e-a566-b9ac2371dbd3)

**Comment by Ansh101112** [comment]
Please assign me this under gssoc'24 @khushi-joshi-05 I want to work on this

**Comment by sunny0625** [comment]
Okay, @Ansh101112 you can work on this issue!

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by Ansh101112** [comment]
> Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

Already assigned to me and I am working on it please see other issues

**Comment by jainaman78** [comment]
I have read the issue and i think i can solve this problem. I'm eager to contribute to your project through GSSOC. Could you please assign me issue

**Comment by Ansh101112** [comment]
@sunny0625 sir pr raised please see to close this issue.
