### ISSUE TITLE
Add Hover Effect on Footer Social Media

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#256]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/b8a544f5-e9a6-4655-bac3-f796fce0e888)

**Comment by pulkitgarg04** [comment]
Please assign this issue to me under GSSoC'24

**Comment by pahuja-sahil** [comment]
hello @khushi-joshi-05 , I would like to work on this issue under GSSoC'24. I have already built a blogging website using reactjs and uploaded it on my github.
Link - https://github.com/pahuja-sahil/Online-Blogging-System.
I can add the hover effects on various button easily and efficiently . So I kindly request you to please assign this issue .
Thank you.

**Comment by tomartanu** [comment]
I want to  work on this issue please assign to this issue to me.

**Comment by Vaibhav-kesarwani** [comment]
i want to work on this issue if possiable than assign it to me i have good experience in UI so i can help you with that

**Comment by dakshika-chaudhary** [comment]
I want to work on such issue ,please assign it to me

**Comment by DhruvPandey1** [comment]
please review my PR I have fixed these Issue Under GSSOC'24

**Comment by MUKUL-RAJPUT2004** [comment]
Hello
Please assign it to me in Gssoc 24 . I will solve the issue a my earliest.
Thank you

**Comment by poswalsameer** [comment]
Hello @khushi-joshi-05, I have created PR #291 with the said change, hoping for it to get merged.

Thank You!

**Comment by anshikatiwari20** [comment]
I'm interested in working on this issue. Could you please assign it to me? I'm eager to dive in and get it resolved as soon as possible.

**Comment by anupa-rb** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by Nih1tGupta** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24.I have good experience in UI so i can help you with that @khushi-joshi-05 .

**Comment by harii1227** [comment]
I'm eager to join the journey of innovation and collaboration! Please assign me a project that aligns with my interests and skills. Let's work together to create something remarkable and leave a lasting impression.
Warm regards.

**Comment by Suruchibharti** [comment]
hii @khushi-joshi-05  ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by MrudulaTeegala** [comment]
@khushi-joshi-05 kindly assign this issue to me

**Comment by satya-sl** [comment]
Hi @sunny0625 sir , I can do it please assign this issue to me sir.

**Comment by loginglug** [comment]
"Excited to contribute to GSSoC'24! Assign me tasks aligned with my skills. Ready to deliver quality work and collaborate effectively."

**Comment by sunny0625** [comment]
@pulkitgarg04 assigned

**Comment by Nih1tGupta** [comment]
> Why contributors are applying the hover effect only homepage what about other pages?

@sunny0625  please see issue #372

**Comment by pulkitgarg04** [comment]
> Why contributors are applying the hover effect only homepage what about other pages?

@sunny0625 There is the same CSS file for menu, and service page. Moreover, the homepage has a hover effect but it's inconsistent on other pages. Can I fix this?

**Comment by sunny0625** [comment]
Okay solve by creating the new issue and tag me I labels level 2.
