### ISSUE TITLE
Card not responsive

### ISSUE THREAD

**Issue by pankaj-bind** [khushi-joshi-05/Food-ordering-website#26]
![Uploading image.png…]()
Proposed changes:
Cards in second section is not responsive.
Please assign me this task.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by JanitKumar** [comment]
Please assign this issue it to me as I have the required skills to do it

**Comment by mdramijzamadar** [comment]
please assign this project I would like to work.
