### ISSUE TITLE
Cards in Menu section overflows out of Container div

### ISSUE THREAD

**Issue by vallinayakichidambaram** [khushi-joshi-05/Food-ordering-website#261]
Hi @khushi-joshi-05 @sunny0625 
 The cards in the menu section goes out of body which creates an unnecessary black space and scroll bar at the bottom.

![Screenshot (100)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/109519460/ed2180cd-0922-42b0-a820-bf556d6b79e5)

I am a GSSoC contributor and I can fix this issue. Kindly assign it to me.

PS: Please add the label as GSSoC

Thanks
Valli Nayaki Chidambaram

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
