### ISSUE TITLE
Organise the menu page and arrange it in a proper manner

### ISSUE THREAD

**Issue by kavyachandarkar** [khushi-joshi-05/Food-ordering-website#262]
I am writing to request an urgent update to the menu page. I have noticed that the current layout is disorganized and uninviting, which may be deterring potential customers from exploring the menu offerings. Specifically, the arrangement of items on the page is inadequate, and the lack of aesthetic appeal makes it difficult to navigate.

To address these concerns, I would appreciate it if you could kindly implement the necessary changes to improve the appearance of the menu page and make it more user-friendly. Some suggestions for improvement could include reorganizing the items into logical categories, providing clear and concise descriptions for each item, and incorporating visually appealing graphics or photos. Additionally, ensuring that the menu is easy to access and navigate on both desktop and mobile devices would greatly enhance the user experience.

I am confident that with these updates, we can significantly enhance the overall customer experience, leading to increased engagement and satisfaction with our menu offerings. Thank you for your attention to this matter, and I look forward to hearing back from you soon.

<img width="944" alt="Screenshot 2024-05-13 132132" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/156076079/4fd2f9ab-2fa1-41a4-8e3f-0515f12d9f20">

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
