### ISSUE TITLE
Design nav bar responsive

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [khushi-joshi-05/Food-ordering-website#271]

**Comment by DharshiBalasubramaniyam** [comment]
@khushi-joshi-05 can you assign this issue to me. I ll make nav bar respo sive in all pages like in the video of pr #211

**Comment by navin-3959** [comment]
@khushi-joshi-05
 assign this issue to me i am expert in building responsive design

**Comment by KS11177** [comment]
@khushi-joshi-05 I have been working with responsive designs for a long time, could you assign this issue to me? I can fix this easily
