### ISSUE TITLE
Issue with "Titles" 

### ISSUE THREAD

**Issue by aakrati14** [khushi-joshi-05/Food-ordering-website#272]
Hey @khushi-joshi-05 ,  I've noticed a few issues with the website that I'd like to work on:

**Website Title Enhancement:** As we click on Home , Menu , Service , Contact and Cart , we reach on another page , but the title above on the screen does not change as you can see in the screenshots. It's always showing "Food ordering website" , only on Cart page it shows "My Cart". I think on loading other pages too , It should have some amazing title like 
"Food Ordering Website | Home" or "Foodie Website | Home"
"Food Ordering Website | Service" 
"Food Ordering Website | Contact" 
"Food Ordering Website | Cart"

So that user can easily see what page they are loading.

![Screenshot (136)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147893415/55cfe027-dae7-4a13-a877-89f70927c379)
![Screenshot (137)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147893415/2237c59a-7027-4f12-8e10-a6ed6ebcb817)
![Screenshot (138)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147893415/d11d4499-d2b8-4dcb-8bf8-181357eea3c5)
![Screenshot (139)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147893415/342a9526-9224-4c66-9475-6bfa7f6f898e)

Could you please assign me this issue under GSSoC'24?

**Comment by navin-3959** [comment]
i want to work on this project

**Comment by navin-3959** [comment]
please assign me
