### ISSUE TITLE
Repeating Background image in service-container section #GSSoC24

### ISSUE THREAD

**Issue by SamarupBhattacharya** [khushi-joshi-05/Food-ordering-website#273]
Hi,
I noticed that the background image you have set for the **service-container** section in the **index.html** file, is repeating. I am attaching a ss for reference 
![bandicam 2024-05-13 17-19-51-035](https://github.com/khushi-joshi-05/Food-ordering-website/assets/138982308/58bd9dcf-a006-40e2-8035-8e383597ae99)

It's a very simple fix, just two lines of code, if you want @khushi-joshi-05 , @sunny0625 , I can do it, and it will look like this

![bandicam 2024-05-13 17-23-10-912](https://github.com/khushi-joshi-05/Food-ordering-website/assets/138982308/7b45cb8c-d9a8-4b0c-8e72-2e90b700c9db)

**Comment by sunny0625** [comment]
@SamarupBhattacharya can work on this issue

**Comment by sunny0625** [comment]
@SamarupBhattacharya Tag your PR here!

**Comment by sunny0625** [comment]
This issue has been solved, Try to participate in different issue!
