### ISSUE TITLE
Elements overflowing from the page

### ISSUE THREAD

**Issue by suma30** [khushi-joshi-05/Food-ordering-website#275]
# Problem
Few elements are overflowing from the home page which is not looking good
![Screenshot 2024-05-10 122654](https://github.com/khushi-joshi-05/Food-ordering-website/assets/112741893/9d85a1be-e82b-445a-9b09-3d1b588c21a1)

# Solution
I will fix it and make it better

# Request
Please assign me this issue under GSSOC 2024 @sunny0625 @khushi-joshi-05

**Comment by suma30** [comment]
@sunny0625 @khushi-joshi-05 Please check this issue and can you assign it to me

**Comment by suma30** [comment]
@khushi-joshi-05 @sunny0625 Please can you confirm about this issue #275, should I close it and create other issues or not?

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
