### ISSUE TITLE
improve ui of navebar

### ISSUE THREAD

**Issue by 39palakved** [khushi-joshi-05/Food-ordering-website#278]
i want to improve ui of  navebar . please assign this task to me.

**Comment by hritika2409** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/117531823/27d6cb9b-f1a5-4f56-b70e-a90acb3ad6bc

I would like to help u with this.I have addressed this issue in my website too.SO can u please assign me this task

**Comment by dakshika-chaudhary** [comment]
@sunny0625 

I would love to add a nice hover effect to the navbar to make it more apperable.
I know Tailwind CSS very well as i have alredy worked over it kindly assign it to me.
