### ISSUE TITLE
Navbar Directory Not Found

### ISSUE THREAD

**Issue by 07sumit1002** [khushi-joshi-05/Food-ordering-website#28]
Expected Behavior:
The directory should lead to the corresponding page without any errors.

Actual Behavior:
Users are encountering a "Directory Not Found" error message when clicking on the directory in the navbar as shown in the image.

Proposed Solution:
Investigate the backend to ensure that the correct directory paths are linked to the navbar items. Test and verify that clicking on each directory correctly navigates to the intended page without any errors.

![Screenshot_20240509_214436](https://github.com/khushi-joshi-05/Food-ordering-website/assets/98510898/6fea5f8c-163a-49a5-8aff-da4612069d9d)

**Comment by MahawarHemlata** [comment]
can you please assign this issue to me??

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this issue ?
