### ISSUE TITLE
Updating the contact page UI and adding the favicon icon

### ISSUE THREAD

**Issue by Khanishsuresh** [khushi-joshi-05/Food-ordering-website#288]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136162512/dc0f75cf-b38b-434a-a308-97e981156fcf)

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136162512/cfef97bd-6788-4626-82ac-76464c870f6a)
By adding a good designed favicon the webpage would be nice

If the UI of the contact section is been updated it would be so useful for the user to contact us.

**Comment by Anshu3301** [comment]
Hello, here's the updated UI of the  contact page, please have a look...
If you like it, please assign this to me too, under GSSOC'24.

![Screenshot (162)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/134282893/d45a6f0e-7c7e-419b-9828-d1c44ff8b027)
 
![Screenshot (163)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/134282893/fd2fbf23-16c4-41b7-bbc6-aa1529c47eb6)
