### ISSUE TITLE
Add Link to the Google Play and App Store image.

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#289]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/3db07583-67b7-4c62-950c-7605fbe47365)

**Comment by K-Svayam05** [comment]
Hello! I am a GSSoC '24 Contributor, and being experienced with HTML, CSS, JS and React, I would like to work on this issue. So I request you to assign this task to me!

**Comment by jainaman78** [comment]
@sunny0625 I'm eager to contribute to your project through GSSOC. Could you please assign me issue.

**Comment by sunny0625** [comment]
@K-Svayam05 I want you to work on the Level 3 issue which I will update in the future check the issue section regularly. I require react tech stack.

@jainaman78 you may work on this issue.

**Comment by jainaman78** [comment]
@sunny0625 where are the links of google play and app store?. can you provide me the links so that i can add them on page

**Comment by sunny0625** [comment]
Currently, the PA has not deployed any application. Try any food app for the same!

**Comment by jainaman78** [comment]
@sunny0625 please accept my PR

**Comment by Aishu040** [comment]
@sunny0625 I'm eager to contribute to your project through GSSOC. Could you please assign me issue.

**Comment by krati234** [comment]
assign please

**Comment by K-Svayam05** [comment]
> @K-Svayam05 I want you to work on the Level 3 issue which I will update in the future check the issue section regularly. I require react tech stack.
> 
> @jainaman78 you may work on this issue.

Okay Sir will keep myself updated!

**Comment by PuR-vI** [comment]
Please assign this task to me under GSSoC 24

Thank you!

**Comment by loginglug** [comment]
"Excited to contribute to GSSoC'24! Assign me tasks aligned with my skills. Ready to deliver quality work and collaborate effectively."

**Comment by Aishu040** [comment]
Please assign me a task and I am interested to work with this project. I
also attached my LinkedIn and github profile.


LinkedIn profile https://www.linkedin.com/in/aishwarya-s-55054822a
Github link : https://github.com/Aishu040

Thank you

**Comment by sunny0625** [comment]
@jainaman78 mentioned PR id here...!

**Comment by jainaman78** [comment]
> @jainaman78 mentioned PR id here...!

@sunny0625 PR id is 296

**Comment by sunny0625** [comment]
@K-Svayam05 do check out #368 issue.

**Comment by jainaman78** [comment]
@sunny0625 I don't know why it is showing me unassigned project. Can you please look into it

**Comment by jainaman78** [comment]
@sunny0625 can you please assign me this again

**Comment by sanskriti-lal** [comment]
I want to work on this issue under GSSoC'24. Please assign me this.

**Comment by sanskriti-lal** [comment]
It's not showing that I've been assigned this issue. can you please look into it @sunny0625

**Comment by JisharamAdigarla** [comment]
@sunny0625 could you please assign me this issue , i ll make sure it works completely

**Comment by Sajiyasiddiqui** [comment]
I want to work on this please assign me.

**Comment by n14rishitha** [comment]
@sunny0625 
I would like to work on this issue . so please assign this task to me . I can complete this task.

**Comment by n14rishitha** [comment]
@sunny0625 
Thank you so much foe assigning this issue to me .

**Comment by n14rishitha** [comment]
> Currently, the PA has not deployed any application. Try any food app for the same!

@sunny0625 can i add any food app link here.
