### ISSUE TITLE
Customer Review

### ISSUE THREAD

**Issue by kanikaa-3018** [khushi-joshi-05/Food-ordering-website#29]
pls assign this issue to me for GSSoc'24. (customer review and rating section can be added )

**Comment by harshmishra19** [comment]
Hello @khushi-joshi-05 Can you plz assign this issue to me under GSSOC'24

**Comment by pranav-666** [comment]
@khushi-joshi-05 please assign this project to me under GSSOC'24

**Comment by Anamika-Ratna** [comment]
Hi! I would like to add customer review/ testimonial section, kindly assign me this issue under the gssoc tag.
Sample work:-
![Screenshot (670)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/122286548/31bc9b48-4e70-4c06-9a1b-6d209bc18d45)

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
