### ISSUE TITLE
Animation enhancement of card component 

### ISSUE THREAD

**Issue by jayesh2474** [khushi-joshi-05/Food-ordering-website#290]
Add animation in card component for better look when we hover on this.
Please assign this issue me to under Gssoc'24 , i would like to work on this
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115784462/cbb9b19f-ce80-4d06-b094-a520c85e6b8d)

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.

**Comment by jayesh2474** [comment]
@Riyasharma28 Why ?? Please work on your own issue.

**Comment by Riyasharma28** [comment]
> @Riyasharma28 Why ?? Please work on your own issue.

I have done that sir, we can participate in multiple contributions
