### ISSUE TITLE
Add more Cards in Menu Section

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#298]
We want the Contributor to add more specialized menu items to the Menu webpage.
Like more single Items.

Ex: In Dishes:
- Shahi Paneer
- Pav Bhaji
etc.

**Comment by Nih1tGupta** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24.

**Comment by SamarupBhattacharya** [comment]
@sunny0625 I would love to make this contribution. Pls assign this to me

**Comment by pahuja-sahil** [comment]
hello @sunny0625  , I would like to work on this issue under GSSoC'24. I have already built a blogging website using reactjs and uploaded it on my github.
Link - https://github.com/pahuja-sahil/Online-Blogging-System.
I can add the various menu items as u specified earlier easily and efficiently . So I kindly request you to please assign this issue to me.
Thank you.

**Comment by Khusi2005** [comment]
Hey, @sunny0625 please assign me this issue under gssoc,24.

**Comment by sancharigandhi** [comment]
> We want the Contributor to add more specialized menu items to the Menu webpage. Like more single Items.
> 
> Ex: In Dishes:
> 
> * Shahi Paneer
> * Pav Bhaji
>   etc.

Hi @sunny0625,
I'm excited to tackle the task of adding more specialized menu items to the Menu webpage. With my experience in website development using HTML, CSS, and JavaScript, I'm confident I can enhance the menu effectively and uniquely.

I'll begin by carefully selecting diverse and appetizing dishes to complement the existing menu. I'll ensure each item is showcased in an appealing manner to entice visitors.

Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by Karthikkariappa08** [comment]
hello @sunny0625 plz assign this issue to me. i will solve it

**Comment by Priyanjali24** [comment]
hello @sunny0625 plz assign this issue to me. I would like to work on this project

**Comment by Ansh101112** [comment]
@sunny0625 sir please assign me this issue to work on.

**Comment by rashmitha155** [comment]
> We want the Contributor to add more specialized menu items to the Menu webpage. Like more single Items.
> 
> Ex: In Dishes:
> 
> * Shahi Paneer
> * Pav Bhaji
>   etc.

hello @sunny0625 I would like to work on this issue under GSSoC'24. 
I can integrate the various menu items as u specified earlier. I will add those menu cards by using bootstrap cards, it will look attractive and more efficient as well.
 So, I kindly request you to please assign this issue to me.
Thank you.

**Comment by Ansh101112** [comment]
> We want the Contributor to add more specialized menu items to the Menu webpage.
> Like more single Items.
> 
> Ex: In Dishes:
> - Shahi Paneer
> - Pav Bhaji
> etc.

@sunny0625 sir please assign me this issue

**Comment by AditiPrabhakar** [comment]
hey @sunny0625 , 
I've worked on a restaurant website before too, please assign this to me.

**Comment by sunny0625** [comment]
@Nih1tGupta Assign to you.

**Comment by vandana79039** [comment]
I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. please assign this issue to me.

**Comment by Ansh101112** [comment]
> @Nih1tGupta Assign to you.

Sir please see my PR #355

**Comment by Nih1tGupta** [comment]
@sunny0625 Thank you  for this opportunity

**Comment by Nih1tGupta** [comment]
@sunny0625 , @khushi-joshi-05 , please see my PR #365 .
