### ISSUE TITLE
Images not properly visible and improve the UI of the carts.

### ISSUE THREAD

**Issue by Anou25** [khushi-joshi-05/Food-ordering-website#300]
In the customer opinion portion the images are not clearly visible and the carts are also not visually appealing.
Features to be added:-
1) The images have to be properly added so that it is clearly visible.
2) The carts also seem to be dull so it can be made more visually appealing. 

![Screenshot 2024-05-13 205634](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136624807/2cee2068-aef7-4a20-b7b5-507ee63724ae)

- [x] I agree to the https://github.com/khushi-joshi-05/Food-ordering-website/blob/863d18d82f8be000dcab0fa0bd09379c41f827d4/CODE_OF_CONDUCT.md

@khushi-joshi-05 please assign the task to me.

**Comment by aasthabagrawal** [comment]
Hey!
I have already made a food website, so having an experience in this, I can make required changes for the same.
