### ISSUE TITLE
Remove Duplicate

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#303]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/c5e3443a-1030-48cc-b49b-f99e330bbc39)
keep 1st line remove 2nd line.

**Comment by SamarupBhattacharya** [comment]
I would love to do this. Please assign it to me.

**Comment by SamarupBhattacharya** [comment]
Done
![bandicam 2024-05-13 22-29-28-249](https://github.com/khushi-joshi-05/Food-ordering-website/assets/138982308/f49eed31-75e0-47ff-96cc-ff09a85beb16)

**Comment by SamarupBhattacharya** [comment]
Done

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by ZnbKhan** [comment]
Hi Khushi Joshi
I hope you're doing well! I'd like to take a shot at fixing this issue. Could you please assign it to me?
Looking forward to contributing!

**Comment by krati234** [comment]
i would like to work on this issue , please assign this to  me

**Comment by loginglug** [comment]
Sure, here's a condensed version:

"Excited to contribute to GSSoC'24! Assign me tasks aligned with my skills. Ready to deliver quality work and collaborate effectively."

**Comment by SamarupBhattacharya** [comment]
@sunny0625 I had removed the lines of code from index.html file that was causing the second line to display and I had made a PR yesterday only, however it has not been merged yet. Can you please check it once ? If there is any issue with the PR, please do inform me and I will fix it right away.

Thanks
