### ISSUE TITLE
Contact page UI

### ISSUE THREAD

**Issue by Nikhilsaini481-tech** [khushi-joshi-05/Food-ordering-website#305]
@khushi-joshi-05  i want to re-design the ui of contact  us page a s it is not up to mark please assign this issue to me
![Screenshot 2024-05-13 at 10 15 10 PM](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136163754/f8dd4016-7b59-4432-92d2-1268b76be
![Screenshot 2024-05-13 at 10 15 10 PM](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136163754/75ff12c8-0583-406a-80d0-b1c69f611bcd)
3c9)

**Comment by Riyasharma28** [comment]
Kindly assign me @Riyasharma28 under GSSOC'24

**Comment by dakshika-chaudhary** [comment]
@khushi-joshi-05 ,I think the contact page must not be so conjusted.
I would love to add my Tailwind CSS skills to it to make it more attractive.
