### ISSUE TITLE
Add login/signup page

### ISSUE THREAD

**Issue by Sneha123-zudo** [khushi-joshi-05/Food-ordering-website#31]
Please assign me this issue under GSSOC'24.

**Comment by Sibam-Paul** [comment]
Hey I want to work on  this issue under GSSOC'24
login and sign up with HTML,CSS

**Comment by Nayanika1402** [comment]
Hey,I would like to work on this issue.Can make a detailed and working login and sign up page using the required web stack.
Please assign me the issue.

**Comment by KunjMaheshwari** [comment]
@khushi-joshi-05 Please can you assign this issue to me. I am a contributor under GSSOC'24

**Comment by mrskjha** [comment]
@khushi-joshi-05 pls assign me for this issue i can do this. this is my first open source contribution so pls assign me

**Comment by Mohammed-790** [comment]
Please assign this issue to me sir i will give my best

**Comment by AnushkaSaini26** [comment]
I'm eager to contribute! Could you please assign me this issue under GSSOC 2024?
@khushi-joshi-05

**Comment by royalrajputayush** [comment]
@Sneha123-zudo I want to work on this issue, please assign me this under GSSoC level 2.

**Comment by royalrajputayush** [comment]
Describe the feature
I want to work on the nav section, please assign me this under gssoc level 2

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
