### ISSUE TITLE
At stages of responsive make images equal in cards in menu.html

### ISSUE THREAD

**Issue by cxde-Sujal** [khushi-joshi-05/Food-ordering-website#321]
![Screenshot (147)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/137087363/616ebf7e-463a-40a6-be72-7df8f38217fb)
@sunny0625

**Comment by Sudharshana426** [comment]
I would love to work on this project. Could you assign me this task for better grid implementation and CSS styles for the issue? I have worked on multiple projects. Check out my LinkedIn Profile: https://www.linkedin.com/in/sudharshanab

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
