### ISSUE TITLE
[fix]: Correcting the spelling mistake

### ISSUE THREAD

**Issue by souvik-maity** [khushi-joshi-05/Food-ordering-website#326]
![Screenshot 2024-05-14 031107](https://github.com/khushi-joshi-05/Food-ordering-website/assets/145227417/de7701d1-1749-4cd9-8b30-db829b75c938)
Here the spelling of restaurant has to be corrected.

**Comment by Sriansh-raj** [comment]
Pls assign it to me.

**Comment by Sriansh-raj** [comment]
Resolved this issue in PR #330. This issue can be closed as solved 😄
