### ISSUE TITLE
No proper Redirection of Pages !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [khushi-joshi-05/Food-ordering-website#334]
There is no proper redirection of pages!!! As by clicking each page in navbar its openning new tab in browser, which is disruptive and confusing for users. This can be  ensured that clicking on the navbar direct users to the intended sections within the browser interface, rather than opening new browser tabs.

**Comment by Riyasharma28** [comment]
Kindly assign me @Riyasharma28 under GSSOC'24
