### ISSUE TITLE
 Enhance the navigation bar by applying a glass morphism effect and sections of landing page needs to made responsive.

### ISSUE THREAD

**Issue by abhinandan202004** [khushi-joshi-05/Food-ordering-website#337]
1.  **Landing page Responsiveness**

-  There are some sections in the landing page that needs to be made responsive 
-  Buttons need to be made a bit responsive and suit the theme of webpage
-  Background images of some sections needs to stop repetition present in them.

![Screenshot 2024-05-14 at 12-36-30 Food Ordering Website](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126962453/88c66a66-5354-475f-8a4a-737beb90dfb8)

2.  **Enhancement of Navigation Bar**  

-   Nav bar can be made to suit the theme of the webpage by employing glass morphism
-   This will give it a modern and sleek appearance.
-   Elements of Nav bar needs to be Receptive.

**Comment by khushi-joshi-05** [comment]
@abhinandan202004 I have assigned you these issues. I was about to create an issue regarding the same. Go ahead, looking for the best results.
Also if u will attach the screenshot after resolving issues, it will be easier to understand.

**Comment by abhinandan202004** [comment]
@khushi-joshi-05 Thank you, I am working on it and will share screenshot after resolving the issue
