### ISSUE TITLE
adding hovering effect for footer section

### ISSUE THREAD

**Issue by reshamsai150** [khushi-joshi-05/Food-ordering-website#338]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/164533685/b51b74c2-1d15-4fc9-b487-41e6f13c4b86)
the footer section is static i want to add a hovering effect in the footer section 
for icons as well as the headings to make the footer section more attractive assign this issue to me @khushi-joshi-05

**Comment by curecode11** [comment]
@khushi-joshi-05 please assign the above mentioned task to me.

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @khushi-joshi-05  under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
