### ISSUE TITLE
update the home page 

### ISSUE THREAD

**Issue by reshamsai150** [khushi-joshi-05/Food-ordering-website#339]
some features need to be added for the home page change its UI 
assign this issue to me @khushi-joshi-05

**Comment by sunny0625** [comment]
@reshamsai150 Describe the changes you want on home page.

**Comment by reshamsai150** [comment]
I want to add some animations to the homepage also change the typography and change the color of order now button 
, log in, and signup button color as these buttons do not match with the home page theme 
Assign this issue to me @khushi-joshi-05
