### ISSUE TITLE
add images in app delivery section 

### ISSUE THREAD

**Issue by Ridhima10** [khushi-joshi-05/Food-ordering-website#34]
Hey, I am contributing under GSSoc'24
i would like to add  images of phones in app delivery section to make it more appealing.
since the background of this section and footer is same. So it is not that eye catching.
I will change the background and add images
![Screenshot 2024-05-09 235925](https://github.com/khushi-joshi-05/Food-ordering-website/assets/85826117/d9338503-a787-4078-8219-2e09248559c2)

Please assign me this issue
Best regards.

**Comment by Mohammed-790** [comment]
Please assign this issue to me sir i will give my best

**Comment by aashkaaaaaa** [comment]
i want working of this issue, please assign me

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
