### ISSUE TITLE
Buttons in Footer Section not working

### ISSUE THREAD

**Issue by kdanjana** [khushi-joshi-05/Food-ordering-website#342]
In footer section of all pages - home,menu,service,contact - these should be buttons or links which when clicked should direct to respective pages.  This is not happening right now .
<img width="633" alt="sthg" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/103878831/4b6dd077-0aef-483c-af1e-3563c7bae6c0">
To achieve a flow in the website and to make all pages part of website, I would create a base.html which contains header and footer sections which are part of all pages. 
Please assign it to me.
GSSOC 2024

**Comment by Riyasharma28** [comment]
Kindly assign me @Riyasharma28 under GSSOC'24
