### ISSUE TITLE
 I noticed a issue that every single page opens in a new tab which shouldnt be happening . it should open in the same page instead of a new tab

### ISSUE THREAD

**Issue by AtulYadavCodes** [khushi-joshi-05/Food-ordering-website#343]
hey I noticed a issue that every single page opens in a new tab which shouldnt be happening . it should open in the same page instead of a new tab.
i would like to work on this issue and make sure that the links dont open in new tab .
please assign this to me under gssoc 24 @khushi-joshi-05

**Comment by AtulYadavCodes** [comment]
@khushi-joshi-05 can you please look into this

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
