### ISSUE TITLE
Adding a scroll to top button

### ISSUE THREAD

**Issue by pani2004** [khushi-joshi-05/Food-ordering-website#344]
I can add a scroll to top button in the home page.
![Screenshot (28)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154724111/4ff85508-69f2-400c-8d26-2f2df60d9993)

**Comment by pani2004** [comment]
@sunny0625 can u assign this to me?

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
