### ISSUE TITLE
Fix images of menu

### ISSUE THREAD

**Issue by Ridhima10** [khushi-joshi-05/Food-ordering-website#35]
Hey i am contributing under GSSoc'24
The images in menu section are stretching. I will fix them to enhance the UI of the website. 
I will also add hover effect to make it more interactive

![Screenshot 2024-05-10 000802](https://github.com/khushi-joshi-05/Food-ordering-website/assets/85826117/823e8f2f-a365-49d9-ab75-5a461a129a3a)

Please assign me this issue
Best regards.

**Comment by nishant0708** [comment]
please assign me this issue

**Comment by Ridhima10** [comment]
Please assign me this issue since I have raised the issue and I have understood your project with details

**Comment by Ridhima10** [comment]
@khushi-joshi-05  Kindly review this.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
