### ISSUE TITLE
Making Menu page responsive

### ISSUE THREAD

**Issue by saketh-05** [khushi-joshi-05/Food-ordering-website#350]
- I want to make Menu page responsive, so that it will have better look for users from mobile devices.
- I will make changes to Title of the page also.
- This will bring more modern and attractive appearance.
![Screenshot 2024-05-14 171910](https://github.com/khushi-joshi-05/Food-ordering-website/assets/134281589/c716de37-1cc7-40f8-874b-46a8c06fcde6)

So please assign me this work.

**Comment by Sudharshana426** [comment]
I would love to work on this project. Could you assign me this task for better grid implementation, responsive web design and CSS styles for the issue? I have worked on multiple projects. Check out my LinkedIn Profile: https://www.linkedin.com/in/sudharshanab
