### ISSUE TITLE
Stick nav bar

### ISSUE THREAD

**Issue by Kalyan9064** [khushi-joshi-05/Food-ordering-website#354]
we have to stick the Navbar, for bater user experience and easy to access- Home, Menu, Service, Contact us, Cart

Hey 
Project Admin: Khushi
Assign me this issue, i can fixed it
![Uploading Screenshot 2024-05-14 191012.png…]()

**Comment by Kalyan9064** [comment]
Assign me this issue

**Comment by dakshika-chaudhary** [comment]
please assign this issue to me @khushi-joshi-05

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @khushi-joshi-05  under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
