### ISSUE TITLE
Login/Signup page could really use some work.

### ISSUE THREAD

**Issue by pahuja-sahil** [khushi-joshi-05/Food-ordering-website#356]
Hello @khushi-joshi-05 , The signup and login page are quite  mediocre and could really use some work. they dont even match the color pallete of the entire website and there is also spelling error on sign up page.

*You can see in the picture below.*

![image_2024-05-14_192212486](https://github.com/khushi-joshi-05/Food-ordering-website/assets/140882358/4e27d493-6fa2-46d1-9297-97e56febb55f)

I kindly request you to assign this issue to me under GSSoC'24 level2 . I can customise this login and signup page in no time and the work will be better than the existing page.

**Comment by Riyasharma28** [comment]
Kindly assign me @Riyasharma28 under GSSOC'24

**Comment by sunny0625** [comment]
@pahuja-sahil Describe how would you want to contribute to this issue.

**Comment by pahuja-sahil** [comment]
@sunny0625 I would like to redesign the login and sign up page so the the background match with the foodie website and also there is a spelling error in the text written on the signup page as you can see in the above screen shot taken by it. 
The page would look good if the background image is of some food type with blur effect and the login and sign up card are aligned in the center. 
Kindly consider this if possible and assign me this issue under GSSoC'24
Thank you.
