### ISSUE TITLE
Changing the logo of Twitter

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#358]
As the new logo of twitter in updated. I want edit it to new logo 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/7c4b59db-de86-4a45-a64f-5b5ae8a92d8c)
The new logo is 
![Screenshot 2024-05-14 131642](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/fc92da39-f164-4e40-8f2f-a3827355e38d)
Please @khushi-joshi-05 mam assign this issue to me under GSSoC'24.

**Comment by Amanjaiiinnn** [comment]
I have changes the logo for bird to X . please assign me this

**Comment by Gultreen** [comment]
please assign me this issue Mam
