### ISSUE TITLE
UI of Contact Us page does not matches to the theme

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#360]
UI of Contact Us page does not matches with the website theme. Please assign this issue to me under GSSoC'24.

**Comment by sunny0625** [comment]
@TBorundia work on this issue. Make responsive as well.

**Comment by Nih1tGupta** [comment]
@sunny0625  ,I want to wok on this issue.
Please assign this to me.
  I will  improve button, hovering effect and add  a background image .

**Comment by SamarupBhattacharya** [comment]
@sunny0625 Making the contact page for the website was one of the first issues that was resolved in this repo. I had solved the issue and had created a responsive Contact page under issue #150. I had saved the code for my page in the file **contact_GSSoC_contriburted.html** . However, this file was never linked with the main website.

 I am attaching a screen recording of the webpage that I had made

https://github.com/khushi-joshi-05/Food-ordering-website/assets/138982308/97b1afa3-1ce0-4e3c-913b-9c9d8a08dd5d

Please assign me this issue so that I can link this page to the main website and solve this issue once and for all.

Thanks

**Comment by Bhavishya2601** [comment]
@khushi-joshi-05 
I want to work on this issue with my expertize in web development, I think, i am the best fit for this issue
I think so, it should look something like this which gives it a professional look

![Screenshot 2024-05-18 234044](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147748752/6da3cf7c-9e46-4768-b69d-26c7f088f359)
Hope you would assign this task to me

**Comment by dakshika-chaudhary** [comment]
@khushi-joshi-05  ,I have already worked on Tailwind CSS projects ,due to which i have a good experience of UI designing .
Kindly assign it to me so that i can make it more attractive and eye catchy.

**Comment by sunny0625** [comment]
@khushi-joshi-05 check which layout you will go..!

**Comment by numitasahu** [comment]
**issue**

- UI of Contact Us page does not matches with the website theme.
**solution**

- If the Contact Us page header is the same as the home or menu page and a transition is applied to the form box on the Contact Us page and the send button is edited slightly, the theme could match.


** Are you contributing under any open-source program ?**

- Yes, GSSOC'24.

**@khushi-joshi-05 please assign me this issue , resolving it would increase attractiveness and look good.**

**Comment by numitasahu** [comment]
I tried to solve this issue and edit contact page . I hope you like it .

![Uploading contact.png…]()

@khushi-joshi-05 please assign me this issue , resolving it would increase attractiveness and look good.

**Comment by numitasahu** [comment]
I tried to solve this issue and edit contact page . I hope you like it .

![contact](https://github.com/khushi-joshi-05/Food-ordering-website/assets/148805208/4a39fbca-fb37-471a-bdd3-a5b92d646875)

@khushi-joshi-05 please assign me this issue , resolving it would increase attractiveness and look good.

**Comment by Bhavishya2601** [comment]
> @khushi-joshi-05 I want to work on this issue with my expertize in web development, I think, i am the best fit for this issue I think so, it should look something like this which gives it a professional look
> 
> ![Screenshot 2024-05-18 234044](https://private-user-images.githubusercontent.com/147748752/331885584-6da3cf7c-9e46-4768-b69d-26c7f088f359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjIwMDksIm5iZiI6MTcxNjcyMTcwOSwicGF0aCI6Ii8xNDc3NDg3NTIvMzMxODg1NTg0LTZkYTNjZjdjLTllNDYtNDc2OC1iNjlkLTI2YzdmMDg4ZjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMTA4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWZjNTBmNDI1YmY2NmM5ZmMzMzNjNjNlNTJjYzgzZDhmZjI5ODg2ZjA2ZWE4NGM0MjcyNGUyNzc5NWQxMTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RL35SEbvCixowX6khcoMGnkvV3G7DiEYaPOOo_o1dc0) Hope you would assign this task to me

Hope you would assign this issue
With addition to this, we can add a banner at the top of this 
and can also embed location using google maps.

**Comment by Tarungupta18** [comment]
please assign me this issue
