### ISSUE TITLE
About us Section RESPONSIVENESS

### ISSUE THREAD

**Issue by mohitrajjha111** [khushi-joshi-05/Food-ordering-website#361]
PROBLEM:
About us section is not responsive and  have problems in it

![responsiveproblem_to send](https://github.com/khushi-joshi-05/Food-ordering-website/assets/125960660/6f84ee57-c6dc-4a65-8245-3734df6d9162)

My Solution:
Create Wireframe first 
Apply it on about us section
Customise images
Improve CSS properties used

@khushi-joshi-05  Please assign it to me under label GSSoC'24.
Thank you

**Comment by mohitrajjha111** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/pull/362

**Comment by mohitrajjha111** [comment]
@khushi-joshi-05

**Comment by dakshika-chaudhary** [comment]
I would love to apply my skills to it to make it responsive ,please assign this issue to me
@khushi-joshi-05
