### ISSUE TITLE
Links Opening in New Tabs

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#364]
Currently, every link on the website is set to open in a new tab, which can disrupt the user experience and cause confusion. Links should ideally open in the same tab unless specified otherwise. This issue needs to be addressed to ensure a smoother browsing experience for users.

I am a GSSOC'24 Contributor. Please assign this issue to me as this issue need to be addressed as soon as possible.

**Comment by Ansh101112** [comment]
@khushi-joshi-05 ma'am please assign me this issue

**Comment by sunny0625** [comment]
@jency1 work on this issue

**Comment by jency1** [comment]
> > @jency1 work on this issue
> 
> Sir please assign me too
