### ISSUE TITLE
Improve Cards

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#368]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/bae38732-0402-4dd4-83f4-a96dd286a889)

Improve the cards and add a counter feature to them. Also these cards not working if clicking on order now.
As I mentioned earlier this issue is for @K-Svayam05.

**Comment by SamarupBhattacharya** [comment]
I want to do it, please assign this to me

**Comment by K-Svayam05** [comment]
> ![image](https://private-user-images.githubusercontent.com/76521579/330669133-bae38732-0402-4dd4-83f4-a96dd286a889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTQ5NzUsIm5iZiI6MTcxNTc1NDY3NSwicGF0aCI6Ii83NjUyMTU3OS8zMzA2NjkxMzMtYmFlMzg3MzItMDQwMi00ZGQ0LTgzZjQtYTk2ZGQyODZhODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MzExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjZkYmU4Nzk1NTUwY2I1MDQ2NDVkZGU5NzE4YjIxNjA5ZmE4MDA3NWI1OTM5NmYwZjY5NmEwZjExNzEyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmBTDNy4hN4wlZaPMN1oFGgP5iGXPCLBrgxaxJksnw0)
> 
> Improve the cards and add a counter feature to them. Also these cards not working if clicking on order now. As I mentioned earlier this issue is for @K-Svayam05.

On it!
Would you assign the issue to me officially.

**Comment by K-Svayam05** [comment]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/141111900/60da250b-dfb8-42f2-9f82-c83f300498b8)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/141111900/e0fb6a30-118c-4d2c-85cd-af73dc8a4e2e)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/141111900/412a1f44-d60a-48cb-919a-edf3aac95fcf)

@sunny0625 
I have made the necessary changes in the appearance of the cards, the add to cart button by incrementing/decrementing the quantity as well as linking the Order Now button with the Cart page.
Should I issue a Pull request?

**Comment by K-Svayam05** [comment]
I have sent the Pull Request to merge the branch, Do check it out and please tag if changes required!
Thank You.

**Comment by harshcodesit** [comment]
hey @sunny0625 
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, and make immersive cards.

Please assign this task to me, GSSOC'24 .

**Comment by sunny0625** [comment]
> I have sent the Pull Request to merge the branch, Do check it out and please tag if changes required! Thank You.



> I have sent the Pull Request to merge the branch, Do check it out and please tag if changes required! Thank You.

Mention PR here!

**Comment by K-Svayam05** [comment]
> > I have sent the Pull Request to merge the branch, Do check it out and please tag if changes required! Thank You.
> 
> > I have sent the Pull Request to merge the branch, Do check it out and please tag if changes required! Thank You.
> 
> Mention PR here!

I have sent a Pull request solving all the conflicts
Pull request:  #386 Fixed issue Improve Cards#368: Improved the cards of Menu page, added…
