### ISSUE TITLE
Links not working in the footer section.

### ISSUE THREAD

**Issue by kdanjana** [khushi-joshi-05/Food-ordering-website#369]
In menu.html and services.html  the links in footer section 
<img width="100" alt="links" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/103878831/f255b0b6-06d6-4ebf-a255-0278361efae4">
they are linked to their respective pages.
Please assign this to me .
GSSOC24

**Comment by kdanjana** [comment]
The social media links are also not working on these pages. Please assign this issue to me .

**Comment by dakshika-chaudhary** [comment]
please assign this issue to me.

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @khushi-joshi-05  under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.

**Comment by lovelymahor** [comment]
I would like to work on this issue Can u please assign me this issue

**Comment by praveen30021** [comment]
I'm looking forward to work on this issue @khushi-joshi-05 under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
