### ISSUE TITLE
Include the Locomotive JS-For smooth scrolling

### ISSUE THREAD

**Issue by suraj-9849** [khushi-joshi-05/Food-ordering-website#37]
I saw that the website is not smooth in scrolling so I thought of using the Locomotive js which can enhance the website smoothness and make the user feel good. So I would like to work on this issue. So please assign this to me under @GSSOC'24
@khushi-joshi-05

**Comment by parth3083** [comment]
Hey, I am a frontend developer who creates stunning and modern websites.
I completed the internship as a frontend developer.
I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling.
The following are the works where I used lgsap animation and locomotive js : 
https://exoape-clone-parth.netlify.app/
https://ochi-clone-parth.netlify.app/
