### ISSUE TITLE
Create Discount feature in Cart page.

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#370]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/ba59c83a-0091-48c4-aeaa-57fcfc5a6658)
I want a feature on my cart page. If the user orders the first time then a random coupon code is generated and the user should get 30% discount on the total billing amount.

@Ansh101112 would you want to try this issue?

**Comment by sunny0625** [comment]
Others Contributors are also welcome..!

**Comment by Ansh101112** [comment]
> Others Contributors are also welcome..!

Sure I would like to work on this issue please assign me.

**Comment by SamarupBhattacharya** [comment]
I would like to do it too

**Comment by Ansh101112** [comment]
> > Others Contributors are also welcome..!
> 
> Sure I would like to work on this issue please assign me @sunny0625 @khushi-joshi-05

**Comment by Ansh101112** [comment]
@sunny0625 sir please see the PR #377 @khushi-joshi-05

**Comment by vandana79039** [comment]
hi, I am vandana kumari GSSOC'24 Contributor.
Could you please assign this task to me.
i would like to create discount feature in cart page.

**Comment by Ansh101112** [comment]
> hi, I am vandana kumari GSSOC'24 Contributor.
> Could you please assign this task to me.
> i would like to create discount feature in cart page.
> 
> 

Hello @vandana79039 👋 this issue is already assigned and a PR is already added please refer any other issue.
