### ISSUE TITLE
Adding the GSAP-Animation for the website 

### ISSUE THREAD

**Issue by suraj-9849** [khushi-joshi-05/Food-ordering-website#38]
I thought of adding the best animation to the website by using the GSAP library. This can be used to enhance the user experience and make the user visit the website many times. So I would like to work on this. Can you please assign this to me under @GSSOC'24 @khushi-joshi-05

**Comment by parth3083** [comment]
Hey, I am a frontend developer who creates stunning and modern websites.
I completed the internship as a frontend developer.
I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling.
The following are the works where I used lgsap animation and locomotive js : 
https://exoape-clone-parth.netlify.app/
https://ochi-clone-parth.netlify.app/
