### ISSUE TITLE
Improving the nav bar hover effect

### ISSUE THREAD

**Issue by Manishar55** [khushi-joshi-05/Food-ordering-website#382]
Hii @khushi-joshi-05 
The color of hover effect in the nav bar is mixing with the background which is not looking good I  want to improve the hover effect 
of the nav items
Can you please assign this task to me under gssoc24

![Screenshot 2024-05-16 165527](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154615478/9bdd921c-5fde-46cb-855b-80e8edf5ed68)

**Comment by debiprasannadash** [comment]
@khushi-joshi-05 Please assign this issue to me since I have the good knowledge of HTML and CSS and can apply the hover effect on the navBar .
Please do so. Since I haven't received a single issue in gssoc 24.

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @khushi-joshi-05 under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
