### ISSUE TITLE
Adding icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [khushi-joshi-05/Food-ordering-website#39]
I've noticed an opportunity to enhance user experience by incorporating icons into the navigation bar. This proposal suggests the addition of intuitive icons alongside existing text labels in the navbar to facilitate quicker navigation and improve visual appeal. Could you please assign me this issue under GSSOC'24

**Comment by Prakhar-bansal1** [comment]
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..

**Comment by KunjMaheshwari** [comment]
@harshmishra19 Please can you assign this issue to me? I am good at Frontend and this would be my first time to contribute in open source.

**Comment by Suvam3456** [comment]
I can easily do this , I have good experience in front-end , @khushi-joshi-05 Please assign me this issue

**Comment by Dhack29** [comment]
@khushi-joshi-05 i already worked food website project. Please assign this issue to me.

**Comment by GuptaKap** [comment]
I have experience in frontend work and I'm interested. Please assign me @khushi-joshi-05 .

**Comment by sejal-sharma08** [comment]
@khushi-joshi-05  Please assign me this task as I have already made a project in food ordering website and have the knowledge to do the same.  It will be my pleasure if you choose to trust me for working in this issue

**Comment by Deepak492001** [comment]
I'm eager to contribute by adding clear navbar icons to improve user experience. Can I take on this issue?
