### ISSUE TITLE
Add Favicon to website

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#394]
Add a favicon to the website to enhance user experience and improve site branding. A favicon is the small icon displayed in browser tabs, bookmarks, and other places where the website's identity is represented.

Adding a favicon to our website will:

1. Enhance brand recognition.
2. Improve user experience.
3. Provide a more professional appearance.

I am a GSSOC'24 contributor. Please assign this issue to me.

@sunny0625 @sanjay-kv  @khushi-joshi-05

**Comment by Ansh101112** [comment]
@khushi-joshi-05 please assign me this issue @sunny0625

**Comment by sunny0625** [comment]
@jency1 work on this issue!

**Comment by sunny0625** [comment]
Describe your contribution.

**Comment by Nih1tGupta** [comment]
![FOODY](https://github.com/khushi-joshi-05/Food-ordering-website/assets/119615342/e61fb22a-a30d-40a5-824c-bcb0206ceef4)
Can i use this?
Please assign this to me

**Comment by Ansh101112** [comment]
> Describe your contribution.

Please assign me this issue

**Comment by jency1** [comment]
> Describe your contribution.

I addressed and resolved bug #364, which pertained to the issue where all hyperlinks were being opened in a new tab, regardless of context or necessity. 

By resolving this bug, the website now provides a smoother and more intuitive navigation experience for users, improving overall usability and adherence to web standards.

I also have experience adding favicons to websites and would like to take on this task. 
I am confident in my ability to complete this task efficiently and would appreciate the opportunity to contribute further to the project by adding the favicon.  @sunny0625

**Comment by jency1** [comment]
> Describe your contribution.

Can I start working on this issue? @sunny0625

**Comment by sunny0625** [comment]
@jency1 start on this issue!

**Comment by jency1** [comment]
> @jency1 start on this issue!

Thanks for assigning this issue to me.

Should I add this image? - [Favicon Image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/94179142-c479-4cec-b57c-f6df4af09153)
