### ISSUE TITLE
[New Feature]: Size of Text box is small.

### ISSUE THREAD

**Issue by crparse** [khushi-joshi-05/Food-ordering-website#398]
The of text box is little is small we can modify it into bigger one & also can add new feature if a mssg is sent by user there should be pop on screen that "Mssg has been sent sucessfully " kind of type.
 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/98864892/e7564a41-0b7d-422b-8c59-2d119a3e04cc)

**Comment by crparse** [comment]
@khushi-joshi-05 please allow me to resolve this error to add the new feature.

**Comment by Rishitatripathi** [comment]
I would like to work on this issue, Please assign it to me under GSSOC 2024
