### ISSUE TITLE
Enhancement in Footer Section

### ISSUE THREAD

**Issue by imanasdash** [khushi-joshi-05/Food-ordering-website#40]
footter Section need to be in black background color , slight modification in text in footer . Please assign me under Gssoc'24 .

**Comment by Nayanika1402** [comment]
The footer section needs advancement in many places like the enhancement  of the styling,adding a bit of hover effect ,and definetely changing the font of the texts.Basically I want to upgrade the footer to a much user-friendly and attractive one.

**Comment by Nayanika1402** [comment]
The footer section needs advancement in many places like the enhancement of the styling,adding a bit of hover effect ,and definetely changing the font of the texts.Basically I want to upgrade the footer to a much user-friendly and attractive one.Please assign me this task @khushi-joshi-05 .

**Comment by Sayali-tech853** [comment]
Hi, can you please assign this issue for me under GSSOC'24 @khushi-joshi-05 

I will improve the footer Where 'our pages' are not clickable 
![Screenshot 2024-05-10 151309](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115891685/4fe039a9-cabb-41a7-a46f-cd6ed131be84)

**Comment by sunny0625** [comment]
@imanasdash Describe how you want to contribute to this issue..!
