### ISSUE TITLE
Create "Book Table" page

### ISSUE THREAD

**Issue by pulkitgarg04** [khushi-joshi-05/Food-ordering-website#407]
Hi @khushi-joshi-05 and @sunny0625, I noticed that there is no book table page on the website. I would like to add a Book Table page to your website.

Please assign me this issue under GSSOC'24.

**Comment by dakshika-chaudhary** [comment]
Adding a book table feature would make it more interesting and i would love to add this feature by using my MERN skill.
Kindly assign it to me
