### ISSUE TITLE
Menu page not responsive

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [khushi-joshi-05/Food-ordering-website#408]
![Screenshot_20240520_110612_Chrome](https://github.com/khushi-joshi-05/Food-ordering-website/assets/139672976/bf9d422f-61c3-43be-8579-8791700f55ee)

Please assign this issue to me under Gssoc'24 to solve the issue.

**Comment by dakshika-chaudhary** [comment]
I am a MERN stack devloper and I would love to add my skills to this and make it more attractive,
kindly assign this issue to me
