### ISSUE TITLE
Quick Links in Footer Section Not Working

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#410]
The quick links in the footer section of the website are currently not functioning. This issue affects the following links:

1. Menu
2. Services
3. Contact Us
4. Cart

When users click on these links, they do not redirect to the appropriate sections or pages. This is impacting the user experience as it prevents easy navigation to important parts of the site.

I'm GSSOC'24 contributor. Please assign this issue to me so I can resolve it as soon as possible.
@khushi-joshi-05 @sunny0625

**Comment by sunny0625** [comment]
This issue has been solved, Try to participate in different issue!
