### ISSUE TITLE
 Hover Color on Links Matches Background Color on Home Page

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#411]
There is an issue with the hover color for links on the home page. When users hover over the links, the color changes to match the background color, making the links invisible and negatively impacting the user experience.

Issue (example) : [Hover Color Matches the background color](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/00ce5bfb-39af-4ad2-9134-ef5ab74aeabc)

Please assign this issue to me so I can solve this as it makes the links invisible.

**Comment by dakshika-chaudhary** [comment]
I would love to give it an impactful effect by using Tailwind CSS.
please assign it to me

**Comment by jency1** [comment]
@khushi-joshi-05 @sunny0625 Thanks for merging this PR. 

Please change the level form level1 to level2 as I have solved the conflict issues and all other issues 6-7 times. And it was all due to the merging of other PR's and not mine. So please consider this and change the level label as soon as possible. 

Thank you.
