### ISSUE TITLE
Place Google play and App store button properly 

### ISSUE THREAD

**Issue by VK-1662004** [khushi-joshi-05/Food-ordering-website#418]
![Screenshot 2024-05-21 191840](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121168967/bb02a990-1ee2-42e1-a0a0-b45b64c94f83)

**Comment by VK-1662004** [comment]
Could you please assign me this task, I'm confident I can help.

**Comment by Hanshika248** [comment]
please assign me the issue
