### ISSUE TITLE
[Enchantment]: Overlapping Content and Contact us section

### ISSUE THREAD

**Issue by theeayushkumar** [khushi-joshi-05/Food-ordering-website#419]
Confusing overlaps exist: "Free Delivery" on the basket icon and app store badge text on the badge itself.
Fix: Increase spacing or change layout for a cleaner look.
Contact us can be improved: Add phone number, address, or even live chat for real-time interaction.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128235540/a3c4f988-fe85-4992-bf8e-8747a29aff66)

**Comment by Hanshika248** [comment]
Please assign me the issue. I want to contribute to the project

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
