### ISSUE TITLE
Adding new tool

### ISSUE THREAD

**Issue by Vidushi736** [khushi-joshi-05/Food-ordering-website#422]
![Screenshot 2024-05-21 214015](https://github.com/khushi-joshi-05/Food-ordering-website/assets/146731374/678d5c68-08b7-4897-9368-37b799b8ba14)

adding a forgot password and reset password tab can help users to login to their account easily without relying on login with google option 
login with google option sometimes causes a lot of problem for users to login due to its two factor authentication seetting

**Comment by Vidushi736** [comment]
please assign this issue to me so that i can add a forgot password link

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
