### ISSUE TITLE
Year needs to update dynamic in footer 

### ISSUE THREAD

**Issue by kapilG0** [khushi-joshi-05/Food-ordering-website#425]
![Screenshot_20240522_125724](https://github.com/khushi-joshi-05/Food-ordering-website/assets/59639410/b5d8c842-b4c3-47a3-93ff-aa10b4bba6fc)

**Comment by kapilG0** [comment]
Hello @khushi-joshi-05 please assign this issue to me under gssoc

**Comment by arpit4521** [comment]
@khushi-joshi-05 please assign me this issue so that i can fix this bug under gssoc label

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
