### ISSUE TITLE
Service page needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [khushi-joshi-05/Food-ordering-website#428]
![Screenshot_20240522_130239](https://github.com/khushi-joshi-05/Food-ordering-website/assets/59639410/275be28b-b933-48d4-8316-fddc16566f6b)

**Comment by kapilG0** [comment]
Hello @khushi-joshi-05 please assign this issue to me under gssoc 24

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
