### ISSUE TITLE
Fix Anchor Tags in Navbar Not linked Properly 

### ISSUE THREAD

**Issue by Sibam-Paul** [khushi-joshi-05/Food-ordering-website#43]
### The anchor tags which are the Home , Menu , Services, Contact Us, Cart not linked properly in frontend and also in backend

![Homeissue](https://github.com/khushi-joshi-05/Food-ordering-website/assets/158052549/602c3602-dee4-4f71-b919-29b0d99a9115)
**Navigating to the site on clicking home ,cart i.e the options in the navbar **
![2024-05-10 09_12_27-Window](https://github.com/khushi-joshi-05/Food-ordering-website/assets/158052549/6186e587-80ca-432b-8f85-93a41fb4a6c7)
**This is Showing error is no presence of content folder in the code **

So I can fix :- 
Linking of the page present in the navbar 

Please do assign me this issue so that I can work on this under GSSOC'24

**Comment by KunjMaheshwari** [comment]
@Sibam-Paul Please can you assign this issue to me?

**Comment by Deepak492001** [comment]
@khushi-joshi-05  I have solved your issue, you can assign me this issue so that I can commit all the changes.

**Comment by Sibam-Paul** [comment]
@khushi-joshi-05 According to the issue I raised 

> ### The anchor tags which are the Home , Menu , Services, Contact Us, Cart not linked properly in frontend and also in backend
> ![Homeissue](https://private-user-images.githubusercontent.com/158052549/329450404-602c3602-dee4-4f71-b919-29b0d99a9115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTI1MjMsIm5iZiI6MTcxNTM1MjIyMywicGF0aCI6Ii8xNTgwNTI1NDkvMzI5NDUwNDA0LTYwMmMzNjAyLWRlZTQtNGY3MS1iOTE5LTI5YjBkOTlhOTExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNDQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzViOGE0OGJmYzExMDE4NTNkN2JkNjc5NDAyNWE4NTRkMjdlN2Y5Njk5ZWE5ODE0ZmYxNDY5NjQ5MzIxNWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cK4WqoAAIw3d8_9tKLw2jNS9c6ZowiLwsoKAMUjRcY0) **Navigating to the site on clicking home ,cart i.e the options in the navbar ** ![2024-05-10 09_12_27-Window](https://private-user-images.githubusercontent.com/158052549/329450618-6186e587-80ca-432b-8f85-93a41fb4a6c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTI1MjMsIm5iZiI6MTcxNTM1MjIyMywicGF0aCI6Ii8xNTgwNTI1NDkvMzI5NDUwNjE4LTYxODZlNTg3LTgwY2EtNDMyYi04Zjg1LTkzYTQxZmI0YTZjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNDQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzhmODZiMDljNTg0MWZhMGRlNmZhODM2Y2JkMzBhZDk5ZDk5MDRmNWNjOTE2ZGE2NWExMmE3MDMxMzgwYmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FK-LwQfddaHPb2vY1vIuzB5_h-ez4-1rKGXnLmhp2us) **This is Showing error is no presence of content folder in the code **
> 
> So I can fix :- Linking of the page present in the navbar
> 
> Please do assign me this issue so that I can work on this under GSSOC'24

**Comment by Sibam-Paul** [comment]
@khushi-joshi-05  Hey with the error mentioned earlier I have corrected the error . 
**Please do assign me so that I can do pull request **

**Comment by Sibam-Paul** [comment]
@sunny0625 please assign me this issue

**Comment by sunny0625** [comment]
This issue has been solved, Try to participate in different issue!
