### ISSUE TITLE
Change the UI of the Contact us page

### ISSUE THREAD

**Issue by Bhavishya2601** [khushi-joshi-05/Food-ordering-website#431]
The UI of the contact page is not the best and needs a upgrade

I wanna make it something like this
![Screenshot 2024-05-22 133655](https://github.com/khushi-joshi-05/Food-ordering-website/assets/147748752/f41daeba-6045-4e8c-94a5-a16f8d04bab8)

And after that we can also embed a map

Hope you would assign this task to me under gssoc

**Comment by sunny0625** [comment]
Check according to the latest updates!
