### ISSUE TITLE
Consistent hover effect for all social media icons in footer

### ISSUE THREAD

**Issue by pulkitgarg04** [khushi-joshi-05/Food-ordering-website#436]
Hey @khushi-joshi-05 and @sunny0625, I noticed that social media icons and their hover effects are inconsistent.
For example:
1. On Homepage
![1](https://github.com/khushi-joshi-05/Food-ordering-website/assets/87312278/aed07944-8514-46a7-b418-74479c62998f)

2. On Menu page
![2](https://github.com/khushi-joshi-05/Food-ordering-website/assets/87312278/4efdb1ce-7ad7-4f81-8f7c-14feaed9410a)

3. On Contact page
![3](https://github.com/khushi-joshi-05/Food-ordering-website/assets/87312278/c8a75c0d-15a9-4280-846a-4d51c1c137ae)

I want to make them look same so that the UI of the website remains consistent.

Please assign me this issue under GSSoC'24

**Comment by mtg718** [comment]
Please assign me this issue under GSSoC'24

**Comment by Anupsimha** [comment]
Well, I am ready to Solve This Bug, If You assign This Task To me!!

**Comment by Hanshika248** [comment]
Please assign me the issue I want to work on the issue

**Comment by GSGore** [comment]
I have fixed this issue.#436

**Comment by GSGore** [comment]
@sunny0625 i have fixed this.
