### ISSUE TITLE
Add back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [khushi-joshi-05/Food-ordering-website#438]
Hey, @khushi-joshi-05 I would like to add the back to top button which is missing in this website.
I am working under GSSoC'24
Please assign this task to me.

**Comment by siya25097** [comment]
Hey @khushi-joshi-05,

I noticed the "back to top" button is missing from the Foodie website. I would love to add this feature as part of my contribution to GSSoC'24. Could you please assign this task to me?

Thank you!

**Comment by sunny0625** [comment]
@Saimanjari777 yeah back to top btn is only applied on the home page.
Try to apply on all web pages.
