### ISSUE TITLE
Social media icon should be clickable  

### ISSUE THREAD

**Issue by u-s-h-a** [khushi-joshi-05/Food-ordering-website#44]
social media handles should be clickable and should be redirected to that particular platform

**Comment by u-s-h-a** [comment]
please assign me this issue i will makes those changes so that your website will become more interactive with other platform

**Comment by aditi1807** [comment]
Please assign me this issue as i can resolve it

**Comment by mrskjha** [comment]
@khushi-joshi-05 pls assign me for this issue i can do this. this is my first open source contribution so pls assign me

**Comment by SIM-RAITANI** [comment]
Could you please assign me this issue . I can resolve the issue you mentioned.

**Comment by shreyanssatpute** [comment]
@khushi-joshi-05  please allot me this issue I will resolve it as needed

**Comment by Deepak492001** [comment]
@khushi-joshi-05  please provide me with your various social media links so that, I can resolve this issue.

**Comment by HarshSDE0** [comment]
Hey there! I'm Harsh Abhishek from #GSSOC 2024 please assign me this issue. I'm a MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,java.
Sample Live project link: https://harshsde0.github.io/1-1personaltraining/
LinkedIn profile: https://www.linkedin.com/in/harsh-abhishek-463359222/
