### ISSUE TITLE
Adding subtle scroll animations.

### ISSUE THREAD

**Issue by yashi-15** [khushi-joshi-05/Food-ordering-website#451]
It is a feature request where I would like to make the website look more modern and engaging.
I want to incorporate smooth and subtle scroll animation effects for the website elements. These elements will seamlessly appear as you scroll through the page.

Kindly assign this issue to me under GSSOC'24, so that I can start working on it.

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 Implementing smooth scroll animations will elevate the visual appeal and user engagement of the website, making it feel more modern and interactive. These subtle animations will dynamically appear as users scroll through the page, adding a touch of elegance to the overall design. Please assign this task to me for implementation.
