### ISSUE TITLE
Content is overlapping at footer of main web page

### ISSUE THREAD

**Issue by suhanigupta23** [khushi-joshi-05/Food-ordering-website#452]
The content is overlapping for the footer section.
<img width="1440" alt="Screenshot 2024-05-23 at 7 14 00 PM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/22f9b2a6-55df-4875-b8a0-cf0797af6573">

**Comment by suhanigupta23** [comment]
Please assign this issue to me under the gssoc'24 .

**Comment by Anupsimha** [comment]
Please Assign Me This Task!!
