### ISSUE TITLE
Inconsistent Box Sizes and Misaligned Text Content

### ISSUE THREAD

**Issue by tanya-54** [khushi-joshi-05/Food-ordering-website#455]
Description:
There are several layout and alignment issues on the webpage. The boxes labeled "Online Delivery," "Click and Collect," and "Restaurant Dining" have irregular sizes, leading to a visually unappealing and disjointed user experience. Additionally, the text content on the left side of the page is not displayed in a continuous manner, which further contributes to the layout inconsistency.

Expected Behavior:
Uniform Box Sizes:

All boxes for "Online Delivery," "Click and Collect," and "Restaurant Dining" should have the same width and height.
The boxes should be evenly spaced and aligned, creating a clean and organized look.
Continuous and Aligned Text Content:

The text content on the left side of the page should be displayed in a continuous, well-aligned manner.
The text should be easy to read, without any fragmentation or misalignment.

Actual Behavior:
Irregular Box Sizes:

The boxes for "Online Delivery," "Click and Collect," and "Restaurant Dining" have different widths and heights, leading to an inconsistent appearance.
This irregularity disrupts the visual flow and makes the layout look unorganized.

Misaligned Text Content:

The text content on the left side of the page is not displayed in a continuous manner. The lines are fragmented and misaligned, making it difficult to read.
The lack of proper alignment and continuity in the text makes the page look cluttered and unprofessional.

impact:
By addressing these issues, we can create a more visually appealing and user-friendly webpage. The changes will ensure that the box sizes are consistent and the text content is properly aligned, resulting in a professional and organized layout.

proof::
![Screenshot 2024-05-23 214221](https://github.com/khushi-joshi-05/Food-ordering-website/assets/148340088/b0f54aba-c54f-4ad8-a150-201da91ef403)

assign me this issue .@khushi-joshi-05

**Comment by ravijat2026** [comment]
Hello @khushi-joshi-05 Please assign me this issue.
