### ISSUE TITLE
Add "Back to Top" Button at the end of Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [khushi-joshi-05/Food-ordering-website#459]
Describe the feature
The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

**Comment by AsmitaMishra24** [comment]
I would like to address this issue as part of GSSOC'24. Please assign it to me.

**Comment by Anupsimha** [comment]
Please Assign This Issue To Me!!

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 I'd be happy to take on this task for GSSOC24. Adding a "Back to Top" button at the end of the homepage is a great idea for improving user experience. It ensures smooth navigation and allows users to easily return to the top of the page with just one click. I'll make sure to design the button in a visually appealing manner to complement the overall aesthetics of the website. Please assign this task to me, and I'll get started right away!

**Comment by AsmitaMishra24** [comment]
I have raised the issue, so it should be assigned to me first.
