### ISSUE TITLE
Add mini Chat bot 

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [khushi-joshi-05/Food-ordering-website#460]
Add mini chat bot for better experience for user.

here's my previous work

![Screenshot (7)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/75926745/a2d5ff4d-dcb7-47da-a6b7-478f4b88f5fd)
![Screenshot (8)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/75926745/6a15c128-85a2-4a3d-a554-d0fd260b3b3a)

**Comment by khushi-joshi-05** [comment]
@Vaibhav22p-qw I have assigned u the task

**Comment by Vaibhav22p-qw** [comment]
hello @khushi-joshi-05 working on it submitting before 11:00AM
