### ISSUE TITLE
Linking add to cart with the menu section.

### ISSUE THREAD

**Issue by suhanigupta23** [khushi-joshi-05/Food-ordering-website#463]
The items when placed order (clicking on "order now") from menu section can be added to the "add to cart" page . 
Like the given below :
<img width="502" alt="Screenshot 2024-05-24 at 9 03 42 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/09b6f97a-6276-4183-8368-081729557790">

Please assign me this task under Gssoc'24.

**Comment by khushi-joshi-05** [comment]
@suhanigupta23  i have assigned u this issue

**Comment by suhanigupta23** [comment]
Thank You ma'am 🙂. I will try to complete the task in the minimum time
possible.
