### ISSUE TITLE
Apply email validation in the footer to accept only approved domains like .com, .in, etc

### ISSUE THREAD

**Issue by Amruta7203** [khushi-joshi-05/Food-ordering-website#465]
There is no email validation function in the footer which can accept only registered domain emails like .com, .in, .org, etc.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/116087736/c6ef2d84-2086-4300-aaa3-f1521763984d)

**Comment by FaizanAli192** [comment]
It would be great of you if you assign me this issue.
