### ISSUE TITLE
Google auth to the website

### ISSUE THREAD

**Issue by Vishnu1804K** [khushi-joshi-05/Food-ordering-website#47]
I want to implement Google authentication in your website so that it will be easy for the users to do login and signup please assign me this issue under GSSOC'24

**Comment by ayush-kumarrai** [comment]
I can add google authentication to your website, what you have to do is to just assign me the task.

**Comment by Vishnu1804K** [comment]
hey @ayush-kumarrai  it is my issue you raise your own issue

**Comment by ayush-kumarrai** [comment]
okk @Vishnu1804K

**Comment by tusharyadav11** [comment]
would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality

**Comment by khushi-joshi-05** [comment]
@Vishnu1804K  I have assigned u this issue. You can start working on it. All the best.
