### ISSUE TITLE
[Bug]: Issue with the Social Media Icon Spacing

### ISSUE THREAD

**Issue by Samridhi002** [khushi-joshi-05/Food-ordering-website#474]
**Description**
The social media icons ("Facebook", "Instagram" and "Twitter") at the bottom of the "Contact Us" page are placed too close to each other. This makes them appear cluttered and can make it difficult for users to interact with individual icon. Proper spacing between the icons can improve usability and overall aesthetic appeal of footer section.

**Attachment**
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/169380578/edd15631-697b-440c-85ce-b11268f0d9c8)

**Solution** 
It would be better to increase the spacing between the icons to maintain a clean and organized look.

hii PA,
I can solve this issue once you assign to me under GSSoc. Thank You!

**Comment by Jatin-gumber12** [comment]
Hii, please assign this issue to me. I'll apply flex-box and make this icons looks nicely spaced using space-between fix flex-direction - column.
