### ISSUE TITLE
Changing twitter logo in footer section

### ISSUE THREAD

**Issue by harikasayani** [khushi-joshi-05/Food-ordering-website#479]
I am GSSOC'24 Contributor.
I observed that twitter logo is incorrect.
I want to work on this issue.
Please assign me this issue.

**Comment by Gultreen** [comment]
Twitter's abrupt rebrand stems partly from Musk's fondness for the letter X, which has popped up throughout his career.That' the only reason to change the logo . For announcing the change of the Twitter logo in the footer section:

 ->  Update Announcement: We've updated the Twitter logo in our website's footer.

-> Brand Alignment: This change aligns with Twitter's latest branding updates.

-> Stay Current: Ensures our site remains up-to-date with industry standards.
I am a GSSOC'24 contributor . Please @khushi-joshi-05 assign me this task .
