### ISSUE TITLE
Adding login and signup to your website 

### ISSUE THREAD

**Issue by Vishnu1804K** [khushi-joshi-05/Food-ordering-website#48]
I want to implement login and signup functionality so that your website can be used by others dynamically . please assign me this project under GSSOC'24

**Comment by Vishnu1804K** [comment]
@GarimaSingh0109 You raise your issuses

**Comment by pranav-666** [comment]
I can add an excellent login and sign up page which is validated additionally I can add some other the required features like forget password page

**Comment by Vishnu1804K** [comment]
Hey @pranav-666 raise your own issue it is my issue
