### ISSUE TITLE
Menu link, service link, contact us link  not working properly in footer section

### ISSUE THREAD

**Issue by harinisayani** [khushi-joshi-05/Food-ordering-website#487]
I have observed that menu link, service link, contact us link is not working properly in footer section.
I want to make them work properly by adding suitable links.
I am GSSOC'24 Contributor
I want to work on this issue.
Please assign me this task.

**Comment by Jatin-gumber12** [comment]
Please assign this issue to me. I'll fix this as soon as possible

**Comment by Phil94comp** [comment]
I just submitted a pull request. Please let me know if you like the changes.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
