### ISSUE TITLE
attribute to links

### ISSUE THREAD

**Issue by gaurijoshi25** [khushi-joshi-05/Food-ordering-website#49]
![Screenshot 2024-05-10 111254](https://github.com/khushi-joshi-05/Food-ordering-website/assets/152186567/096bcb74-0ebf-41d6-aac8-83d54a03876e)
there is no attribute to the links shown above.
kindly assign this task to me under GSSoc'24 @khushi-joshi-05

**Comment by Rrishabh2003** [comment]
I can solve this one

**Comment by HimangshuRanjan** [comment]
I want to work upon this, please assign this task to me.

**Comment by sunny0625** [comment]
@gaurijoshi25 are you still up for issue?
