### ISSUE TITLE
enhancing the SERVICE section page.

### ISSUE THREAD

**Issue by suhanigupta23** [khushi-joshi-05/Food-ordering-website#494]
In service section page we can add links to the "Food Tour and Experiences" and "Catering Services for Events" . And linking Meal delivery subscription to a new page having options for buying membership (gold, silver etc) and according to monthly and yearly subscriptions .
Like this:
![Memberships-vs-Subscriptions-What_s-the-Difference-Inner-08-1024x588](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/6d760c42-a303-4343-997a-a885bb54738a)
<img width="1186" alt="Screenshot 2024-05-25 at 10 00 39 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/144280247/3174f584-87a7-47bc-8c9a-4517ddabd14c">
I want to work on this issue under Gssoc'24.

**Comment by khushi-joshi-05** [comment]
@suhanigupta23 i have assigned u the task. first design is pretty good, go ahead with it

**Comment by suhanigupta23** [comment]
@khushi-joshi-05 please add label of gssoc to the issue
