### ISSUE TITLE
Elements are overflowing on the Home Page

### ISSUE THREAD

**Issue by suma30** [khushi-joshi-05/Food-ordering-website#50]
# Problem
The elements in the home page as shown in the pics are overflowing

# Solution
I will fix the problem

# Request
I am a GSSOC contributor 
Please assign me this issue @khushi-joshi-05

**Comment by MelissaSequeira** [comment]
Pls Assign me this task:
you can check my repos where i made websites responsive:
https://melissasequeira.github.io/fashionweb.github.io/
https://melissasequeira.github.io/My_Portfoliogithub.io/
