### ISSUE TITLE
Improvising the UI of Bringing happiness to you section.

### ISSUE THREAD

**Issue by GauriGupta21** [khushi-joshi-05/Food-ordering-website#501]
Hey @khushi-joshi-05 

![Screenshot 2024-05-25 134614](https://github.com/khushi-joshi-05/Food-ordering-website/assets/117813988/8fd87614-7366-4532-9871-47b302f8943a)

I have noticed the repetition of background image in this section and I would like to resolve this issue.
I would also like to add or change few more things in this section like:

1. Improve UI to make it more user friendly and interactive.
2. Placement of text and buttons.
3. Make it responsive.
4. Improve font style to make it more visible.

Please assign this task to me under GSSoC'24.

**Comment by khushi-joshi-05** [comment]
@GauriGupta21  i have assigned u this issue. Only work on the background part and making the buttons more visible.

**Comment by GauriGupta21** [comment]
@khushi-joshi-05 thanks for assigning me this issue and please add GSSoC label as well.

**Comment by GauriGupta21** [comment]
@khushi-joshi-05 I resolved the background image issue and make buttons more visible. Kindly check the changes.
