### ISSUE TITLE
Improving the contact us component

### ISSUE THREAD

**Issue by Athul28** [khushi-joshi-05/Food-ordering-website#502]
The component isn't styled using CSS it doesn't look good, I can add CSS and make it look good

![Screenshot 2024-05-25 140430](https://github.com/khushi-joshi-05/Food-ordering-website/assets/79209367/29284bf9-1121-4800-8d8b-c370aa7dd023)

**Comment by gyanshankar1708** [comment]
@khushi-joshi-05
I am a GSSOC 2024 Contributor. 
Can I work on this.

**Comment by khushi-joshi-05** [comment]
@Athul28 i have assigned u this issue. Also on mobile screen the dimensions of this contact section isn't aligning with other elements. Do improve that if u can.

**Comment by Athul28** [comment]
@khushi-joshi-05 okay I will do it, thanks for assigning it to me
