### ISSUE TITLE
Bug: Navbar section not aligned properly.

### ISSUE THREAD

**Issue by gyanshankar1708** [khushi-joshi-05/Food-ordering-website#504]
Hey @khushi-joshi-05 
I had visited your web page. There  i saw that the navbar is not aligned properly and the style of onordererd list is not made to none.
![Screenshot 2024-05-25 150126](https://github.com/khushi-joshi-05/Food-ordering-website/assets/155980409/5f6d5a1e-ba85-4e12-8ac3-40eab96df69c)
I am a GSSOC 2024 contributor
Please assign me for this work.

**Comment by khushi-joshi-05** [comment]
@gyanshankar1708  i have assigned u this issue.

**Comment by gyanshankar1708** [comment]
I had raised Pr #520  for this iaaue please review it and merge it.
