### ISSUE TITLE
Make an Input section for coupon code!

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#509]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/1b2f47ca-e402-47a4-ae25-5d95de700afb)

- Make a input section for coupon code to apply Discount.

**Comment by jency1** [comment]
Customers will be able to enter and apply coupon codes during the checkout process, making it easier to use discounts and improving the overall user experience.

Please assign this issue to me.

**Comment by Karthik5400** [comment]
Customers can use ,making it easier to use discounts and improving the overall user experience.

Please assign this issue to me.

**Comment by Seejal03** [comment]
pls assign me this issue

**Comment by avilash01** [comment]
Customers will be able to enter the coupon codes which will help the customer in getting the discount which increases the frequency of the ordering of the customer. 
Please assign this issue to me.
