### ISSUE TITLE
Spell error in the content

### ISSUE THREAD

**Issue by I-Saara** [khushi-joshi-05/Food-ordering-website#511]
"Memories" is misspelt as "memotries" under the INDIAN thali section on the website.
"Deliciouis" word has also spell error .
Please assign it to me. 
I am contributor in GSSOC'24.

**Comment by Gultreen** [comment]
There are two spelling errors on the website , these domains are as -

1. In the INDIAN THALI section , "Memotries" word has an spell error . 
2. In the SNACKS section, "Deliciouis" word has also spell error . 
![Uploading spell.jpeg…]()

Proposed Solution : 
1. The correct spelling is " MEMORIES ".
2. And next is " DELICIOUS ".

I am a GSSoC Contributor .Please  @khushi-joshi-05  assign me this task .
