### ISSUE TITLE
Bug : 2 Contact Us Links in Navbar on Home Page 

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#515]
There is an issue with the hover color for links on the home page. When users hover over the links, the color changes to match the background color, making the links invisible and negatively impacting the user experience.

Issue (example) : [Hover Color Matches the background color](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/00ce5bfb-39af-4ad2-9134-ef5ab74aeabc)

Please assign this issue to me so I can solve this as it makes the links invisible. @khushi-joshi-05

**Comment by GarimaSingh0109** [comment]
I can't assign you the issue. You should contact @khushi-joshi-05

**Comment by jency1** [comment]
> I can't assign you the issue. You should contact @khushi-joshi-05

It was by mistake, I mentioned you. I wanted to mention her only.
