### ISSUE TITLE
Bug : Quick Links in Footer Section Not Working on Home Page

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#516]
The quick links in the footer section of the website are currently not functioning. On clicking the link, it redirects us to 404 error page.
This issue affects the following links on Home Page:

1. Menu
2. Services
3. Contact Us
4. Cart

Error : [404 Error - footer link](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/09043031-4482-4451-a4ab-6a85a8bb4c23)

When users click on these links, they do not redirect to the appropriate sections or pages. This is impacting the user experience as it prevents easy navigation to important parts of the site.

I'm GSSOC'24 contributor. Please assign this issue to me so I can resolve it as soon as possible.
@khushi-joshi-05

**Comment by jency1** [comment]
@GarimaSingh0109  @sunny0625   

Can I start working on this issue? 

As it needs to be resolved as soon as possible so that user can get the best experience while using the website. 
Also it makes the negative impact when not redirected to the appropriate page.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
