### ISSUE TITLE
Bug: The message and Email section of contact overlap when Message section is Expanded

### ISSUE THREAD

**Issue by Archit-Ash** [khushi-joshi-05/Food-ordering-website#529]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/95583743/5b465c8b-6245-4703-b97c-832a2d25c51b)

i would like to improve it by fixing a size for the message section ,so that it doesn't overlap the email section

**Comment by Archit-Ash** [comment]
#GSSoC24

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
