### ISSUE TITLE
WRONG position of marquee EFFECT

### ISSUE THREAD

**Issue by anshgautam-github** [khushi-joshi-05/Food-ordering-website#53]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/95379812/7e4603ef-2117-469d-b8ff-3a806c9b8c97)

This 30% offer line should come at the top of the website and not above the footer. 

Kindly, assign this issue to me under GSSOC 24

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.I have prior experience too as I have made 20+ Full-stack projects.
