### ISSUE TITLE
Bug : Fix The Rating System Of The Dishes!!!

### ISSUE THREAD

**Issue by Anupsimha** [khushi-joshi-05/Food-ordering-website#535]
![Screenshot 2024-05-26 075212](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144825137/0dfc3e08-49da-4f57-a383-78b33e30a7be)
Improper Rating System. Will Enhance It Like The Real World Working Websites.
Please Assign This Task To me!!!!

**Comment by Anupsimha** [comment]
@khushi-joshi-05 Please Assign Me This Task Under GSSOC'24!!!!

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
