### ISSUE TITLE
[BUG]: "Send Message" Button not aligned Properly

### ISSUE THREAD

**Issue by kashvi9** [khushi-joshi-05/Food-ordering-website#545]
The text in **Send Message** Button is not aligned properly. It's more towards the bottom.

Here's a screenshot, 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/169376061/b6c88c0a-2eb0-477f-9d1b-e8cd3954b530)
Hey @khushi-joshi-05 
I can align this text properly in the middle, if you assign me this issue under GSSOC'24.
Thank You!

**Comment by harshcodesit** [comment]
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS , I can design the button with proper alignment.

Please assign this task to me, GSSOC'24 .

**Comment by harshcodesit** [comment]
hey @khushi-joshi-05 ,
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS , I can design the button with proper alignment.

Please assign this task to me, GSSOC'24 .

**Comment by kashvi9** [comment]
I'll am highly thankful to @khushi-joshi-05 and @sunny0625 for giving me this opportunity to solve this issue, since it has been completed and merged can you please add suitable labels to it and close this issue.
Thanks
