### ISSUE TITLE
[BUG]: Changing the title of Website

### ISSUE THREAD

**Issue by kashvi9** [khushi-joshi-05/Food-ordering-website#546]
The title of the Website must be changed to **Foodie** from _Food Ordering Website_.

Here is a screenshot of how it looks-

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/169376061/9d6601a8-c86e-42a2-a1c9-f99a7d672820)

Hey PA @khushi-joshi-05 ,
I can solve this issue under GSSOC'24, if you assign me this.
Thank you!

**Comment by Nehasree08** [comment]
I can work on it , can you assign it to me please
under GSSOC'24

**Comment by harshcodesit** [comment]
@sunny0625 
please assign me the issue
