### ISSUE TITLE
Improving UI Alignment and Color Scheme for Log In and Sign Up Pages

### ISSUE THREAD

**Issue by khushi-joshi-05** [khushi-joshi-05/Food-ordering-website#552]
Issue Description:
The Log In and Sign Up pages need adjustments in color and alignment to match the website's design. Existing discrepancies affect user experience.

Proposed Solution:
Align elements uniformly and harmonize color schemes with the website's palette for consistency and improved aesthetics.

**Comment by jency1** [comment]
Please assign this issue to me. So that I can make relevant changes for login and sign up pages.

**Comment by khushi-joshi-05** [comment]
@jency1 i have assigned u this issue. Go ahead and make it visually appealing and maintain consistency in colors.

**Comment by jency1** [comment]
> @jency1 i have assigned u this issue. Go ahead and make it visually appealing and maintain consistency in colors.

Thanks for assigning this issue to me. I will make necessary changes as soon as possible. 

Please add the gssoc label and level label.

**Comment by jency1** [comment]
@khushi-joshi-05 @sunny0625  

Please add the gssoc and level label. Otherwise my PR won't be counted.

**Comment by jency1** [comment]
@khushi-joshi-05  Can you please add the labels gssoc and level2 in the raised issue also? 

As it was told that the labels should me mentioned in both the issue and the pull request, I am having the labels in pull request only so please add the labels on this raised issue also. #552

Thank you!

**Comment by jency1** [comment]
@khushi-joshi-05 

Thank you for adding the labels and merging PR. 

Can you please change the level of difficulty from level2 to level3 ? Because I have changed the UI of whole page for both login and sign up pages. I have also changed the colors of the forms such that it matches the website's palette for consistency and improved aesthetics.
