### ISSUE TITLE
Add Discord Link

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#558]
Add Discord Link in the footer section.

- https://discord.com/invite/sybYafYA
- Also edit the GitHub URL to this repo URL.

**Comment by jency1** [comment]
Please assign this issue to me. I will make necessary changes as soon as possible.

**Comment by Srujitha-Raghava** [comment]
hello @sunny0625 sir, I can make the required changes please assign this to me

**Comment by sunny0625** [comment]
@Srujitha-Raghava work on this issue!

**Comment by jency1** [comment]
@sunny0625 As the assignment of issues is based on a first-come, first-served basis, I wanted to highlight that I was the first to comment on this issue. I kindly request that you check this and reassign this issue to me.

I appreciate your consideration and look forward to contributing to the project.

Thank you!

**Comment by Srujitha-Raghava** [comment]
okay sir @sunny0625 Ok can you assign this to me?

**Comment by sunny0625** [comment]
Thank you @jency1  for responding to this issue. As this program is open-source every contributor has the right to get the opportunity to contribute. As you have already solved previous issues.

**Comment by Srujitha-Raghava** [comment]
@sunny0625 I've raised a PR,please review it sir!

**Comment by sunny0625** [comment]
@Srujitha-Raghava what about other pages ?

**Comment by Srujitha-Raghava** [comment]
Oh sorry for that,I will add in them too

**Comment by Srujitha-Raghava** [comment]
@sunny0625 #559 kindly,please check it sir

**Comment by jency1** [comment]
> Thank you @jency1 for responding to this issue. As this program is open-source every contributor has the right to get the opportunity to contribute. As you have already solved previous issues.

Okay!
