### ISSUE TITLE
Responsiveness of website

### ISSUE THREAD

**Issue by MitulSonagara** [khushi-joshi-05/Food-ordering-website#56]
The website is not perfectly responsive for mobile and tablets. I will make it responsive. Please assign me this issue. I am contributing under GSSOC'24

**Comment by MelissaSequeira** [comment]
Plz assign this task to me to make the webpage responsive...
U can check these repos of my
https://github.com/MelissaSequeira/fashionweb.github.io

**Comment by MelissaSequeira** [comment]
@khushi-joshi-05
Also plz add level ,and gssoc label

**Comment by GarimaSingh0109** [comment]
@khushi-joshi-05 i have worked on many web projects and most of them are responsive i can use tailwind and bootstrap both to improve the user experience of the webpage kindly assign me this issue under #gssoc'24

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by nsk6704** [comment]
Please assign this issue to me !

I have interned at Codsoft and have sufficient experience in making responsive websites!

I am also certified by freeCodeCamp in Respinsive Web Design!

**Comment by ShatakshiPalli** [comment]
Please assign me this issue. I would like to make the website responsive using Bootstrap.

**Comment by sunny0625** [comment]
@MitulSonagara work on other pages. The home page is responsive.
