### ISSUE TITLE
[Feat]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [khushi-joshi-05/Food-ordering-website#562]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

![PR merged](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115717746/f1859b86-d726-4012-b24c-43a962a396dd)

**Comment by Asymtode712** [comment]
@sunny0625 please assign me this issue

**Comment by Asymtode712** [comment]
@sunny0625 please assign me this issue

**Comment by sunny0625** [comment]
Is this workflow Automerge into the main branch without authentication?
@Asymtode712

**Comment by Asymtode712** [comment]
@sunny0625 this workflow is only for commenting on a PR when it is merged by the maintainer of this repo
