### ISSUE TITLE
[Feat]: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [khushi-joshi-05/Food-ordering-website#563]
This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

![Close Old Iss](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115717746/55a7419f-c396-4101-a2f4-6d687a63aa3e)

**Comment by Asymtode712** [comment]
@sunny0625 please assign me this issue

**Comment by Asymtode712** [comment]
@sunny0625 please assign me this issue

**Comment by Asymtode712** [comment]
@sunny0625 please assign me this issue

**Comment by sunny0625** [comment]
Does this feature close Genuine issues automatically if we delay an assignment or reply?

**Comment by Asymtode712** [comment]
@sunny0625 This workflow will close the issues which are inactive for a span of 30 days or more
