### ISSUE TITLE
[Bug]:Service Page is not responsive in mobile view

### ISSUE THREAD

**Issue by alok2424** [khushi-joshi-05/Food-ordering-website#574]
Here is the video of the Service Page of the website . As I have open the website in the mobile , none of the element are aligning properly.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/130597958/123c818a-4ba0-4764-a3ac-b010a6d3c2e3

This is a major issue as no one will able to access the website from mobile.

**Comment by sunny0625** [comment]
@alok2424 gtg..!

**Comment by alok2424** [comment]
Sir , please merged my previous PR #640 .
