### ISSUE TITLE
Add logo on the webpage and modify the nav bar. 

### ISSUE THREAD

**Issue by harsh02mishra** [khushi-joshi-05/Food-ordering-website#586]
1. The webpage does not have a logo for the website.
2. The navigation bar items appear too close together due to lack of spaces.
By modifying the navigation bar and adding a logo related to the website's theme (foodie).
I also attached the updated view of the website below
**After Modification**
![Modifyed Foodie](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144336311/8571e579-6a1b-4ec5-a0a9-b76816534400)

@khushi-joshi-05 Plaese assign me this task..
GSSoC'24

**Comment by akarshi19** [comment]
Please assign this issue to me under GSSOC'24

**Comment by khushi-joshi-05** [comment]
@harsh02mishra I think current navbar is pretty good, adding a logo only will be enough .

**Comment by harsh02mishra** [comment]
> @harsh02mishra I think current navbar is pretty good, adding a logo only will be enough .

Sure
