### ISSUE TITLE
Hover of the footer 

### ISSUE THREAD

**Issue by jayanththalla** [khushi-joshi-05/Food-ordering-website#588]
Hover the footer and make social media discord hover.
Other social media links are hover but discord is not hover.
please assign me @khushi-joshi-05

**Comment by Taranpreet10451** [comment]
@khushi-joshi-05 plz assign me this issue I would love to solve this

**Comment by aditi29400** [comment]
@khushi-joshi-05 please assign

**Comment by aditi29400** [comment]
@sunny0625 please assign
