### ISSUE TITLE
add Slider preview for home page 

### ISSUE THREAD

**Issue by Dhack29** [khushi-joshi-05/Food-ordering-website#60]
_**Add feature to slider.**_ 

Image and content changes after few seconds .

Add buttons for previous and next.

and make it more attractive and professional.

![Screenshot 2024-05-10 162727](https://github.com/khushi-joshi-05/Food-ordering-website/assets/150424032/803637e9-0e89-4ad8-8a25-58cffb312ac3)

Please Assign to me Under GSSoC'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24. I am used it in one of my projects and can work on it.
