### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by JanitKumar** [khushi-joshi-05/Food-ordering-website#601]
I want to improve navbar. Majorly, I want to improve hover of navbar and navbar responsiveness is also not good I want to change it too.
What I will do is make a icon by clicking which all the options of navbar can appear
please assign it to me. I eagerly want to contribute in your project and make your project.

![Screenshot 2024-05-27 184821](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126192349/746a8d92-5751-4fa9-8063-62bd569dbb01)

**Comment by MegaTron200** [comment]
Hello,
I hope this message finds you well. My name is Suhani, and I am participating in the GirlScript Summer of Code (GSSoC) program. I'm reaching out to express my interest in working on the Navbar enhancement . Could you please assign this task to me?

**Comment by lovelymahor** [comment]
I would like to work on this issue; please assign it to me

**Comment by Sajiyasiddiqui** [comment]
I want to work on this please assign me.
.

**Comment by n14rishitha** [comment]
> I want to improve navbar. Majorly, I want to improve hover of navbar and navbar responsiveness is also not good I want to change it too. What I will do is make a icon by clicking which all the options of navbar can appear please assign it to me. I eagerly want to contribute in your project and make your project.
> 
> ![Screenshot 2024-05-27 184821](https://private-user-images.githubusercontent.com/126192349/334115585-746a8d92-5751-4fa9-8063-62bd569dbb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMTQxNjQsIm5iZiI6MTcxNzMxMzg2NCwicGF0aCI6Ii8xMjYxOTIzNDkvMzM0MTE1NTg1LTc0NmE4ZDkyLTU3NTEtNGZhOS04MDYzLTYyYmQ1NjlkYmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwNzM3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTNkNjcxYmY3YmI0NWEyOTQzZmMxZmJlZDYwNmNhNGJjZmE1MzdiZjFmZDZiNWUzMzVmMjUxYjc2OTYyZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VlhQj5XA6fIQWIj0p18mVkI5LHuHCiwaHtuqtlikiws)

Hi @sunny0625 

I would like to work on this issue .  I can solve this issue . so could you please assign this task to me .

**Comment by JanitKumar** [comment]
i closed it because before i could make it responsive someone had already made it
