### ISSUE TITLE
Bug in cart page: After change the quantity, the product name change to undefined.

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [khushi-joshi-05/Food-ordering-website#604]
To find the bug,
1. Add an item to cart.
2. Increment/decrement the quantity
3. refresh the page
4. Now it is visible that product name is turning to undefined: 

https://github.com/khushi-joshi-05/Food-ordering-website/assets/139672976/430a9af3-5a04-41ed-992b-f795f84dcc6b

I would like to solve this issue.
I would also like to improve the ui of the cart page as below.

![Screenshot 2024-05-27 194139](https://github.com/khushi-joshi-05/Food-ordering-website/assets/139672976/8d3aaa2c-d6b2-42eb-85f4-9261880e8291)

Not only that it would be more user interactive if we display a message as below when there is no cart items. I would also like to do that.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/139672976/a8c38d7f-3c85-4ab9-8912-9c0fe94c2ab1)

Kindly please assign this issue to me for improve cart page.

**Comment by khushi-joshi-05** [comment]
@DharshiBalasubramaniyam I have assigned u this issue. Go ahead.

**Comment by DharshiBalasubramaniyam** [comment]
@khushi-joshi-05 @sunny0625 Thank you assigning me the issue. Can you please add gssoc and level labels to this issue?. I have raised a pr for this issue as well. Kindly please review that pr.
