### ISSUE TITLE
Bug in Footer near Copyright Area

### ISSUE THREAD

**Issue by akhileshhSingh** [khushi-joshi-05/Food-ordering-website#609]
![Screenshot 2024-05-27 214407](https://github.com/khushi-joshi-05/Food-ordering-website/assets/140011019/731e218d-0edb-4dfe-b675-0c547e417885)

The Footer section near Copyright Area looks distorted (main main is appearing in dark grey color)
I can fix this bug,please assign me this under GSSoc.

**Comment by sunny0625** [comment]
I guess this issue has been solved, Try to participate in different issues!
