### ISSUE TITLE
Logo for the website 

### ISSUE THREAD

**Issue by Atreyiprasad** [khushi-joshi-05/Food-ordering-website#613]
I would like to make a logo for the website, focusing on simplicity and professionalism.   
kindly assign me this issue .

**Comment by SohaFarhana** [comment]
Hii 
I would like to work on this issue.
Can u assign this to me under GSSOC'24

**Comment by Henin-6024** [comment]
I would like to fix this issue. Please assign this task to me under GSSoC'24 with required labels.
