### ISSUE TITLE
Signup and Login Links Show Text Instead of Cursor on Hover

### ISSUE THREAD

**Issue by kashnx** [khushi-joshi-05/Food-ordering-website#615]
When clicking on the signup and login links within our application, the text is being selected instead of the cursor changing to indicate an interactive element. This behavior is confusing for users.

Expected Behavior:
Clicking on the signup or login links should change the cursor to a pointer (hand icon), indicating that these are clickable, interactive elements. It should then proceed with the expected action (e.g., redirect to the signup or login page).

Please assign this issue to me.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
