### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Shreyaa173** [khushi-joshi-05/Food-ordering-website#618]
The documentation can be better.
![Screenshot 2024-05-28 104741](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144673309/73a72f52-c328-4e5f-9e7b-b8b7f55f494d)
please assign me @khushi-joshi-05

**Comment by RahaneSayali** [comment]
@khushi-joshi-05 assign this to me

**Comment by SohaFarhana** [comment]
Can u assign this issue to me under GSSOC'24

**Comment by sunny0625** [comment]
@Shreyaa173 gtg..!

**Comment by richamaitry248** [comment]
@khushi-joshi-05 . I want to work on this issue raised so adhere to assign this issue to me.
I will be delighted to  work on this under gssoc 24 .thankyou!

**Comment by Shreya173** [comment]
It is already assigned to me and I have already submitted the PR.
