### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Shreyaa173** [khushi-joshi-05/Food-ordering-website#619]
The color should be better as it is not clearly visible.
![Screenshot 2024-05-28 104715](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144673309/114703b1-937d-4572-a5ad-3a8b4716bb32)
please assign me @khushi-joshi-05

**Comment by khushi-joshi-05** [comment]
@Shreyaa173 this one is solved
