### ISSUE TITLE
Enhancing media queries

### ISSUE THREAD

**Issue by Vanshikaxxa** [khushi-joshi-05/Food-ordering-website#62]
Enhancing the media queries of the website, I've encountered a few issues:
1.  Some images extend beyond the window boundaries, disrupting the layout.
2.  The message box in the footer doesn't align properly with the rest of the content. 
3.  The contrast between the images and the website, as well as the font, isn't blending well together.
4. I will utilize Fooocus AI to seamlessly integrate images into the website, ensuring they enhance the overall aesthetic and user experience.

These issues need to be addressed to ensure a seamless user experience across different devices and screen sizes.
could you please assign it to me GSSOC 24' : ) @khushi-joshi-05

**Comment by MelissaSequeira** [comment]
Pls Assign me this task:
you can check my repos where i made websites responsive:
https://melissasequeira.github.io/fashionweb.github.io/
https://melissasequeira.github.io/My_Portfoliogithub.io/

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05! I'd love to take on the task of enhancing media queries. With my background as an experienced web content writer, having authored and published over 30 articles on Asiana Times' website, along with several content writing internships under my belt, I'm confident I can contribute effectively. Could you please assign this task to me with the GSSOC tag? Thanks!
