### ISSUE TITLE
Bug-hover effect

### ISSUE THREAD

**Issue by Shreyaa173** [khushi-joshi-05/Food-ordering-website#620]
Hover effect on the discord button is not working
![Screenshot 2024-05-28 104811](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144673309/bac721ec-387d-45ed-ac4c-0fd7ada9eeca)
please assign me @khushi-joshi-05

**Comment by khushi-joshi-05** [comment]
@Shreyaa173 i have assigned u this issue
