### ISSUE TITLE
Hover effect on play store and app store icon

### ISSUE THREAD

**Issue by Shreyaa173** [khushi-joshi-05/Food-ordering-website#621]
I want to add hover effect on play store and app store icon.
![Screenshot 2024-05-28 105318](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144673309/3c1bc522-51d4-4fd4-b480-2b50a0e41c07)
please assign me @khushi-joshi-05

**Comment by khushi-joshi-05** [comment]
@Shreyaa173  go ahead
