### ISSUE TITLE
color is not visible

### ISSUE THREAD

**Issue by Shreyaa173** [khushi-joshi-05/Food-ordering-website#622]
![Screenshot 2024-05-28 105542](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144673309/0c5cffc3-2bd1-4675-91d8-ff2505ca2a39)
want to change please assign @khushi-joshi-05

**Comment by Muhammad-Rebaal** [comment]
Hi @khushi-joshi-05 !
Can you assign this issue to me ?

**Comment by khushi-joshi-05** [comment]
@Shreyaa173 this is solved
