### ISSUE TITLE
Menu Card Layout

### ISSUE THREAD

**Issue by aggrhythm** [khushi-joshi-05/Food-ordering-website#623]
The ratio of these pictures aren't fitting well, i would like to change the dimensions and implement round cornering along with changing the hover effects to make it more smoother.
I would request @khushi-joshi-05 and @sunny0625 to assign me this issue

![WhatsApp Image 2024-05-28 at 12 11 28](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115718113/21ef51e2-a616-4a02-a7e9-da1c1a50a057)

**Comment by khushi-joshi-05** [comment]
@aggrhythm go ahead
