### ISSUE TITLE
[Bug] : Fixing Navbar Alignment

### ISSUE THREAD

**Issue by its-kumar-yash** [khushi-joshi-05/Food-ordering-website#63]
Current Navbar Alignment is neither attractive nor visible, I'll fix this issue.
Kindly assign this issue to me 

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/97521394/4fa06dd6-3a33-4360-9047-7e422d3dc996)

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @khushi-joshi-05,

I hope you're doing well! I noticed the [Bug] regarding the Navbar Alignment and I'd like to take on the task. I have experience as a web content writer, having authored and published over 30 articles on the Asiana Times website. Additionally, I've completed several content writing internships. Could you please assign this task to me with the GSSOC tag?

**Comment by Godavarikadam** [comment]
Navbar allignment is not properly done and it can be made more attractive by applying styling to this navbar .
So please assign this to me so  i can make chnges in navbar UI with preserving the responsiveness of webpage.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
