### ISSUE TITLE
Bug : Text Color not visible in Cart Table 

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#631]
Currently the text color is not visible in the Cart Table in cart page. It matches the background color making it invisible. So user cannot read what's in the cart.

This needs to be resolved as soon as possible for best user experience.

Bug : [cart table](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/6e27e781-bc85-4170-8186-793010287c34)

Please assign this issue to me, As I would like to resolve this bug as soon as possible.

@khushi-joshi-05  @sunny0625

**Comment by Taranpreet10451** [comment]
If we look at the cart table table then the text isn't visible this needs to be resolved for increasing the user experience as soon as possible.

Issue: Cart Table

Please assign me this issue. I would love to work on it.
@khushi-joshi-05 @sunny0625

**Comment by Taranpreet10451** [comment]
@jency1 If you are supposed to assign this issue then please assign it to me I also want to work on it.
