### ISSUE TITLE
Enhancing the login and sign up page

### ISSUE THREAD

**Issue by taneeshaa15** [khushi-joshi-05/Food-ordering-website#639]
I will make the login and sign up page look more attractive.

**Comment by taneeshaa15** [comment]
@khushi-joshi-05 Please assign me this issue under GSSoC'24 label.

**Comment by RahaneSayali** [comment]
Good at enhancing @khushi-joshi-05 assign this to me

**Comment by taneeshaa15** [comment]
@sunny0625 @khushi-joshi-05 Please assign me this issue under GSSOC'24 label. (Assign this on first come first serve please).

**Comment by sunny0625** [comment]
@taneeshaa15 Describe your contribution.

**Comment by taneeshaa15** [comment]
@sunny0625 I will add hover on the login page and signup page, and i will merge the pages into one with giving transition from figma.

**Comment by taneeshaa15** [comment]
@sunny0625 starting working on it and will shaare the progress with you soon.
