### ISSUE TITLE
Contact us panel format links to socials and menu page.

### ISSUE THREAD

**Issue by Harsh-KumarJha** [khushi-joshi-05/Food-ordering-website#64]
![Screenshot 2024-05-10 174120](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121922047/ed012e0d-ddc1-4465-acf8-56b1a7e6189b)

1. The navigation through the social links is not appealing and do not work. I can make them interactive for the user on hover.
2. the send message and the your email placeholder test do not match and i can fix it and can make it look better
3. The our Pages do not work I can link the following for navigation.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121922047/c6e0b102-9021-4d39-884a-ad665a87c0a1)

1. The issue for menu page is less visually appealing and the pricing is in dollars where I can add a dollar to rupee converter that will convert all the prices in dollars.
2. and I can add a better Hover animation for cards.

I am a contributor to GSSoC'24 and I want to contribute to your project with above ideas to make a better experience for the users and thus I am looking for the assignment so that i can source out merge request and start contributing.

Thanks.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @khushi-joshi-05,

I hope this message finds you well! I'm excited about the opportunity to enhance the visual appeal of the Contact Us panel and other sections on our platform. As an experienced web content writer, I've authored and published over 30 articles on the Asiana Times website and have completed numerous content writing internships.

Could you please assign me the task with the GSSOC tag? I'm eager to contribute to our project's success.
