### ISSUE TITLE
add a hover effect on menu counters 

### ISSUE THREAD

**Issue by shuhaki** [khushi-joshi-05/Food-ordering-website#641]
add a hover effect on menu counters ..
zoom in/ zzom out hover effect according for user interface

<img width="1401" alt="Screenshot 2024-05-29 at 12 08 08 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/145912232/edf5c68f-4b88-4b72-b5f7-199905e49858">

**Comment by Silentman87** [comment]
please assign  this issue to me  i want to work on it..
#641

**Comment by sunny0625** [comment]
@shuhaki Zoom in / out already working. Could you describe your contribution to improve it?
