### ISSUE TITLE
Making attractive UI for the contact page

### ISSUE THREAD

**Issue by Khanishsuresh** [khushi-joshi-05/Food-ordering-website#647]
By making the UI attractive, it would make the user feel comfortable. 
So i would like to make some changes in the UI of the contact page according to the website

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/136162512/5f1102d2-5c97-4414-8333-1197f6266312)

**Comment by Khanishsuresh** [comment]
Hii @khushi-joshi-05 ,

i would like to work on this issue
would u please assign this issue under GSSOC'24 with respective levels

**Comment by khushi-joshi-05** [comment]
@Khanishsuresh Thanks for creating issue! 2 contributors are already working on it.
