### ISSUE TITLE
 Add  to cart section text color need to improved

### ISSUE THREAD

**Issue by AakankshaSarode** [khushi-joshi-05/Food-ordering-website#648]
in Add to cart section adding  added items not clearly visible due to text color

**Comment by AakankshaSarode** [comment]
@khushi-joshi-05  please assign me this issue under GSSOC . I want to work on this issue.

**Comment by hitali-khachane** [comment]
Can u pleasse Assign me this issue .I would like to Work on this issue

**Comment by sunny0625** [comment]
@AakankshaSarode can you Describe your issue!

**Comment by guneetdewangan9** [comment]
I would like to work on this issue under GSSoC . Please assign this issue to me.

**Comment by AakankshaSarode** [comment]
@sunny0625  someone already solved this issue
