### ISSUE TITLE
Fixing cards of Customer opinion section and footer enhancement.

### ISSUE THREAD

**Issue by hussain123sahil** [khushi-joshi-05/Food-ordering-website#65]
Here the cards of customer opinion section is very basic. I can improve the fonts, add hover effect to cards as well choose good color combination to make the cards more attractive. Plus the borders are very much basic, i can improve the borders by making it slight rounded from four sides.
Also the footer section fonts need to be improved and the contact us part can be more eye catching.

![Screenshot (133)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126157627/e131efa9-c5f6-45cf-9fc7-24c66cd2a144)

I can improve all this functionality. Please assign me this issue under GSSOC'24.

**Comment by hussain123sahil** [comment]
@khushi-joshi-05 please look into this and assign me this issue.

**Comment by ShatakshiPalli** [comment]
I would like to work on this issue. Please assign me.
