### ISSUE TITLE
Improve design for the Home section

### ISSUE THREAD

**Issue by DebapriyaJha** [khushi-joshi-05/Food-ordering-website#650]
I feel that the design layout of the Home section can be enhanced more and can be made more professional, eye-catching and attractive for the customers.

I would love to solve this issue and contribute to the project. Please assign me this under the gssoc and appropriate level labels.

**Comment by vishalmanve** [comment]
i would love to solve this issue please give me chance to merge the new skills with new features

**Comment by Ananya-Nair20** [comment]
Hello 

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you

**Comment by hitali-khachane** [comment]
I would love to work on this issue .Can u please assign this issue to me @DebapriyaJha

**Comment by Palakmeena** [comment]
I want to work on this issue please assign it to me

**Comment by DebapriyaJha** [comment]
@sunny0625 can you also add the appropriate level label to this issue
