### ISSUE TITLE
Login/SignUp button in navbar not have pointer

### ISSUE THREAD

**Issue by zalabhavy** [khushi-joshi-05/Food-ordering-website#654]
This is not good that login/signup button not have cursor pointer i will add pointer to that so it give better experience.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/126322584/4266fec9-9455-4f36-a909-0c693fca3f6e)

**Comment by khushi-joshi-05** [comment]
@zalabhavy it has now.
