### ISSUE TITLE
Cart Page UI improvement

### ISSUE THREAD

**Issue by Sypher0Dronzer** [khushi-joshi-05/Food-ordering-website#658]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/83546205/7181a58a-91aa-492d-8069-723086349112)
The Ui of the cart section needs improvement 
please assign this issue to me  @khushi-joshi-05

**Comment by sunny0625** [comment]
@Sypher0Dronzer gtg..!

**Comment by Sypher0Dronzer** [comment]
@sunny0625 sir can you revert the changes taht were made to the cart page , now the on adding things to the cart, those food items are not being displayed
instead can I solve the issue of the footer as of now 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/83546205/27af14ae-a85a-4560-8a0b-cfceff944b8e)
