### ISSUE TITLE
Customer feedback section

### ISSUE THREAD

**Issue by aggrhythm** [khushi-joshi-05/Food-ordering-website#659]
I would like to add a section of customer feedbacks on the home page.
Attaching an example image

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/115718113/56033148-c90c-4b09-b8f0-189a34771392)

Therefore i request the project admins @khushi-joshi-05 & @sunny0625 to assign me this issue

**Comment by sunny0625** [comment]
@aggrhythm gtg..!
