### ISSUE TITLE
Contact Us Section Of Homepage

### ISSUE THREAD

**Issue by sukritcharredsoul** [khushi-joshi-05/Food-ordering-website#66]
The contact us section of the code isn't looking very pleasing , i wish to make it more appealing to the potential consumers and add value to the website.

I wish to work on this issue.

**Comment by 23additi** [comment]
Hey
I would like to work on this issue.

**Comment by prajwaldp223** [comment]
I would like to fix this issue

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by bk408** [comment]
Hello @khushi-joshi-05 
I'm proposing an update to the Contact Us section design to enhance its aesthetics and usability. This update will include improvements in colour scheme, typography, layout, and responsiveness.

**Comment by achlbatra** [comment]
I would like to work on this issue under GSSoC'24.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05,

Hope you're doing well! I'd like to take on the assignment of enhancing the Contact Us section of the homepage. Given my experience as a content writer, having published over 30 articles on Asiana Times' website and completed numerous content writing internships, I believe I can add significant value to this task. Could you please allocate this to me with the GSSOC tag?

**Comment by sukritcharredsoul** [comment]
Thanks for assigning me this issue,

I have been tinkering for a good layout, I'll be sending a pull request
soon enough.
