### ISSUE TITLE
Changing background and text color at some places 

### ISSUE THREAD

**Issue by Vaishnavi1047** [khushi-joshi-05/Food-ordering-website#664]
Changing background and text color at some places as it seems unpleasant and disturbing.
![Screenshot 2024-05-30 185158](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149894552/2952a858-2c56-4e42-b8d6-34f6c1f4dd1e)

**Comment by Pratiksha03Ukarde** [comment]
CAN YOU PLEASE ASSIGN ME THIS ISSUE ?
