### ISSUE TITLE
add icon of foodie in the navbar

### ISSUE THREAD

**Issue by jayanththalla** [khushi-joshi-05/Food-ordering-website#665]
In the foodie logo is not there
please assign me @pa
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/121346142/64496b8f-2727-4e6b-aad4-5b1f32a69440)

**Comment by Shrutika006** [comment]
please assign it to me @khushi-joshi-05, im a beginner will try my best. Thankyou

**Comment by Salusha** [comment]
please assign it to me, i can even add fevicon.

**Comment by Salusha** [comment]
please assign it to me, I can even add favicon.
