### ISSUE TITLE
Bug : Remove Duplicate "Order Now" Buttons on Cart Page

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#668]
Currently there are 2 "Order Now" buttons present on our cart page, which can be confusing for users and negatively impact the user experience. We need to identify and remove the duplicate buttons while ensuring the remaining button is positioned correctly and functions as intended.

![Duplicate order now](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/61ac21af-fbed-4248-9490-9fe448ce14f0)

This needs to be resolved for best user experience. Please assign this issue to me.

@khushi-joshi-05 @sunny0625

**Comment by sunny0625** [comment]
This issue has been solved try to contribute to different issues!
