### ISSUE TITLE
Bug : Fix Misaligned Footer on Cart Page

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#669]
The footer on the cart page is misaligned and needs to be corrected to ensure consistency with the rest of the site. The current footer layout appears cluttered and uneven, impacting the overall aesthetics and user experience.

The footer should be aligned properly, with each section (Our Pages, Exclusive Offers, Payment Products, Contact Us) evenly spaced and formatted consistently. The "Follow Us" icons should be centered and the footer text should be clearly visible and aligned.

![bug - footer](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/57364809-16d9-44b2-8646-ef666ca5f63b)

This issue needs to be resolved. Please assign this issue to me.

@khushi-joshi-05 @sunny0625

**Comment by sunny0625** [comment]
This issue is already solved, try to contribute to different issues!
