### ISSUE TITLE
[BUG]: Small message box Size

### ISSUE THREAD

**Issue by aryansharma220** [khushi-joshi-05/Food-ordering-website#670]
The message box should be bigger so that it is easier for the user to see what they typed.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/133234867/fd9029f7-5175-4d01-beb1-594adec72554)

Please assign it to me under gssoc24

**Comment by DivyasreeDoppalapudi** [comment]
Can you please assign me this issue ?

**Comment by Salusha** [comment]
can you please assign this issue to me?
