### ISSUE TITLE
Update Copyright Year to Dynamic Value

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [khushi-joshi-05/Food-ordering-website#674]
Hey @khushi-joshi-05 

The current implementation of the copyright year in the footer is hardcoded, which requires manual updates each year. To improve maintainability and ensure the copyright year is always current, we need to update the code to dynamically generate the year using JavaScript. This change will automatically reflect the current year without the need for manual intervention.

**Comment by lovelymahor** [comment]
I would like to work on this issue Can u please assign me this issue
