### ISSUE TITLE
Adding the icon to set dark and bright theme for the website 

### ISSUE THREAD

**Issue by DivyasreeDoppalapudi** [khushi-joshi-05/Food-ordering-website#675]
We can add an icon to change the theme of website as per user's convenience

**Comment by DivyasreeDoppalapudi** [comment]
Can you assign me this issue ?

**Comment by n14rishitha** [comment]
Hi @sunny0625 

I would like to work on this issue . so please assign this task to me . I can complete this issue .

**Comment by sunny0625** [comment]
@DivyasreeDoppalapudi are you up for this issue!

**Comment by shraddhha** [comment]
Hi @sunny0625 
I'm a beginner looking to contribute to your project. I would like to work on this issue, and I assure that I will complete the task as soon as possible. Please assign me this issue under GSSOC.
