### ISSUE TITLE
Home page text not visible clearly

### ISSUE THREAD

**Issue by Athul28** [khushi-joshi-05/Food-ordering-website#678]
![Screenshot 2024-05-30 223738](https://github.com/khushi-joshi-05/Food-ordering-website/assets/79209367/50242de8-2430-4f9b-94e3-577df5381f14)

The text in the home page isn't clearly visible also the font style isn't matching the site, I will make the text visible clearly and change the font

Also I will improve the navbar to match the site theme

**Comment by sunny0625** [comment]
Update your issue to latest changes..!
