### ISSUE TITLE
Beautify NavBar 

### ISSUE THREAD

**Issue by sau-mili** [khushi-joshi-05/Food-ordering-website#68]
The present nav bar is not attractive. 
I wish to change the alignment, text effects, add shadow and icons of the navbar to make it more beautiful
Please assign me this

**Comment by sejal-sharma08** [comment]
I have worked on the project of food delivering website. I will be my pleasure  if you @khushi-joshi-05  choose me to solve this problem.

**Comment by MelissaSequeira** [comment]
I have worked on many web projects ......Plz assign me this task

**Comment by MelissaSequeira** [comment]
@khushi-joshi-05 
Also plz add level ,and gssoc label

**Comment by shmbhvi101** [comment]
Hi Khushi. I'm an experienced UI designer and i'm very fond of designing web pages. I have prior experience too. please assign this issue to me as a part of my GSSoC journey!

**Comment by raniafarooq** [comment]
The present nav-bar does not have good fonts and is very plain. What I'd suggest is to make the nav-bar sticky once the hero section is crossed. The nav-bar could use a light transparent background with a blur effect. Additionally, I think the nav bar should be centered in the middle to achieve a more professional look.
I request you to assign me this task, If you like what I I've suggested :)
Thanks and Regards

**Comment by Kash2612** [comment]
I came across your food delivery website and discovered that it lacks proper header designing as the font style is not very attractive it lacks links to login signup pages as well. Along with that I believe that adding hovering effects to the content would be more attractive.

I request you to kindly assign this task under GSSoC'24 as I have earlier worked on websites with responsive Navbars

**Comment by debiprasannadash** [comment]
Kindly assign this issue to me. I will try to modify the navBar and make it look attractive .

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05 
I'm interested in tackling the error in the GitHub repository for the Beautify NavBar project. Could you please assign this task to me?

**Comment by Gauri-Dabhade** [comment]
i would like to work on this,so could you assign this work to me

**Comment by Anu00009** [comment]
I have completed a project on food delivery website . As i have prior experience i want to fix this issue please assign me this task .

**Comment by sunny0625** [comment]
Give some Description. How do you want to change the NavBar?

**Comment by debiprasannadash** [comment]
@sunny0625 The NavBar should contain some theme and not be completely transparent and should have drop-down menu also giving customers a lot of options to choose from.

**Comment by sunny0625** [comment]
@khushi-joshi-05 check the suitable idea for your project.

**Comment by anshikatiwari20** [comment]
I noticed the issue and I believe I can help with it. Could you please assign this issue to me? I will try to resolve it as soon as possible.

**Comment by MrudulaTeegala** [comment]
@khushi-joshi-05 kindly assign this issue to me

**Comment by khushilatey16** [comment]
hey @khushi-joshi-05 pls assign this issue to me

**Comment by GarimaSingh0109** [comment]
Hi @khushi-joshi-05 I have made a designed a lot of web pages. I have good knowledge of HTML CSS JS and ReactJS. In this project the navbar needs to be aligned and made responsive. I have a lot of experience of using different framework like bootstrap material UI etc. I am willing to contribute to this project. Can you please assign me this task.
<img width="506" alt="food-ordering" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/130893914/f0e9b13e-7e4d-47c7-b34d-adb7f4f89003">

**Comment by khushi-joshi-05** [comment]
@GarimaSingh0109 I have assigned you the issue. After making changes, do attach a screenshot of it. Go ahead.

**Comment by sau-mili** [comment]
@khushi-joshi-05 I raised the issue.. so shouldn’t I be assigned this?
