### ISSUE TITLE
Bug : Text Color Matches the background color in Cart Page

### ISSUE THREAD

**Issue by jency1** [khushi-joshi-05/Food-ordering-website#680]
Currently the text color is not visible in the Cart Table in cart page. It matches the background color making it invisible. So user cannot read what's in the cart.

This needs to be resolved as soon as possible for best user experience.

Bug : 

![Text Color not visible](https://github.com/khushi-joshi-05/Food-ordering-website/assets/149723236/c91a4f34-b98b-4a29-aab3-53e458951dee)

Please assign this issue to me, As I would like to resolve this bug as soon as possible.

@khushi-joshi-05 @sunny0625

**Comment by sunny0625** [comment]
This issue is already solved!
try different issues!
