### ISSUE TITLE
[Feature]: Menu Cards UI enhancement

### ISSUE THREAD

**Issue by Sypher0Dronzer** [khushi-joshi-05/Food-ordering-website#685]
I want to improve the UI of the cards in the menu page 

this is the present UI
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/83546205/418f75e3-b551-41b1-912f-2ec7ddbb3e8b)

The following UI is close to what I wish to impliment 
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/83546205/6f91b19a-6dbf-4b5a-b279-35c5c7b803fb)

Please assign this issue to me @sunny0625

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by Sypher0Dronzer** [comment]
@Shubham-Zone bro I have already solved the issue
