### ISSUE TITLE
Bug: No Popup Or Alert When User Tries to login without Filling complete data

### ISSUE THREAD

**Issue by nishant0708** [khushi-joshi-05/Food-ordering-website#691]
Currently When user tries to login without filling every detail It is not alerting like No password found. Fill all details 
![Screenshot_5](https://github.com/khushi-joshi-05/Food-ordering-website/assets/101548649/6358f87d-63e2-431e-8bb1-0b5ed1d7b93b)
See No PopUp is coming

**Comment by Ananya2125** [comment]
I would like to contribute to this issue, under GSSOC'24. Kindly, assign it to me.
