### ISSUE TITLE
Adding light/dark mode 

### ISSUE THREAD

**Issue by kanishk-2** [khushi-joshi-05/Food-ordering-website#696]
Adding light/dark mode on website option for better ui.

**Comment by kanishk-2** [comment]
@khushi-joshi-05 @sunny0625 assign me this issue and add label of gssoc level-2

**Comment by kanishk-2** [comment]
@sunny0625  plz assign me this issue.

**Comment by kanishk-2** [comment]
Thank you @sunny0625 can you please add the level 2 label to this issue

**Comment by sunny0625** [comment]
> Thank you @sunny0625 can you please add the level 2 label to this issue

After PR.

**Comment by kanishk-2** [comment]
@sunny0625 This is the issue id for pr #971
