### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by Saimanjari777** [khushi-joshi-05/Food-ordering-website#701]
The navbar is not visible when scrolled down. I would like to make it fixed so that users can easily navigate.
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/130165687/4c6cccb4-69ec-4742-bd54-639922d33802)
Please assign this issue to me
I am working under GSSoC'24

**Comment by sohail0khan** [comment]
Hello,

I am new to open source and very excited to contribute. I would love to work on this project. Could you please assign this issue to me?

**Comment by CommandoNK18** [comment]
I am good in Front-end ,
Please assign this issue to me.
I am working under GSSoC'24 .
