### ISSUE TITLE
"View Our Menu" in the Home Page Not Pointing to the Menu

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [khushi-joshi-05/Food-ordering-website#716]
Hey @khushi-joshi-05 

The "View Our Menu" button on the website is not correctly linking to the menu section. This issue needs to be addressed to ensure that users can easily navigate to the menu from the button.

**please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
