### ISSUE TITLE
Sticky Navbar Header

### ISSUE THREAD

**Issue by Che140401** [khushi-joshi-05/Food-ordering-website#718]
Sticky Navbar is best for user interface to access user anywhere

https://github.com/khushi-joshi-05/Food-ordering-website/assets/109230049/04b3e125-917e-4dca-8020-683ceaf86095

We dont have sticky header

https://github.com/khushi-joshi-05/Food-ordering-website/assets/109230049/f846b1d1-4b4e-46e9-ab0a-0ea479ab4738

**Comment by chitraa-cj** [comment]
please assign this issue to me

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
