### ISSUE TITLE
Improving overall UI of the website 

### ISSUE THREAD

**Issue by Dhanika29** [khushi-joshi-05/Food-ordering-website#72]
Hey ,I would like you to assign this issue to me .I would like to improve the ui and contribute to it.

**Comment by shmbhvi101** [comment]
Hi Khushi. I'm an experienced UI designer and i'm very fond of designing web pages. I have prior experience too. please assign this issue to me as a part of my GSSoC journey!

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05, I'd love to take on the task of enhancing the website's overall UI. Could you please assign this to me with the GSSOC tag? Thanks!

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.I have prior experience too as I have made 20+ Full-stack projects.
