### ISSUE TITLE
Correct Input Type for Phone Number in Book Table Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [khushi-joshi-05/Food-ordering-website#722]
Hey @khushi-joshi-05 

The current form in book table page uses type="number" for the phone number input field. This can cause issues with input formatting and user experience, particularly on mobile devices.

To improve the form's usability and compatibility, we need to change the input type from number to tel. This change will enable users to input their phone numbers more efficiently and will allow for better formatting and handling across different devices.

**Please add the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by Henin-6024** [comment]
I would like to fix this issue #722 . Please assign this task to me under GSSoC'24 with required labels.

**Comment by sunny0625** [comment]
@SaiTejaswaniBikkasani are you up for Issue?

**Comment by sunny0625** [comment]
Why create spam issues?

**Comment by SaiTejaswaniBikkasani** [comment]
@sunny0625 , yeah I am working on it

**Comment by SaiTejaswaniBikkasani** [comment]
@sunny0625 , what is spam issues..?

**Comment by sunny0625** [comment]
> @sunny0625 , what is spam issues..?

What is this #770 ?
