### ISSUE TITLE
BUG: PERFECT  IMAGE FOR CARDS NEEDED ,ADDITON OF SMOOTH HOVERING EFFECT ON CARDS 

### ISSUE THREAD

**Issue by Nih1tGupta** [khushi-joshi-05/Food-ordering-website#723]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/119615342/f8f9c849-ffc3-42ea-92c3-e357b1ceef0b)

**Comment by Nih1tGupta** [comment]
Font and background can be improved too. @sunny0625 . Kindly consider this issue

**Comment by sunny0625** [comment]
Do change according to the latest website.
