### ISSUE TITLE
Bug: In the home section

### ISSUE THREAD

**Issue by shruti-mishraa** [khushi-joshi-05/Food-ordering-website#727]
when we are on the home section and clicking on the home button the the error is shown.
for your reference I have provided You a video.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/92870611/8cd27bfe-78ea-468b-bfde-fdf8afbf983b

let me Work on the issue.

**Comment by shruti-mishraa** [comment]
@khushi-joshi-05 let me work the issue.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by sunny0625** [comment]
No such issue was found on the deployment link.
