### ISSUE TITLE
Enhancement [dark mode]

### ISSUE THREAD

**Issue by rajlaxmi03** [khushi-joshi-05/Food-ordering-website#73]
Enhancement [dark mode]

**Comment by Sibam-Paul** [comment]
Please assign this to me. as I want to work on this issue

**Comment by iamrudhresh** [comment]
Please assign this issue to me under gssoc'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24. I have used it in one of my projects and can work on it.

**Comment by GAGGZ1** [comment]
I've implemented this feature in my previous projects, showcasing my ability to enhance user experience through customization. With my expertise in front-end development, I'm confident I can integrate this feature smoothly into your project.

@khushi-joshi-05 could you please assign me

**Comment by anshig135** [comment]
I've recently raised a PR in a project on the same issue and showcased my skills on the same. I request you to kindly assign me this project under GSSOC'24.

@khushi-joshi-05 can you please assign me this issue
