### ISSUE TITLE
Redesigning Navbar

### ISSUE THREAD

**Issue by AsmitaMishra24** [khushi-joshi-05/Food-ordering-website#733]
Description:
I am interested in redesigning the navigation bar to improve its look and align it with the website's color theme.

Screenshot of my previous work:
![Screenshot 2024-05-25 004232](https://github.com/khushi-joshi-05/Food-ordering-website/assets/146121869/6cd642c2-3e20-4cf2-82fc-e0b1d376fa8e)

By redesigning the navigation bar, I aim to enhance the overall look of the website and ensure a cohesive color theme.

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by AsmitaMishra24** [comment]
@sunny0625, i will submit PR in next 2 days
