### ISSUE TITLE
feat: adding pre loader 

### ISSUE THREAD

**Issue by solanki505** [khushi-joshi-05/Food-ordering-website#735]
A pre loader is an essential interface element that appears on a web page while its content is being loaded
I would like to add pre loader to make the web page more interactive
<img width="243" alt="Screenshot 2024-06-01 074011" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/158484284/5fc339c3-6bef-4d88-94ca-b1e1a3b1d743">
 Please assign me this issue under GSSOC.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
