### ISSUE TITLE
Hamburger menu is not working

### ISSUE THREAD

**Issue by K-kiran77** [khushi-joshi-05/Food-ordering-website#736]
when i click on the hamburger icon it is changing to cross icon but the nav links are not opening

Could you please assign me this issue under GSSoC 2024

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
