### ISSUE TITLE
Creating Social Media accounts

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#739]
Icons of facebook, instagram and other icons does not contain the original website links. So if you provide the links , then I can make them functional or else you can share the details, so that I can create accounts .
This will provide users with easy access to our social media profiles and improve engagement.
Could you please assign this issue to me under GSSoC'24?

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
