### ISSUE TITLE
Make the search bar work more efficiently 

### ISSUE THREAD

**Issue by rajlaxmi03** [khushi-joshi-05/Food-ordering-website#74]
Make the search bar work more efficiently

**Comment by KhushAgrawal001** [comment]
Assign this to me i can exell in expectations and solve this issue as my GSSoC'24 Participation.

**Comment by debiprasannadash** [comment]
Adding a voice search in the search bar will look much better

**Comment by rajlaxmi03** [comment]
I would like to work on my issue and contribute to this project

**Comment by debiprasannadash** [comment]
Kindly assign this issue to me. I would love to work to make the best modification of the search bar.
Adding a voice search in the search bar will look much better.

**Comment by Diwakar124** [comment]
hello, I want to add the search button on the top of the website Kindly assign the project.
