### ISSUE TITLE
Menu Page UI Enhancement 

### ISSUE THREAD

**Issue by GarimaSingh0109** [khushi-joshi-05/Food-ordering-website#740]
The current menu page user interface (UI) needs improvement to enhance the user experience.

Details:

Describe the specific UI elements that you find lacking. This could include:

Poor organization of menu items
Unintuitive navigation (scrolling, filtering)
Inconsistency with the overall website design
Impact:- 
Users might be frustrated if they can't easily find the items they're looking for.
The user might be overwhelmed by a cluttered design.
Users might not understand the pricing information due to poor presentation.
Desired Outcome:
A design that is consistent with the overall brand identity.

<img width="940" alt="foodie_menu_issue" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/130893914/0ebcf50e-dbe2-443d-9975-464c68edf529">

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
