### ISSUE TITLE
Menu Filter Functionality

### ISSUE THREAD

**Issue by GarimaSingh0109** [khushi-joshi-05/Food-ordering-website#741]
The current menu does not have filter functionality that hinders efficient browsing.
Impact - 
Users with dietary restrictions have difficulty finding suitable options.
Users spend extra time trying to understand and use the filters.
Users may miss out on desired menu items due to inaccurate filtering.
It's unclear which filters are currently active, making it difficult to adjust selections.
Desired Outcome:
Offer a variety of relevant filter options for dietary needs, price, meal type, etc.
Employ a clear and intuitive interface that is easy to understand and navigate.
Filters should accurately display menu items based on the selected criteria.
Visual cues like checkboxes or highlighted buttons should show active filters.
Allow users to combine multiple filters seamlessly without unexpected results.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development
