### ISSUE TITLE
Enhancement of navbar

### ISSUE THREAD

**Issue by harinisayani** [khushi-joshi-05/Food-ordering-website#747]
I want to add icons to navbar and making it look good by adding CSS features.
I am GSSOC'24 contributor.
Please assign me this issue.
I want to work on this issue.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by sunny0625** [comment]
@Shubham-Zone go ahead!

**Comment by Shubham-Zone** [comment]
@sunny0625 thankyou for the opportunity
