### ISSUE TITLE
Addd social media and feedback section in blog page 

### ISSUE THREAD

**Issue by rajlaxmi03** [khushi-joshi-05/Food-ordering-website#75]

**Comment by KhushAgrawal001** [comment]
I can solve this issue as part of my GSSoC'24 Journey.

**Comment by paridhi1509** [comment]
I would like to work on this issue

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @khushi-joshi-05,

I hope you're doing well! I'd like to take on the task of adding a social media and feedback section to the blog page. With my experience as a content writer, I've authored and published over 30 articles on Asiana Times' website and have completed numerous content writing internships. I believe I can effectively enhance the blog's functionality and engagement. Could you kindly assign this task to me with the GSSOC tag?

**Comment by sunny0625** [comment]
This issue has been solved, Try to participate in different issue!
