### ISSUE TITLE
Adding linkedin link in footer section.

### ISSUE THREAD

**Issue by harinisayani** [khushi-joshi-05/Food-ordering-website#750]
I want to add linkedin link in footer section.
Please assign me this issue.
I want to work on this issue.
I am GSSOC'24 contributor.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05  please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by khushizz** [comment]
I would like to work on this feature as a GSSOC contributor. Please assign it to me.

**Comment by reashav7** [comment]
I want to work on this issue, please assign it to me.

**Comment by aditi29400** [comment]
please assign

**Comment by sunny0625** [comment]
#835
