### ISSUE TITLE
Aligning items to center in service page

### ISSUE THREAD

**Issue by harikasayani** [khushi-joshi-05/Food-ordering-website#755]
I am GSSOC'24 Contributor.
I want to align items to center in service page.
Please assign me this task.
I want to work on this issue.

**Comment by Shubham-Zone** [comment]
@khushi-joshi-05 please assign this to me i am GSSOC'24 contributor with 2+ years of experience in development

**Comment by khushi-joshi-05** [comment]
@harikasayani also can u set the background correctly on service page?

**Comment by harikasayani** [comment]
Ok
