### ISSUE TITLE
Add a Nav bar that disappears when u scroll down.

### ISSUE THREAD

**Issue by shmbhvi101** [khushi-joshi-05/Food-ordering-website#76]
Please assign me i would like to resolve this issue for GSSoC'24.
i have previously done this for my website too. I'm proficient in Bootstrap, HTML, CSS, React, and JavaScript, and this is an extremely easy task that i'd love to take up!!

**Comment by MelissaSequeira** [comment]
Plz ass me this task....for i done it previously

**Comment by GarimaSingh0109** [comment]
@khushi-joshi-05 I have used similar feature in one of my projects I can resolve this issue using CSS kindly assign me the task under #gssoc'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24. I am used it in one of my projects and can work on it.
