### ISSUE TITLE
Bug: Solve Nav Bar on Home Page

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#763]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/a54b4322-374d-43e0-9af4-867e37e2f0e1)

As the Nav Bar goes out on the home page.

**Comment by khushizz** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by kashvi9** [comment]
Hello @sunny0625 
Please assign me this issue under GSSOC'24
Thank You!

**Comment by DevGajjar28** [comment]
@sunny0625  I would like to work on this issue. Please assign it to me.

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by lovelymahor** [comment]
I would like to work on this issue Can u please assign me this issue?

**Comment by praveen30021** [comment]
@sunny0625 I would like to work on this issue. Please assign it to me.

**Comment by sunny0625** [comment]
@khushizz did you up for this issue..?
