### ISSUE TITLE
FEATURE: Want to add Catering Services for events.

### ISSUE THREAD

**Issue by kdanjana** [khushi-joshi-05/Food-ordering-website#764]
Want to create a new page - CateringServices.html that includes 3 types of catering services:
1. Wedding Catering Service
2. Corporate Catering Service
3. Birthday Catering Service
In the service.html(below page) when you click on the Book Catering, the catringservices.html will be displayed.
<img width="728" alt="1" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/103878831/23963037-8054-48a1-8d48-cc6aea066021">
I will make sure the newly added cateringservices.html UI will look like part of website,
Please assign it to me under GSSOC2024.

**Comment by khushi-joshi-05** [comment]
@kdanjana  i have assigned u this issue.  Go ahead.

**Comment by kdanjana** [comment]
@khushi-joshi-05   I have made a PR mentioning this issue.  PR: #768
