### ISSUE TITLE
Fix Missing Logo and Website Name on Cart Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [khushi-joshi-05/Food-ordering-website#771]
Hey @khushi-joshi-05 

The cart page currently has the following issues that need to be addressed:

- The logo is not displayed, which affects the visual branding and user experience.
- The website name is not prominently displayed, which can cause confusion for the users.

Currently, the cart page looks like:
![Screenshot 2024-06-01 171936](https://github.com/khushi-joshi-05/Food-ordering-website/assets/159511364/f69447f7-d7ef-4f23-921b-81cccd0c0326)

**Please assign the required labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
