### ISSUE TITLE
CARDS OF DISHES 

### ISSUE THREAD

**Issue by PacemakerX** [khushi-joshi-05/Food-ordering-website#78]
Would like to add cards like menu option to the website, by which they can get an idea, what the food ordering website has to offer

**Comment by PacemakerX** [comment]
i have already made a website comprising of a restaurant  , you can check and check my skill set and credibility @sanjay-kv  assign this issue to me

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
