### ISSUE TITLE
Missing of Favicons to the below pages

### ISSUE THREAD

**Issue by Anjaliavv51** [khushi-joshi-05/Food-ordering-website#782]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/01ed81fd-4cc1-421c-b82b-4fcc48806539)

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/ab8d75a9-2590-4282-b7b2-ac7cac3ce770)

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/9b179b5d-b52a-44f2-accb-33c4712b518a)

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/f0b97aec-6b2e-4e72-b631-1441cc56f13f)

**Comment by Anjaliavv51** [comment]
@khushi-joshi-05

**Comment by S-i-y-a-g** [comment]
please assign me this issue @sunny0625
