### ISSUE TITLE
proper cursor to login and sign up (hovered)

### ISSUE THREAD

**Issue by NeerajaGurram** [khushi-joshi-05/Food-ordering-website#783]
current cursor on hovering login and sign up looks like it is for a text input field
you can see the difference in the cursors between home,menu and login, sign up in the video below:

https://github.com/khushi-joshi-05/Food-ordering-website/assets/152693538/de79f306-cd5e-4270-a773-5e8b2de873cc

 i would like to change the cursor which looks the same as the cursor for home,menu while hovering.
i would like to work on this under gssoc . please assign me this and give the gssoc and appropriate label to it .
thankyou

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
