### ISSUE TITLE
Bug: Fix Responsiveness of Customer Review Section

### ISSUE THREAD

**Issue by DebapriyaJha** [khushi-joshi-05/Food-ordering-website#788]
The customer review section on the homepage is currently not responsive, causing layout issues on different screen sizes. I plan to make the necessary adjustments to ensure that this section displays correctly on all devices, providing a consistent user experience.

![responsive](https://github.com/khushi-joshi-05/Food-ordering-website/assets/111692420/0427975f-79b2-471a-a1ad-fa88643846d7)

@khushi-joshi-05  Please assign this task to me. I would love to contribute. Also please assign the gssoc24 and appropriate level labels to this task.

**Comment by DebapriyaJha** [comment]
@sunny0625 Can you Please add the appropriate level label to this issue as it would help me to rank in leaderboard.

**Comment by sunny0625** [comment]
After PR.

**Comment by DebapriyaJha** [comment]
@sunny0625 Please have a look at my PR, assign it to the appropriate gssoc level label, and please merge it.

**Comment by sunny0625** [comment]
see your changes in 😎 Deploy Preview.
