### ISSUE TITLE
Our pages in Footer section should contain clickable links

### ISSUE THREAD

**Issue by K-kiran77** [khushi-joshi-05/Food-ordering-website#79]
If the list items of Our Pages unordered list in the footer section are clickable links to the sections mentioned by the list item will increase user experience, I can solve the issue by adding clickable links to the list items by adding destination addresses to the anchor tags

kindly assign me this to solve the issue under GSSoC 2024
My userid is @K-kiran77

**Comment by K-kiran77** [comment]
Could you please assign me this project to solve the issue that i raised

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by SougataXdev** [comment]
@K-kiran77  please assign this task to me

**Comment by sunny0625** [comment]
This issue has been solved, Try to participate in different issue!
