### ISSUE TITLE
linking "view our menu" button 

### ISSUE THREAD

**Issue by nandani-goyal** [khushi-joshi-05/Food-ordering-website#791]

**Comment by nandani-goyal** [comment]
![Screenshot 2024-06-01 192650](https://github.com/khushi-joshi-05/Food-ordering-website/assets/152094228/153cb9eb-e306-4798-9106-7ccb131652af)
the view menu button on clicking is not taking the user to the menu rather it is moving the page upwards.
I can link it to the menu button.
please assign me this under gssoc'24.

**Comment by Pratiksha1661** [comment]
Please assign me this issue under gssoc'24

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
