### ISSUE TITLE
STYLE: The title of the cuisines isn't properly visible.

### ISSUE THREAD

**Issue by vaishali-gupta32** [khushi-joshi-05/Food-ordering-website#794]
The title in the different cuisine boxes is not properly visible as the background and the font colour is non-differentiating. 

![Screenshot 2024-06-01 211444](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144541888/1d7c7684-694c-445e-9859-149c43922fb8)

![Screenshot 2024-06-01 211444](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144541888/d2d9f1e3-3de9-4b6c-8089-9ce3825c460c)

**Comment by vaishali-gupta32** [comment]
@khushi-joshi-05 please assign this issue to me. I am willing to contribute to this. Also, please label it.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
