### ISSUE TITLE
BUG: after clicking "view more menu" button  its show  error page

### ISSUE THREAD

**Issue by shuhaki** [khushi-joshi-05/Food-ordering-website#803]
after clicking "view more menu" button  its show  error page. it's show this

<img width="640" alt="Screenshot 2024-06-02 at 12 46 47 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/145912232/08beaf5f-67d0-427f-850e-f6d002d2d02c">

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
