### ISSUE TITLE
BUG : Responsive NavBar

### ISSUE THREAD

**Issue by KomalMaurya** [khushi-joshi-05/Food-ordering-website#807]
Nav Bar is not responsive for all screen sizes as for tablet size the nav bar disappears completely.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/145214525/5167fd9b-b360-4419-9cc3-5678107b35da

Name: Komal Maurya
GitHub profile link: https://github.com/KomalMaurya
Email ID: komal092btcseai23@igdtuw.ac.in
Role: GSSoC-2024 contributor

 
The Nav Bar is not responsive for all screen sizes so I would request you to assign me under the GSSOC 2024 and with level.
Can you assign it to me? @khushi-joshi-05
Thank You.

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor, I have good experience in frontend designing I can make it more visually appealing please assign me this issue under GSSOC 2024

**Comment by KomalMaurya** [comment]
@sunny0625 I requested a PR which fixed this issue #807. Kindly Please review it and inform about it.
