### ISSUE TITLE
Enhancement Proposal: Navbar Styling & Homepage Carousel

### ISSUE THREAD

**Issue by harithaguna** [khushi-joshi-05/Food-ordering-website#81]
I propose beautifying the navbar with alignment and styling enhancements. Additionally, suggesting the integration of a dynamic carousel on the homepage for improved visual appeal and engagement. Eager to contribute, please assign this task to me.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @khushi-joshi-05  I'd love to take on the Enhancement Proposal for Navbar Styling & Homepage Carousel. Could you please assign this task to me with the GSSOC tag?
