### ISSUE TITLE
Issue: Subscription Page Layout Problem

### ISSUE THREAD

**Issue by Amulya-Codes** [khushi-joshi-05/Food-ordering-website#810]
Hello Mentor,

On the subscription page of the Foodies Ordering website, there is a layout issue where the text for the regular membership is not confined within its designated box. Instead, the text overflows and overlaps with other elements on the page, causing readability and usability problems.

![Screenshot (1104)](https://github.com/khushi-joshi-05/Food-ordering-website/assets/118996055/f5152b05-b507-4dd3-8375-51f7483ad5af)

**Comment by sunny0625** [comment]
@Amulya-Codes make them responsive.
