### ISSUE TITLE
Add Scroll Animation for Enhanced User Experience

### ISSUE THREAD

**Issue by Skb08** [khushi-joshi-05/Food-ordering-website#811]
As part of GSSoC '24, I propose adding animations triggered by scrolling to enhance the user experience. This feature will provide a more engaging and interactive interface for users. I have attached a demo video below to illustrate the desired effect.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/113046759/710ce8af-fb35-4789-a9af-9358bf98d66b

**Comment by sunny0625** [comment]
@Skb08 Go ahead..!
