### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by sunny0625** [khushi-joshi-05/Food-ordering-website#814]
Description:
- Update the Screenshot of the Website in Readme.md

**Comment by kdanjana** [comment]
@sunny0625 Assign this to me, I will update the website screen shots in the readme .

**Comment by kdanjana** [comment]
@sunny0625  I have updated readme.md .
I have added new page -cateringServices.html, (fixes: #764 ) , should I include this screenshot also in the readme?
