### ISSUE TITLE
FAQ section is missing

### ISSUE THREAD

**Issue by nehal1222** [khushi-joshi-05/Food-ordering-website#820]
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/119063830/9010dd52-7608-4594-b6ee-8938aca46581)
We can add a page like this.

**Comment by nehal1222** [comment]
Hey, Please allow me to resolve this issue.



thank you

**Comment by sunny0625** [comment]
currently, this issue is assigned #101

**Comment by sunny0625** [comment]
@nehal1222 work on this issue!

**Comment by nehal1222** [comment]
yes sir...i a making the changes
