### ISSUE TITLE
Feat :  Autocomplete Search Bar in navbar

### ISSUE THREAD

**Issue by MavSneha** [khushi-joshi-05/Food-ordering-website#83]
# I would like to work on this @khushi-joshi-05  below is the feature description

# Feature Description :

**1. Adding a search icon in the navbar**
**2. Auto-complete search bar**

# Idea visualization :

![search bar](https://github.com/khushi-joshi-05/Food-ordering-website/assets/130782754/4da439df-a08b-47e0-a51d-66f9a0235428)

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.
