### ISSUE TITLE
Update Copyright Year Dynamically in Footer.

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [khushi-joshi-05/Food-ordering-website#84]
Hey @khushi-joshi-05, The current copyright year in the footer section of the website is hardcoded in the HTML tag and is not updated to 2024. To ensure that the copyright year is always up to date, I propose to modify the HTML code to dynamically update the year to the current year. This will improve the accuracy and professionalism of the website. **Please** **assign the label** **and assign me this work under GSSOC'24**. Thank you!!

**Comment by saketh-05** [comment]
I want work to improve this feature. Please assign me the work.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05 

I hope you're doing well! I'd like to take on the task of updating the copyright year dynamically in the footer. It's an important feature that ensures our website stays current and compliant. Could you please assign this task to me with the GSSOC tag? I'm excited to contribute to the project!
