### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by MuraliDharan7** [khushi-joshi-05/Food-ordering-website#843]
Add FAQ Section

Improve user experience by providing a dedicated section for Frequently Asked Questions (FAQs).
Increase user self-service by addressing common questions and reducing support load.

Please assign this issue to me under GSSoC'24. Add relevant labels into it.

**Comment by abhisek2004** [comment]
i want to add some task and also want to work in it

**Comment by dakshika-chaudhary** [comment]
@khushi-joshi-05 and @sunny0625 
kindly assign this issue to me i can add frequently asked questions feature to with a beautify design
