### ISSUE TITLE
[Bug] : Service Card have extra image in the end of card

### ISSUE THREAD

**Issue by dhruv8433** [khushi-joshi-05/Food-ordering-website#857]
@khushi-joshi-05 

check this ,

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/114583978/c0d964f6-dc3c-48de-a711-b84a84aa677d)

in the second card's bottom have some unnecessary image

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
