### ISSUE TITLE
[Bug] : Footer Style changed in service page

### ISSUE THREAD

**Issue by dhruv8433** [khushi-joshi-05/Food-ordering-website#858]
@khushi-joshi-05 
@sunny0625 

check this out,
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/114583978/ad5accc1-d0f1-467b-9213-5ef047754c40)

footer style changed in service page

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
