### ISSUE TITLE
Hover Effect-Fixing

### ISSUE THREAD

**Issue by SuhainaFathimaM** [khushi-joshi-05/Food-ordering-website#86]
Hovering Effect is not clear and it can be improvised..
Please Assign me this issue.. 
I will work on it
Also label it as GSSoC

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task for GSSoC 24.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by gargimukherjee25** [comment]
Hello I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by T1rth1** [comment]
heyy @i would like to work upon this issue. can you please assign me this issue...

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05, hope you're doing well! I'd like to tackle the Hover Effect-Fixing assignment. Could you please assign this task to me with the GSSOC tag? Looking forward to contributing!

**Comment by royalrajputayush** [comment]
I want to work on this issue, please assign me this under gssoc'24- level 2.
