### ISSUE TITLE
BUG: Different Font Size and Font Style of NavBar on Each Page

### ISSUE THREAD

**Issue by Vibhu315** [khushi-joshi-05/Food-ordering-website#867]
### Navbar Bug

#### In the Website different Pages have different Font Size and Font Style of the Navbar.

When we move from one page to another the font style and font size of navbar changes.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/93249125/dc254164-ce5e-4799-bdd6-f6556cc7aeb1)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/93249125/bca8d970-4766-4e20-84dc-74af496473b8)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/93249125/c0af12df-c520-4926-8902-e0bd1b806144)

 - [x] GSSOC24

- [x]  I follow [CODE_OF_CONDUCT](https://github.com/khushi-joshi-05/Food-ordering-website/blob/main/CODE_OF_CONDUCT.md) of this project

**Comment by Vibhu315** [comment]
Hey @khushi-joshi-05 ,
I would like to work on this issue.
Please assign me this issue.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
