### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by mehrun171** [khushi-joshi-05/Food-ordering-website#871]
Footer page under services isn't fitting the footer section and looking awkward...it need to be fixed and all the text , links, send message section can be redesigned...
![Screenshot 2024-06-03 131144](https://github.com/khushi-joshi-05/Food-ordering-website/assets/116735695/77026985-47b2-4d99-83f0-2711932476eb)

**Comment by mehrun171** [comment]
Please assign me this issue @khushi-joshi-05

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
