### ISSUE TITLE
Incorrect Images in Menu Sections

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#879]
The images in the menu are not according to the section names. 
For instance, the juice section contains images of thali, dessert, and snacks.
 I would like to edit the images of each section to ensure they match the section names.
@sunny0625 Sir,  Please assign this issue to me under GSSoC'24.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/d9fdeda0-a323-4795-a201-c03f124ac663)

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
