### ISSUE TITLE
Alignment and Punctuation Issues in Text

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#880]
The text in the image used for the menu has alignment and punctuation issues.
 The current text is not properly aligned, and the punctuation could be improved for better readability.
Please assign this issue to me under GSSoC'24.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/ee0d5dc7-84fe-477c-9b96-d7777eb44c8a)

**Comment by nileshsn** [comment]
Assign me I will work. @khushi-joshi-05
