### ISSUE TITLE
Spelling Mistake in Menu Text

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#881]
There is a spelling mistake in the menu text. The word "memotries" should be corrected to "memories."
Please assign this issue to me under GSSoC'24.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/5857d495-667e-41a0-bb4f-e0d33f7c613c)

**Comment by Aashka19** [comment]
Hey could you please assign me this issue under GSSOC 24, I would be happy to contribute!
