### ISSUE TITLE
Adding social media accounts

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#882]
Icons of facebook, instagram and other icons does not contain the original website links. So if you provide the links , then I can make them functional or else you can share the details, so that I can create accounts .
This will provide users with easy access to our social media profiles and improve engagement.
Could you please assign this issue to me under GSSoC'24?

**Comment by sunny0625** [comment]
@khushi-joshi-05 will give the social media handles.

**Comment by TBorundia** [comment]
> @khushi-joshi-05 will give the social media handles.

@khushi-joshi-05 Mam, please provide details so that I can link them.
