### ISSUE TITLE
"Contact Us" Link Incorrectly Points to Offer Page

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#883]
There is a bug on the website where the "Contact Us" link is incorrectly linked to the "Offer" page. 
This issue needs to be resolved to ensure that the "Contact Us" link points to the correct "Contact Us" page.
I would like to work on this issue under GSSoC'24. Please assign this issue to me.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/ac99650c-93ce-47ad-af0e-f0bedf8cd4be

**Comment by sunny0625** [comment]
solve navbar problem for navigation.
