### ISSUE TITLE
Typo in Readme File regarding the Git-Clone command 

### ISSUE THREAD

**Issue by ananyabansal16** [khushi-joshi-05/Food-ordering-website#889]
The HTTPS url is incorrect in the ReadMe
![Screenshot 2024-06-03 at 7 49 52 PM](https://github.com/khushi-joshi-05/Food-ordering-website/assets/95698522/ac99d08d-219d-4842-a4f6-199953411346)
where it should be https://github.com/khushi-joshi-05/Food-ordering-website.git

Kindly assign this to me under GSSoC'24 so that I can fix this bug immediately.

**Comment by jethasriM** [comment]
please assign this issue to me

**Comment by Sneha0019** [comment]
I will do it in a single day. Please assign it to me under GSSOC'24!

**Comment by atharvakej** [comment]
@ananyabansal16 we need to make a fork first then clone the repo, not the actual repo. So we need to make changes in readme as first fork the repo then clone it. @sunny0625
