### ISSUE TITLE
Improve footer.

### ISSUE THREAD

**Issue by soniya-malviy** [khushi-joshi-05/Food-ordering-website#900]
Add styling in footer for enhance website.
![Image 04-06-24 at 1 13 AM](https://github.com/khushi-joshi-05/Food-ordering-website/assets/151515611/66b4a9ec-1026-480e-a991-66ef5bb9e8f7)

**Comment by Shresthasamanta** [comment]
@sunny0625 @khushi-joshi-05 I want to work on this project. So kindly assign me this issue I will work on it . Add gssoc and level label to it.
