### ISSUE TITLE
BUG - in navigation bar

### ISSUE THREAD

**Issue by Harleen-786** [khushi-joshi-05/Food-ordering-website#91]
Describing the bug
When navigating from the navigation bars on index.html page to the menu.html or services.html or cart.html or contact.html the user is not directed to the particular section as expected.

Expected behavior
Clicking on the navigation bars  on the index.html page should take the user back to the particular section to the other menu.html , contact.html , cart.html.

Screenshots : 
![bug](https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/3f439c87-fff8-4e50-9e89-2755355382a7)

![bug1](https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/a2a49b7c-7a87-45f2-8972-cbeb7a50cd59)
![bug2](https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/db4fc67c-f268-41ff-b46d-e4f88c7e1093)
![bug3](https://github.com/khushi-joshi-05/Food-ordering-website/assets/109780561/016f0d32-f29d-4c79-b3d1-867fecacfafe)

I am contributing under GSSoc24 open source Program .Please assign me this issue.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05 I'm ready to tackle the bug in the navigation bar. Could you assign me this task with the GSSOC tag?

**Comment by Shivangbarnwal** [comment]
I can fix this issue. Please assign this to me under GSSoC 24. Also, the links open in a new tab each time we click a navbar link which creates a mess in the tab bar of user's browser which does not feel good. I can take care of that too.

**Comment by Harleen-786** [comment]
@khushi-joshi-05 please assign me this issue  as i have discussed and issued above.

**Comment by sunny0625** [comment]
This issue has been solved, Try to contribute to other recent issues!
