### ISSUE TITLE
creating a footer and navbar in login page

### ISSUE THREAD

**Issue by Its-your-rj** [khushi-joshi-05/Food-ordering-website#913]
<img width="921" alt="Screenshot 2024-06-04 105113" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/131703345/d11c9129-709e-464e-83b4-95d43f4705dd">

Login page in this website lacks footer and navbar please assign me this task to update the page with improved styling

**Comment by Its-your-rj** [comment]
@khushi-joshi-05 please assign me this tasks under GSSOC'24

**Comment by khushi-joshi-05** [comment]
@Its-your-rj go ahead

**Comment by Its-your-rj** [comment]
@khushi-joshi-05 Thank you
