### ISSUE TITLE
Bug: Service Page footer not Covering Entire Page

### ISSUE THREAD

**Issue by TBorundia** [khushi-joshi-05/Food-ordering-website#916]
The service page does not cover the entire viewport, resulting in an incomplete display of the content.
I want to fix this issue under GSSoC'24, can you please assign it to me?

![Screenshot 2024-06-04 111751](https://github.com/khushi-joshi-05/Food-ordering-website/assets/168854094/b5446285-4302-4037-a19e-bfe0df774833)

**Comment by Aashka19** [comment]
Hey could you please assign me this issue under GSSOC 24, I would be happy to contribute!

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
