### ISSUE TITLE
Add validation for email and password fields

### ISSUE THREAD

**Issue by geoffgeorgein** [khushi-joshi-05/Food-ordering-website#924]
![Screenshot 2024-06-04 143541](https://github.com/khushi-joshi-05/Food-ordering-website/assets/52931060/60a18f76-bbc6-4abb-8afc-8a013d3f90f8)

The email and password fields in the login page are lacking client side validation. I can add that.

**Comment by sakshi261203** [comment]
Could you please assign this to me **@sunny0625**
