### ISSUE TITLE
Improvement in the design of both the navbar and buttons on the website.

### ISSUE THREAD

**Issue by ridimagarg28** [khushi-joshi-05/Food-ordering-website#93]
![Screenshot 2024-05-11 002927](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128244696/011e08fb-1740-41e7-ab0e-39eb2ce2cd58)
I can enhance the appearance of all buttons on the site, including the navbar of the page. I'll add a hover effect to make them more interactive. I'll ensure proper alignment of the items, and when users scroll down, the navbar will remain fixed at the top with a blur effect.

**Comment by FatemaBaig** [comment]
i would like to work on this part of project.  Please assign it to me.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @khushi-joshi-05 I'm enthusiastic about enhancing the design of both the navbar and buttons on the website. Could you please assign me this task in the GitHub repo?
