### ISSUE TITLE
Improvement of footer of Services page.

### ISSUE THREAD

**Issue by tanushri1506** [khushi-joshi-05/Food-ordering-website#931]
![issue1](https://github.com/khushi-joshi-05/Food-ordering-website/assets/125864601/29b68c17-2c50-4faa-975d-195e656ff1cf)

I will improve the footer part of Services page.
Please assign this issue to me with the labels.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
