### ISSUE TITLE
Improvement of footer of Services page

### ISSUE THREAD

**Issue by KHU-SHIGUPTA** [khushi-joshi-05/Food-ordering-website#935]
![servicepage](https://github.com/khushi-joshi-05/Food-ordering-website/assets/165371975/e09c580c-5871-4d25-a35b-fabdc6eeb6ee)
 The footer on the Services page is not covering the entire screen. It needs adjustment.

**Comment by KHU-SHIGUPTA** [comment]
@khushi-joshi-05 please assign this issue to me under GSSoC'24

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
