### ISSUE TITLE
image not visible in Menu file and addition of scroball to all HTML files in Repo

### ISSUE THREAD

**Issue by Anjaliavv51** [khushi-joshi-05/Food-ordering-website#936]
Bug [image not visible in Menu file] :

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/cd55438b-c701-47ff-b30c-94ae4d703fd3)

Feature[addition of scroball to all HTML files in Repo]:

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/c088adb8-68ed-4cb1-a55f-1894deadb018)

PLease assign this under GSSOC.

**Comment by Anjaliavv51** [comment]
@sunny0625

**Comment by 143divya** [comment]
Can you please assign me this issue for gssoc'24

**Comment by Anjaliavv51** [comment]
@sunny0625 please assign me this issue

**Comment by Anjaliavv51** [comment]
@sunny0625 please assign me this issue
