### ISSUE TITLE
Font-family issue

### ISSUE THREAD

**Issue by Chinmayeep58** [khushi-joshi-05/Food-ordering-website#940]
The font-family of the navbar is different is all the pages. The same font-family would enable users to have a better experience.
Please assign this issue to me, so that I can fix this issue.

For instance, there is a difference in font-family in the home page and menu page navbars
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/146485755/186d99b6-0305-4b5c-9b24-75bc88799b00)
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/146485755/d4a18bf1-18cd-43c5-a44a-ce7eb7c7c468)

Thank you

**Comment by Aashka19** [comment]
Hey could you please assign me this issue under GSSOC 24, I would be happy to contribute!
