### ISSUE TITLE
[Update]: Update the Chat delete button

### ISSUE THREAD

**Issue by SrinivasDevolper** [khushi-joshi-05/Food-ordering-website#959]
If the user clicks the delete button without chatting in the chat box, the delete button should not work

**Actual Behaviour**:-

https://github.com/khushi-joshi-05/Food-ordering-website/assets/121508628/74a09447-7008-4869-87f4-cf9f40ca1caa

**I am GSSOC24 Contributor
Please assign me this issue, I would like to work on it**

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
