### ISSUE TITLE
feature navbar

### ISSUE THREAD

**Issue by siddhant-2002** [khushi-joshi-05/Food-ordering-website#966]
navbar is having very basic styling look i would like to work on it and looking stylish 

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/112260375/2d16cbd5-97c5-4fd8-b7d7-8fb6e187e0b8)

**Comment by Aashka19** [comment]
i've studied your prject,please assign it to me under gssoc 24

**Comment by Khushi-Pushkar** [comment]
hey  , please assign this to me, thank you.

**Comment by Khushi-Pushkar** [comment]
I am gssoc contributer , I want to work on this issue  . Creating an attractive and unique navigation bar (navbar)  can significantly enhance user engagement. Can u please aassign this to me @khushi-joshi-05
