### ISSUE TITLE
Basic Changes in Redirection

### ISSUE THREAD

**Issue by Drona-Srivastava** [khushi-joshi-05/Food-ordering-website#98]
Hi i have noticed that redirection links from navbar to Menu and others are not working and also the links open in a new tab each time we click a navbar link which creates a mess in the tab bar of users browser which does not feel good/
Also the font for about is too small to be read comfortably which it should for a better experience for the user.
I have the solution ready. Please assign me this issue under GSSoC 24 to work as a contributor

1. This Screenshot shows the mess in tab bar i was talking about.

![Screenshot 2024-05-11 074034](https://github.com/khushi-joshi-05/Food-ordering-website/assets/120251095/6346681e-35ff-4fb9-845c-fa6932c9fe26)

2. This Screenshot shows the text size for about paragraph right now which is quite uncomfortable to read. 

![Screenshot 2024-05-11 074320](https://github.com/khushi-joshi-05/Food-ordering-website/assets/120251095/205164e7-461d-4661-92aa-9a7c1f9dfc7c)

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by Shivangbarnwal** [comment]
I would like to fix the issue. Please assign it to me under GSSoC 24.

**Comment by Drona-Srivastava** [comment]
@khushi-joshi-05  Please assign me this issue raised by me under GSSoC 24 so that i can create the PR for this as i am ready with the change.
