### ISSUE TITLE
Sign Up page is partially hidden

### ISSUE THREAD

**Issue by harsh02mishra** [khushi-joshi-05/Food-ordering-website#980]
The signup heading is hidden and while we scroll down it overlaps.

![New](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144336311/fea627dd-e7dc-41a3-ab17-cd7a6d09175a)
![New2](https://github.com/khushi-joshi-05/Food-ordering-website/assets/144336311/1ed74199-10c6-455a-a0c8-00c56b6cb992)

@khushi-joshi-05 please assign this to me under GSSoC'24.

**Comment by khushi-joshi-05** [comment]
👍

**Comment by sauraabhh** [comment]
hey ! I am interested to fix this bug so please assign me this under GSSoC 24
