### ISSUE TITLE
Create Reservation Form: Implement Navigation Triggered by 'Book a Table' Button

### ISSUE THREAD

**Issue by Pratik2401** [khushi-joshi-05/Food-ordering-website#99]
I'll develop a reservation form triggered by the 'Book a Table' button, facilitating seamless navigation for users interested in making reservations. This feature will enhance user experience and streamline the booking process. Assigning this task to me for GSSoC contribution will enable efficient implementation of the reservation form functionality
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/105542579/ede78c78-0c72-4541-aa88-c0a66755e06d)

**Comment by vedanshipathak** [comment]
@khushi-joshi-05 please assign me this issue under GSSOC'24 . i have already created one food ordering website with a reservation page. I can create good reservation page.
