### ISSUE TITLE
[Enhancement]:  Navbar Alignment and gap

### ISSUE THREAD

**Issue by theeayushkumar** [khushi-joshi-05/Food-ordering-website#998]
1.Padding and Margin Adjustments:
Adjust the padding and margin of the nav elements to ensure they align properly.
Reduce the gap between the links and align them centrally.

2.Flexbox for Alignment:
Use Flexbox to handle the alignment of the items within the navbar. This ensures even spacing and proper alignment.

3.Container Width:
Ensure the container holding the navbar spans the full width of the viewport and centers its content properly.

![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/128235540/fc87ca5f-62d8-449f-82c1-e60d5875923b)

**Comment by theeayushkumar** [comment]
assign me this issue

**Comment by sunny0625** [comment]
@theeayushkumar are you still up for this issue?

**Comment by theeayushkumar** [comment]
> @theeayushkumar are you still up for this issue?

yes I am working on it.
