### ISSUE TITLE
Contact us option in footer is redirecting to exclusive offers page

### ISSUE THREAD

**Issue by SalehaTabassum** [khushi-joshi-05/Food-ordering-website#999]
Hello Pa,
in footer when we click contact option its redirecting to exclusive offers page instead of contact us page.

@khushi-joshi-05 Please assign this issue to me Under GSSOC 2024 and add appropriate labels to it.

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
